### ISSUE TITLE
argument must be an int, or have a fileno() method.

### ISSUE THREAD

**Issue by emilstahl97** [Exa-Networks/exabgp#1020]
I'm getting this issue while trying to run "exabgp ./conf.ini" on Ubuntu 20.4 with exabgp installed from apt and pip3. Running python 3.8.5.

My conf.ini includes the following:
```
neighbor 192.168.97.111 {                 # Remote neighbor to peer with
    router-id 192.168.97.2;                 # Our local router-id
    local-address 192.168.97.2;        # Our local update-source
    local-as 65000;                           # Our local AS
    peer-as 65000;                           # Peer's AS
}
```
I've tried placing the conf.ini in /etc/exabgp without luck.

I'm following this tutorial on ExaBGP: https://thepacketgeek.com/exabgp/getting-started/

Expected behavior is that it should start sending messages. 
This is my first time using exabgp so I'm sorry if this is an easy fix, but haven't found anything related to it. 

Output:
```
emilstahl@RoutingVM:~/Git/Degree-Project-in-Information-and-Communication-Technology-IA150X/exabgp$ exabgp -d conf.ini
19:46:14 | 26932  | welcome       | Thank you for using ExaBGP
19:46:14 | 26932  | version       | 4.2.4   
19:46:14 | 26932  | interpreter   | 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
19:46:14 | 26932  | os            | Linux RoutingVM 5.8.0-40-generic #45~20.04.1-Ubuntu SMP Fri Jan 15 11:35:04 UTC 2021 x86_64
19:46:14 | 26932  | installation  |         
19:46:14 | 26932  | cli control   | named pipes for the cli are:
19:46:14 | 26932  | cli control   | to send commands  /run/exabgp/exabgp.in
19:46:14 | 26932  | cli control   | to read responses /run/exabgp/exabgp.out
19:46:14 | 26932  | configuration | performing reload of exabgp 4.2.4
19:46:14 | 26932  | configuration | > neighbor         | '192.168.97.111'
19:46:14 | 26932  | configuration | . router-id        | '192.168.97.2'
19:46:14 | 26932  | configuration | . local-address    | '192.168.97.2'
19:46:14 | 26932  | configuration | . local-as         | '65000'
19:46:14 | 26932  | configuration | . peer-as          | '65000'
19:46:14 | 26932  | configuration | < neighbor         | 
19:46:14 | 26932  | reactor       | new peer: neighbor 192.168.97.111 local-ip 192.168.97.2 local-as 65000 peer-as 65000 router-id 192.168.97.2 family-allowed in-open
19:46:14 | 26932  | reactor       | loaded new configuration successfully
19:46:14 | 26932  | process       | forked process api-internal-cli-ed649e68
19:46:14 | 26932  | reactor       | initialising connection to peer-1
19:46:14 | 26932  | outgoing-1    | attempting connection to 192.168.97.111:179
19:46:14 | 26932  | outgoing-1    | connection to 192.168.97.111:179 failed
19:46:14 | 26932  | outgoing-1    | Could not bind to local ip 192.168.97.2 - [Errno 99] Cannot assign requested address
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 245, in run
    self.loop()
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 218, in loop
    ready = self.read_on(reading)
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 104, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
19:46:14 | 26932  | process       | process api-internal-cli-ed649e68 ended, restarting it
19:46:14 | 26932  | process       | terminating process api-internal-cli-ed649e68
19:46:14 | 26932  | process       | forked process api-internal-cli-ed649e68
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 245, in run
    self.loop()
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 218, in loop
    ready = self.read_on(reading)
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 104, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
19:46:15 | 26932  | process       | process api-internal-cli-ed649e68 ended, restarting it
19:46:15 | 26932  | process       | terminating process api-internal-cli-ed649e68
19:46:15 | 26932  | process       | forked process api-internal-cli-ed649e68
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 245, in run
    self.loop()
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 218, in loop
    ready = self.read_on(reading)
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 104, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
19:46:15 | 26932  | process       | process api-internal-cli-ed649e68 ended, restarting it
19:46:15 | 26932  | process       | terminating process api-internal-cli-ed649e68
19:46:15 | 26932  | process       | forked process api-internal-cli-ed649e68
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 245, in run
    self.loop()
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 218, in loop
    ready = self.read_on(reading)
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 104, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
19:46:15 | 26932  | process       | process api-internal-cli-ed649e68 ended, restarting it
19:46:15 | 26932  | process       | terminating process api-internal-cli-ed649e68
19:46:15 | 26932  | process       | forked process api-internal-cli-ed649e68
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 245, in run
    self.loop()
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 218, in loop
    ready = self.read_on(reading)
  File "/usr/lib/python3/dist-packages/exabgp/application/control.py", line 104, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
19:46:15 | 26932  | process       | process api-internal-cli-ed649e68 ended, restarting it
19:46:15 | 26932  | process       | terminating process api-internal-cli-ed649e68
19:46:15 | 26932  | process       | forked process api-internal-cli-ed649e68
19:46:15 | 26932  | process       | Too many death for api-internal-cli-ed649e68 (5) terminating program
19:46:15 | 26932  | reactor       | Problem when sending message(s) to helper program, stopping
19:46:15 | 26932  | reactor       | performing shutdown
19:46:15 | 26932  | process       | terminating process api-internal-cli-ed649e68
emilstahl@RoutingVM:~/Git/Degree-Project-in-Information-and-Communication-Technology-IA150X/exabgp$ 
```

Also available here: https://pastebin.com/eeQrrcmt

Thanks in advance

**Comment by thomas-mangin** [comment]
You are running an old version of exabgp. AFAIR, this bug has already been fixed.

**Comment by ljb2of3** [comment]
I'm having the same issue on 4.2.12, which appears to have just been released. I tried all the way back to 4.2.9 and had the exact same issue.

```
landy@anycast-dns-01:~$ exabgp exabgp.conf
05:18:13 | 19416  | welcome       | Thank you for using ExaBGP
05:18:13 | 19416  | version       | 4.2.12
05:18:13 | 19416  | interpreter   | 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
05:18:13 | 19416  | os            | Linux anycast-dns-01 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64
05:18:13 | 19416  | installation  | /usr/local
05:18:13 | 19416  | cli control   | named pipes for the cli are:
05:18:13 | 19416  | cli control   | to send commands  /run/exabgp.in
05:18:13 | 19416  | cli control   | to read responses /run/exabgp.out
05:18:13 | 19416  | configuration | performing reload of exabgp 4.2.12
05:18:13 | 19416  | reactor       | loaded new configuration successfully
05:18:13 | 19416  | api           | route added to neighbor 10.10.26.1 local-ip 10.10.26.5 local-as 65010 peer-as 65210 router-id 129.244.26.5 family-allowed in-open : 10.10.10.10/32 next-hop self
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 247, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 220, in loop
    ready = self.read_on(reading)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 106, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 247, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 220, in loop
    ready = self.read_on(reading)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 106, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 247, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 220, in loop
    ready = self.read_on(reading)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 106, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
05:18:14 | 19416  | api           | route added to neighbor 10.10.26.1 local-ip 10.10.26.5 local-as 65010 peer-as 65210 router-id 129.244.26.5 family-allowed in-open : 10.10.10.10/32 next-hop self
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 247, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 220, in loop
    ready = self.read_on(reading)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 106, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
argument must be an int, or have a fileno() method.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 247, in run
    self.loop()
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 220, in loop
    ready = self.read_on(reading)
  File "/usr/local/lib/python3.8/dist-packages/exabgp/application/control.py", line 106, in read_on
    poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
TypeError: argument must be an int, or have a fileno() method.
05:18:15 | 19416  | process       | Too many death for api-internal-cli-ad0c83e0 (5) terminating program
05:18:15 | 19416  | reactor       | Problem when sending message(s) to helper program, stopping
05:18:15 | 19416  | reactor       | performing shutdown
landy@anycast-dns-01:~$
```

**Comment by thomas-mangin** [comment]
From the information provided, I am not sure how to trigger the issue so could you please confirm if this patch fixes the issue or not:
```
--- a/lib/exabgp/application/control.py
+++ b/lib/exabgp/application/control.py
@@ -81,7 +81,7 @@ class Control(object):
 
     def cleanup(self):
         def _close(pipe):
-            if self.r_pipe:
+            if pipe:
                 try:
                     os.close(pipe)
                 except (OSError, IOError, TypeError):
@@ -103,7 +103,8 @@ class Control(object):
 
         poller = select.poll()
         for io in reading:
-            poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
+            if io is not None:
+                poller.register(io, select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLNVAL | select.POLLERR)
 
         ready = []
         for io, event in poller.poll(sleep_time):
````

**Comment by ljb2of3** [comment]
Yes, that appears to have fixed the issue. I no longer see the error message or tracebacks.

**Comment by thomas-mangin** [comment]
ok, released a version of the code with the fix. thank you for your help :-)
