### ISSUE TITLE
Build master failure with python:3-slim-buster Docker image

### ISSUE THREAD

**Issue by leleobhz** [Exa-Networks/exabgp#1025]
### Issue

Build exabgp using python:3-slim-buster Docker image leads to the following error:

```
STEP 5: RUN cd /tmp     && echo Building ${buildver}     && pip install -U setuptools     && pip install git+https://github.com/Exa-Networks/exabgp.git@${buildver}
Building master
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (53.0.0)
Collecting git+https://github.com/Exa-Networks/exabgp.git@master
  Cloning https://github.com/Exa-Networks/exabgp.git (to revision master) to ./pip-req-build-iy6ilhpv
  Running command git clone -q https://github.com/Exa-Networks/exabgp.git /tmp/pip-req-build-iy6ilhpv
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpi25gub4f
       cwd: /tmp/pip-req-build-iy6ilhpv
  Complete output (57 lines):
  /usr/local/bin/python: can't open file '/tmp/pip-req-build-iy6ilhpv/lib/exabgp/version.py': [Errno 2] No such file or directory
  Traceback (most recent call last):
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 387, in _parse_attr
      return getattr(StaticModule(module_name), attr_name)
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 24, in __init__
      spec = importlib.util.find_spec(name)
    File "/usr/local/lib/python3.9/importlib/util.py", line 94, in find_spec
      parent = __import__(parent_name, fromlist=['__path__'])
  ModuleNotFoundError: No module named 'exabgp'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 53, in <module>
      setuptools.setup(
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 121, in setup
      dist.parse_config_files()
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 680, in parse_config_files
      parse_configuration(self, self.command_options,
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 157, in parse_configuration
      meta.parse()
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 463, in parse
      section_parser_method(section_options)
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
      self[name] = value
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
      value = parser(value)
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 552, in _parse_version
      version = self._parse_attr(value, self.package_dir)
    File "/tmp/pip-build-env-o16_4ovl/overlay/lib/python3.9/site-packages/setuptools/config.py", line 390, in _parse_attr
      module = importlib.import_module(module_name)
    File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'exabgp'
  ----------------------------------------
WARNING: Discarding git+https://github.com/Exa-Networks/exabgp.git@master. Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpi25gub4f Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpi25gub4f Check the logs for full command output.
Error: error building at STEP "RUN cd /tmp     && echo Building ${buildver}     && pip install -U setuptools     && pip install git+https://github.com/Exa-Networks/exabgp.git@${buildver}": error while running runtime: exit status 1
```

###  Steps to reproduce

Build the following Dockerfile

```
FROM python:3-slim-buster

ARG buildver="master"

RUN apt update \
    && apt -y dist-upgrade \
    && apt install -y git \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN cd /tmp \
    && echo Building ${buildver} \
    && pip install -U setuptools \
    && pip install git+https://github.com/Exa-Networks/exabgp.git@${buildver}

WORKDIR /usr/local/etc/exabgp
```

Using this command line in same dir of Dockerfile.:

```
docker build --build-arg buildver=master -t exabgp ./
```

**Comment by thomas-mangin** [comment]
Thank you - I will have a look.

**Comment by thomas-mangin** [comment]
I will however point that master is currently in flux and is not advised for production :-)

**Comment by leleobhz** [comment]
> I will however point that master is currently in flux and is not advised for production :-)

Hello Thomas,

I do a massive build here for my containers and I keep it available to fast-change if needed (Example, some upstream change to emergencies).

![image](https://user-images.githubusercontent.com/201189/108390477-7c367c00-71ef-11eb-91cb-16371a8855b7.png)

This is the reason I compile more than one TAG and Master, but its just for keep it in fast track in case of some need.

Thanks you for the advise - you're correct. And thank you to take a look at the issue!

**Comment by thomas-mangin** [comment]
ok, should be working now with https://github.com/Exa-Networks/exabgp/commit/4890322b32bf3c8c1c9d00d0746f2718a98e200f and also added the docker file for remote installation to the repository.
