### ISSUE TITLE
BGP-LS link NLRI not parsed

### ISSUE THREAD

**Issue by esserrge** [Exa-Networks/exabgp#1048]
**Describe the bug**

ExaBGP throws an python TypeError when receiving a bgp-ls link nlri update from a Huawei speaker

**To Reproduce**

Configure bgp-ls between Huawei router and ExaBGP, announce link nlri.

**Expected behavior**

I'd expect ExaBGP to correclty parse the update and not throw a traceback.

**Environment (please complete the following information):**

 - OS: Ubuntu 20.04.3 LTS
 - Version 4.2.4 and 4.2.11 behaves the same

```
fredrlon@ban-ztp:~$ env exabgp.log.all=true ./exabgp-4.2.11/sbin/exabgp -d ./conf.ini 
fatal: not a git repository (or any of the parent directories): .git
17:57:05 | 840316 | welcome       | Thank you for using ExaBGP
17:57:05 | 840316 | version       | 4.2.11  
17:57:05 | 840316 | interpreter   | 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
17:57:05 | 840316 | os            | Linux ban-ztp 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64
17:57:05 | 840316 | installation  | /home/fredrlon/exabgp-4.2.11
17:57:05 | 840316 | advice        | environment file missing
17:57:05 | 840316 | advice        | generate it using "exabgp --fi > /home/fredrlon/exabgp-4.2.11/etc/exabgp/exabgp.env"
17:57:05 | 840316 | cli control   | named pipes for the cli are:
17:57:05 | 840316 | cli control   | to send commands  /run/exabgp/exabgp.in
17:57:05 | 840316 | cli control   | to read responses /run/exabgp/exabgp.out
17:57:05 | 840316 | configuration | performing reload of exabgp 4.2.11
17:57:05 | 840316 | configuration | > neighbor         | '130.244.96.1'
17:57:05 | 840316 | configuration | . local-address    | '130.244.98.51'
17:57:05 | 840316 | configuration | . local-as         | '1257'
17:57:05 | 840316 | configuration | . peer-as          | '1257'
17:57:05 | 840316 | configuration | > family           | 
17:57:05 | 840316 | configuration | . bgp-ls           | 'bgp-ls'
17:57:05 | 840316 | configuration | < family           | 
17:57:05 | 840316 | configuration | < neighbor         | 
17:57:05 | 840316 | reactor       | new peer: neighbor 130.244.96.1 local-ip 130.244.98.51 local-as 1257 peer-as 1257 router-id 130.244.98.51 family-allowed in-open
17:57:05 | 840316 | reactor       | loaded new configuration successfully
17:57:05 | 840316 | process       | forked process api-internal-cli-e7fa4210
17:57:05 | 840316 | reactor       | initialising connection to peer-1
17:57:05 | 840316 | outgoing-1    | attempting connection to 130.244.96.1:179
17:57:05 | 840316 | outgoing-1    | sending TCP payload (  49) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0031 0104 04E9 00B4 82F4 6233 1402 0601 0440 0400 4702 0641 0400 0004 E902 0206 00
17:57:05 | 840316 | outgoing-1    | >> OPEN version=4 asn=1257 hold_time=180 router_id=130.244.98.51 capabilities=[Multiprotocol(bgp-ls bgp-ls), Extended Message(65535), ASN4(1257)]
17:57:05 | 840316 | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002D 01
17:57:05 | 840316 | outgoing-1    | received TCP payload (  26) 0404 E900 B482 F460 0110 020E 0104 4004 0047 0200 4104 0000 04E9
17:57:05 | 840316 | outgoing-1    | << message of type OPEN
17:57:05 | 840316 | outgoing-1    | << OPEN version=4 asn=1257 hold_time=180 router_id=130.244.96.1 capabilities=[Multiprotocol(bgp-ls bgp-ls), Route Refresh, ASN4(1257)]
17:57:05 | 840316 | ka-outgoing-1 | receive-timer 60 second(s) left
17:57:05 | 840316 | outgoing-1    | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
17:57:05 | 840316 | outgoing-1    | >> KEEPALIVE (OPENCONFIRM)
17:57:05 | 840316 | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
17:57:05 | 840316 | outgoing-1    | << message of type KEEPALIVE
17:57:05 | 840316 | ka-outgoing-1 | receive-timer 180 second(s) left
17:57:05 | 840316 | reactor       | connected to peer-1 with outgoing-1 130.244.98.51-130.244.96.1
17:57:05 | 840316 | outgoing-1    | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0340 0447
17:57:05 | 840316 | outgoing-1    | >> EOR bgp-ls bgp-ls
17:57:05 | 840316 | peer-1        | >> EOR(s)
17:57:05 | 840316 | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 006A 02
17:57:05 | 840316 | outgoing-1    | received TCP payload (  87) 0000 0053 4001 0102 4002 0080 0404 0000 0000 4005 0400 0000 6490 0E00 3A40 0447 0482 F460 0100 0001 002D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 01
17:57:05 | 840316 | outgoing-1    | << message of type UPDATE
17:57:05 | 840316 | parser        | parsing UPDATE (  87) 0000 0053 4001 0102 4002 0080 0404 0000 0000 4005 0400 0000 6490 0E00 3A40 0447 0482 F460 0100 0001 002D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 01
17:57:05 | 840316 | routes        | withdrawn NLRI none
17:57:05 | 840316 | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 02
17:57:05 | 840316 | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
17:57:05 | 840316 | parser        | attribute med                flag 0x80 type 0x04 len 0x04 payload 0000 0000
17:57:05 | 840316 | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
17:57:05 | 840316 | parser        | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0x3a payload 4004 4704 82F4 6001 0000 0100 2D03 0000 0000 0000 0000 0100 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 6001
17:57:05 | 840316 | parser        | NLRI      bgp-ls bgp-ls      without path-information     payload 0001 002D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 01
17:57:05 | 840316 | routes        | announced NLRI none
17:57:05 | 840316 | parser        | decoded UPDATE (   0) json { "exabgp": "4.0.1", "time": 1631894225.9785688, "host" : "ban-ztp", "pid" : 840316, "ppid" : 839294, "counter": 1, "type": "update", "neighbor": { "address": { "local": "130.244.98.51", "peer": "130.244.96.1" }, "asn": { "local": 1257, "peer": 1257 } , "direction": "in", "message": { "update": { "attribute": { "origin": "incomplete", "med": 0, "local-preference": 100 }, "announce": { "bgp-ls bgp-ls": { "130.244.96.1": [ { "ls-nlri-type": "bgpls-node", "l3-routing-topology": 0, "protocol-id": 3, "node-descriptors": { "autonomous-system": 1257, "bgp-ls-identifier": "2197053441", "ospf-area-id": "0.0.0.17", "router-id": "130.244.96.1" }, "nexthop": "130.244.96.1" } ] } } } } } }
17:57:05 | 840316 | peer-1        | << UPDATE #1
17:57:05 | 840316 | peer-1        |    UPDATE #1 nlri  (   2) { "ls-nlri-type": "bgpls-node", "l3-routing-topology": 0, "protocol-id": 3, "node-descriptors": { "autonomous-system": 1257, "bgp-ls-identifier": "2197053441", "ospf-area-id": "0.0.0.17", "router-id": "130.244.96.1" }, "nexthop": "130.244.96.1" }
17:57:05 | 840316 | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0072 02
17:57:05 | 840316 | outgoing-1    | received TCP payload (  95) 0000 005B 4001 0102 4002 0080 0404 0000 0000 4005 0400 0000 6480 1D05 0400 0001 2090 0E00 3A40 0447 0482 F460 0100 0001 002D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D
17:57:05 | 840316 | outgoing-1    | << message of type UPDATE
17:57:05 | 840316 | parser        | parsing UPDATE (  95) 0000 005B 4001 0102 4002 0080 0404 0000 0000 4005 0400 0000 6480 1D05 0400 0001 2090 0E00 3A40 0447 0482 F460 0100 0001 002D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D
17:57:05 | 840316 | routes        | withdrawn NLRI none
17:57:05 | 840316 | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 02
17:57:05 | 840316 | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
17:57:05 | 840316 | parser        | attribute med                flag 0x80 type 0x04 len 0x04 payload 0000 0000
17:57:05 | 840316 | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
17:57:05 | 840316 | parser        | attribute bgp-ls             flag 0x80 type 0x1d len 0x05 payload 0400 0001 20
17:57:05 | 840316 | parser        | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0x3a payload 4004 4704 82F4 6001 0000 0100 2D03 0000 0000 0000 0000 0100 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 600D
17:57:05 | 840316 | parser        | NLRI      bgp-ls bgp-ls      without path-information     payload 0001 002D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D
17:57:05 | 840316 | routes        | announced NLRI none
17:57:05 | 840316 | parser        | decoded UPDATE (   0) json { "exabgp": "4.0.1", "time": 1631894225.986203, "host" : "ban-ztp", "pid" : 840316, "ppid" : 839294, "counter": 2, "type": "update", "neighbor": { "address": { "local": "130.244.98.51", "peer": "130.244.96.1" }, "asn": { "local": 1257, "peer": 1257 } , "direction": "in", "message": { "update": { "attribute": { "origin": "incomplete", "med": 0, "local-preference": 100, "bgp-ls": { "node-flags": {"O": 0, "T": 0, "E": 1, "B": 0, "R": 0, "V": 0, "RSV": 0} } }, "announce": { "bgp-ls bgp-ls": { "130.244.96.1": [ { "ls-nlri-type": "bgpls-node", "l3-routing-topology": 0, "protocol-id": 3, "node-descriptors": { "autonomous-system": 1257, "bgp-ls-identifier": "2197053441", "ospf-area-id": "0.0.0.17", "router-id": "130.244.96.13" }, "nexthop": "130.244.96.1" } ] } } } } } }
17:57:05 | 840316 | peer-1        | << UPDATE #2
17:57:05 | 840316 | peer-1        |    UPDATE #2 nlri  (   2) { "ls-nlri-type": "bgpls-node", "l3-routing-topology": 0, "protocol-id": 3, "node-descriptors": { "autonomous-system": 1257, "bgp-ls-identifier": "2197053441", "ospf-area-id": "0.0.0.17", "router-id": "130.244.96.13" }, "nexthop": "130.244.96.1" }
17:57:05 | 840316 | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0105 02
17:57:05 | 840316 | outgoing-1    | received TCP payload ( 242) 0000 00EE 4001 0102 4002 0080 0404 0000 0000 4005 0400 0000 6480 1D07 0447 0003 0003 E890 0E00 CB40 0447 0482 F460 0100 0002 005D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0101 0100 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D01 0200 0882 F460 5E82 F460 5F00 0200 5D03 0000 0000 0000 0000 0100 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 600D 0101 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 6001 0102 0008 82F4 605F 82F4 605E
17:57:05 | 840316 | outgoing-1    | << message of type UPDATE
17:57:05 | 840316 | parser        | parsing UPDATE ( 242) 0000 00EE 4001 0102 4002 0080 0404 0000 0000 4005 0400 0000 6480 1D07 0447 0003 0003 E890 0E00 CB40 0447 0482 F460 0100 0002 005D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0101 0100 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D01 0200 0882 F460 5E82 F460 5F00 0200 5D03 0000 0000 0000 0000 0100 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 600D 0101 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 6001 0102 0008 82F4 605F 82F4 605E
17:57:05 | 840316 | routes        | withdrawn NLRI none
17:57:05 | 840316 | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 02
17:57:05 | 840316 | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
17:57:05 | 840316 | parser        | attribute med                flag 0x80 type 0x04 len 0x04 payload 0000 0000
17:57:05 | 840316 | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
17:57:05 | 840316 | parser        | attribute bgp-ls             flag 0x80 type 0x1d len 0x07 payload 0447 0003 0003 E8
17:57:05 | 840316 | parser        | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0xcb payload 4004 4704 82F4 6001 0000 0200 5D03 0000 0000 0000 0000 0100 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 6001 0101 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 600D 0102 0008 82F4 605E 82F4 605F 0002 005D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D01 0100 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0101 0200 0882 F460 5F82 F460 5E
17:57:05 | 840316 | parser        | NLRI      bgp-ls bgp-ls      without path-information     payload 0002 005D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0101 0100 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D01 0200 0882 F460 5E82 F460 5F00 0200 5D03 0000 0000 0000 0000 0100 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 600D 0101 0020 0200 0004 0000 04E9 0201 0004 82F4 6001 0202 0004 0000 0011 0203 0004 82F4 6001 0102 0008 82F4 605F 82F4 605E
17:57:05 | 840316 | parser        | NLRI      bgp-ls bgp-ls      without path-information     payload 0002 005D 0300 0000 0000 0000 0001 0000 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0D01 0100 2002 0000 0400 0004 E902 0100 0482 F460 0102 0200 0400 0000 1102 0300 0482 F460 0101 0200 0882 F460 5F82 F460 5E
17:57:05 | 840316 | routes        | announced NLRI none
17:57:05 | 840316 | outgoing-1    | could not decode message "2"
17:57:05 | 840316 | outgoing-1    | object of type 'NoneType' has no len()
17:57:05 | 840316 | outgoing-1    | Traceback (most recent call last):
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/reactor/protocol.py", line 238, in read_message
17:57:05 | 840316 | outgoing-1    |     message = Message.unpack(msg_id, body, self.negotiated)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/bgp/message/message.py", line 180, in unpack
17:57:05 | 840316 | outgoing-1    |     return cls.klass(message).unpack_message(data, negotiated)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/bgp/message/update/__init__.py", line 291, in unpack_message
17:57:05 | 840316 | outgoing-1    |     logger.debug(LazyFormat('decoded UPDATE', '', parsed), 'parser')
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/logger.py", line 355, in debug
17:57:05 | 840316 | outgoing-1    |     self._report(message, source, level)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/logger.py", line 347, in _report
17:57:05 | 840316 | outgoing-1    |     for line in message.split('\n'):
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/logger.py", line 53, in split
17:57:05 | 840316 | outgoing-1    |     return str(self).split(char)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/logger.py", line 56, in __str__
17:57:05 | 840316 | outgoing-1    |     formated = self.formater(self.message)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/bgp/message/update/__init__.py", line 289, in parsed
17:57:05 | 840316 | outgoing-1    |     return 'json %s' % Response.JSON(json_version).update(negotiated.neighbor, 'in', update, None, '', '')
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/reactor/api/response/json.py", line 321, in update
17:57:05 | 840316 | outgoing-1    |     message = self._update(update)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/reactor/api/response/json.py", line 287, in _update
17:57:05 | 840316 | outgoing-1    |     m += ', '.join('%s' % nlri.json(compact=self.compact) for nlri in nlris)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/reactor/api/response/json.py", line 287, in <genexpr>
17:57:05 | 840316 | outgoing-1    |     m += ', '.join('%s' % nlri.json(compact=self.compact) for nlri in nlris)
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/bgp/message/update/nlri/bgpls/link.py", line 192, in json
17:57:05 | 840316 | outgoing-1    |     if self.link_ids:
17:57:05 | 840316 | outgoing-1    |   File "/home/fredrlon/exabgp-4.2.11/lib/exabgp/bgp/message/update/nlri/bgpls/tlvs/linkid.py", line 68, in __len__
17:57:05 | 840316 | outgoing-1    |     return len(self._packed)
17:57:05 | 840316 | outgoing-1    | TypeError: object of type 'NoneType' has no len()
17:57:05 | 840316 | outgoing-1    |         
17:57:05 | 840316 | outgoing-1    | sending TCP payload (  62) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003E 0301 0063 616E 206E 6F74 2064 6563 6F64 6520 7570 6461 7465 206D 6573 7361 6765 206F 6620 7479 7065 2022 3222
17:57:05 | 840316 | outgoing-1    | >> NOTIFICATION (1,0,"can not decode update message of type "2"")
17:57:05 | 840316 | outgoing-1    | peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
17:57:05 | 840316 | outgoing-1    | outgoing-1 130.244.98.51-130.244.96.1, closing connection
17:57:05 | 840316 | reactor       | initialising connection to peer-1
17:57:06 | 840316 | outgoing-2    | attempting connection to 130.244.96.1:179
17:57:06 | 840316 | outgoing-2    | sending TCP payload (  49) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0031 0104 04E9 00B4 82F4 6233 1402 0601 0440 0400 4702 0641 0400 0004 E902 0206 00
17:57:06 | 840316 | outgoing-2    | outgoing-2 130.244.98.51-130.244.96.1, closing connection
17:57:06 | 840316 | outgoing-2    | peer reset, message [closing connection] error[Broken TCP connection]
17:57:06 | 840316 | outgoing-2    | outgoing-2 130.244.98.51-130.244.96.1, closing connection
17:57:07 | 840316 | reactor       | initialising connection to peer-1
17:57:07 | 840316 | outgoing-3    | attempting connection to 130.244.96.1:179
17:57:07 | 840316 | outgoing-3    | sending TCP payload (  49) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0031 0104 04E9 00B4 82F4 6233 1402 0601 0440 0400 4702 0641 0400 0004 E902 0206 00
17:57:07 | 840316 | outgoing-3    | outgoing-3 130.244.98.51-130.244.96.1, closing connection
17:57:07 | 840316 | outgoing-3    | peer reset, message [closing connection] error[Broken TCP connection]
17:57:07 | 840316 | outgoing-3    | outgoing-3 130.244.98.51-130.244.96.1, closing connection
^C17:57:07 | 840316 | reactor       | ^C received
17:57:07 | 840316 | reactor       | performing shutdown
17:57:07 | 840316 | process       | terminating process api-internal-cli-e7fa4210
fredrlon@ban-ztp:~$ [A^C
```

**Comment by thomas-mangin** [comment]
ok, thank you, this is not some code I authored but I will look into it.
