### ISSUE TITLE
Fix support for RFC 7752

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#1057]
A user asked about the decoding of BGP LS NLRI encoded using RFC 7752
https://datatracker.ietf.org/doc/html/rfc7752

I added the option `--nlri` to decode so to be able to test NLRI payload decode without having to create complete update messages

With the payload `nlri : 00 01 03 00 00 00 00 00 00 00 00 01 00 00 20 02 00 00 04 00 00 00 01 02 01 00 04 c0 a8 7a 7e 02 02 00 04 00 00 00 00 02 03 00 04 0a 04 04 04` we get the following as the decoding for that RFC is not implemented, and the protocol ID not in the list of known ones:

(-p starts pdb on failure to inspect the running code)

```
at 20:48:10 ❯ ./sbin/exabgp decode -p --nlri etc/exabgp/conf-bgpls.conf "00 01 03 00 00 00 00 00 00 00 00 01 00 00 20 02 00 00 04 00 00 00 01 02 01 00 04 c0 a8 7a 7e 02 02 00 04 00 00 00 00 02 03 00 04 0a 04 04 04"
configuration performing reload of exabgp master-0e01923695429adeeec673a3e28cbb497a4bb949
reactor       loaded new configuration successfully
parser        could not parse the nlri
parser        Traceback (most recent call last):
parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/configuration/check.py", line 230, in check_nlri
parser            nlri, announced = NLRI.unpack_nlri(afi, safi, announced, IN.ANNOUNCED, addpath)
parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/nlri.py", line 102, in unpack_nlri
parser            return cls.registered_nlri[key].unpack_nlri(a, s, data, action, addpath)
parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/nlri.py", line 122, in unpack_nlri
parser            klass = cls.registered_bgpls[code].unpack_nlri(bgp[4 : length + 4], rd)
parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/node.py", line 69, in unpack_nlri
parser            raise Exception('Protocol-ID {} is not valid'.format(proto_id))
parser        Exception: Protocol-ID 0 is not valid
parser                

********************************************************************************
EXABGP HAD AN INTERNAL ISSUE / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP and we could not keep the program
running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : master-0e01923695429adeeec673a3e28cbb497a4bb949
Python version : 3.8.12 (default, Oct 13 2021, 06:42:42)  [Clang 13.0.0 (clang-1300.0.29.3)]
System Uname   : Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
System MaxInt  : 9223372036854775807
Root           : /Users/thomas/Coding/exabgp/master

Environment:

-- Traceback

Traceback (most recent call last):
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/application/main.py", line 89, in <module>
    main()
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/application/main.py", line 82, in main
    cmdarg.func(cmdarg)
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/application/decode.py", line 71, in cmdline
    Reactor([getconf(cmdarg.configuration)]).check(sanitized, cmdarg.nlri)
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/reactor/loop.py", line 233, in check
    if not check(neighbor, route):
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/configuration/check.py", line 230, in check_nlri
    nlri, announced = NLRI.unpack_nlri(afi, safi, announced, IN.ANNOUNCED, addpath)
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/nlri.py", line 102, in unpack_nlri
    return cls.registered_nlri[key].unpack_nlri(a, s, data, action, addpath)
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/nlri.py", line 122, in unpack_nlri
    klass = cls.registered_bgpls[code].unpack_nlri(bgp[4 : length + 4], rd)
  File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/node.py", line 69, in unpack_nlri
    raise Exception('Protocol-ID {} is not valid'.format(proto_id))
Exception: Protocol-ID 0 is not valid


-- Logging History

20:48:22 95971  configuration   . local-as         | '1'
20:48:22 95971  configuration   . peer-as          | '1'
20:48:22 95971  configuration   > family           | 
20:48:22 95971  configuration   . bgp-ls           | 'bgp-ls'
20:48:22 95971  configuration   < family           | 
20:48:22 95971  configuration   < neighbor         | 
20:48:22 95971  reactor         new peer: neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 1 peer-as 1 router-id 1.2.3.4 family-allowed in-open
20:48:22 95971  reactor       loaded new configuration successfully
20:48:22 95971  parser          parsing NLRI b'\x00\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00 \x02\x00\x00\x04\x00\x00\x00\x01\x02\x01\x00\x04\xc0\xa8z~\x02\x02\x00\x04\x00\x00\x00\x00\x02\x03\x00\x04\n\x04\x04\x04'
20:48:22 95971  parser        could not parse the nlri
20:48:22 95971  parser        Traceback (most recent call last):
20:48:22 95971  parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/configuration/check.py", line 230, in check_nlri
20:48:22 95971  parser            nlri, announced = NLRI.unpack_nlri(afi, safi, announced, IN.ANNOUNCED, addpath)
20:48:22 95971  parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/nlri.py", line 102, in unpack_nlri
20:48:22 95971  parser            return cls.registered_nlri[key].unpack_nlri(a, s, data, action, addpath)
20:48:22 95971  parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/nlri.py", line 122, in unpack_nlri
20:48:22 95971  parser            klass = cls.registered_bgpls[code].unpack_nlri(bgp[4 : length + 4], rd)
20:48:22 95971  parser          File "/Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/node.py", line 69, in unpack_nlri
20:48:22 95971  parser            raise Exception('Protocol-ID {} is not valid'.format(proto_id))
20:48:22 95971  parser        Exception: Protocol-ID 0 is not valid
20:48:22 95971  parser                


********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

> /Users/thomas/Coding/exabgp/master/src/exabgp/bgp/message/update/nlri/bgpls/node.py(69)unpack_nlri()
-> raise Exception('Protocol-ID {} is not valid'.format(proto_id))
(Pdb) dir()
['cls', 'data', 'proto_id', 'rd']
(Pdb) cls
<class 'exabgp.bgp.message.update.nlri.bgpls.node.NODE'>
(Pdb) proto_id
0
(Pdb) rd
(Pdb) data
b'\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00 \x02\x00\x00\x04\x00\x00\x00\x01\x02\x01\x00\x04\xc0\xa8z~\x02\x02\x00\x04\x00\x00\x00\x00\x02\x03\x00\x04\n\x04\x04\x04'
```

**Comment by thomas-mangin** [comment]
@ruissalo is it something you have a need for / have worked on please or is it one for me?

**Comment by thomas-mangin** [comment]
I am not sure if the NLRI is correct as it was sent by mail.

**Comment by ruissalo** [comment]
it's been a long time since I worked with these. That said, looking at where the exception shows up, that protocol id doesn't seem to be supported by RFC 7752 (see "Table 2: Protocol Identifiers" in the rfc) - protocols ids go from 1 to 6. Unless there is some sort of parsing error, but seems unlikely. If this is a user report, can they maybe share more info/context?

**Comment by thomas-mangin** [comment]
The length was mising :-) using FF FF for it gives:
```
at 11:48:45 ❯ ./sbin/exabgp decode -p --nlri etc/exabgp/conf-bgpls.conf "00 01 FF FF 03 00 00 00 00 00 00 00 00 01 00 00 20 02 00 00 04 00 00 00 01 02 01 00 04 c0 a8 7a 7e 02 02 00 04 00 00 00 00 02 03 00 04 0a 04 04 04"
configuration performing reload of exabgp master-63e797e99ab5a456c73174ea75d13aed853515fa
reactor       loaded new configuration successfully
parser        nlri json { "ls-nlri-type": "bgpls-node", "l3-routing-topology": 0, "protocol-id": 3, "node-descriptors": { "autonomous-system": 1, "bgp-ls-identifier": "3232266878", "ospf-area-id": "0.0.0.0", "router-id": "10.4.4.4" }, "nexthop": "None" }
```
