### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by alarig** [Exa-Networks/exabgp#1072]
If I try to use `exabgpcli` it always prints a stacktrace on the logs.

```
edge03-stolon ~ # exabgpcli version

warning: no end of command message received
warning: normal if exabgp.api.ack is set to false otherwise some data may get stuck on the pipe
warning: otherwise it may cause exabgp reactor to block
```

```Python
can't concat str to bytes

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/exabgp/application/control.py", line 248, in run
    self.loop()
  File "/usr/lib/python3.9/site-packages/exabgp/application/control.py", line 225, in loop
    consume(self.r_pipe)
  File "/usr/lib/python3.9/site-packages/exabgp/application/control.py", line 209, in consume
    store[source] += read[source](1024)
TypeError: can't concat str to bytes
```

**Comment by alarig** [comment]
I’m using python 3.9.9 and exabgp 4.2.17

**Comment by thomas-mangin** [comment]
Could please try master

**Comment by thomas-mangin** [comment]
If `<path to your installation>/exabgp --run cli` works it is then a sign that python2 is used when it should not.

**Comment by thomas-mangin** [comment]
I do not have enough information to help.
