### ISSUE TITLE
NodeName object has not attribute "MERGE"

### ISSUE THREAD

**Issue by annaisesc** [Exa-Networks/exabgp#1077]
**Bug Report** 

First of all sorry for assigning this bug, there is an auto assign that I cannot modify...

**Describe the bug**

A traceback error shows that a class "NodeName" has no attribute "MERGE"

**Traceback**
```
 exabgp decode -c exabgp-master/exabgp.conf "FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00AE 02 0000 0097 4001 0100 4002 0040 0504 0000 0064 8009 04C0 A8FC 8B80 0A04 0C04 0101 801D 4004 0000 0100 0402 0012 484C 354D 4D54 312D 3130 372D 4958 522D 5236 0403 0009 4900 0000 00FF 9800 0004 0400 04C0 A8AF 3104 0400 04C0 A8AF 3304 0400 04C0 A8FB E790 0E00 3440 0447 04C0 A8FC 8B00 0001 0027 0100 0000 0000 0000 0401 0000 1A02 0000 0400 00FC 1302 0100 0400 0000 8B02 0300 0619 2168 2512 31"
configuration performing reload of exabgp master
reactor       loaded new configuration successfully
parser        could not parse the message
parser        Traceback (most recent call last):
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/configuration/check.py", line 293, in check_update
parser            update = Update.unpack_message(injected, Direction.IN, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/__init__.py", line 270, in unpack_message
parser            attributes = Attributes.unpack(_attributes, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 290, in unpack
parser            attributes = cls().parse(data, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 385, in parse
parser            return self.parse(left, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 385, in parse
parser            return self.parse(left, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 385, in parse
parser            return self.parse(left, direction, negotiated)
parser          [Previous line repeated 2 more times]
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 371, in parse
parser            decoded = Attribute.unpack(aid, flag, attribute, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attribute.py", line 278, in unpack
parser            instance = cls.klass(attribute_id, flag).unpack(data, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/bgpls/linkstate.py", line 69, in unpack
parser            if klass.MERGE:
parser        AttributeError: 'NodeName' object has no attribute 'MERGE'

```

**Comment by thomas-mangin** [comment]
Shaking my head reviewing this code more ...
```sh
❯ ./sbin/exabgp decode -f 'bgp-ls bgp-ls' "FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00AE 02 0000 0097 4001 0100 4002 0040 0504 0000 0064 8009 04C0 A8FC 8B80 0A04 0C04 0101 801D 4004 0000 0100 0402 0012 484C 354D 4D54 312D 3130 372D 4958 522D 5236 0403 0009 4900 0000 00FF 9800 0004 0400 04C0 A8AF 3104 0400 04C0 A8AF 3304 0400 04C0 A8FB E790 0E00 3440 0447 04C0 A8FC 8B00 0001 0027 0100 0000 0000 0000 0401 0000 1A02 0000 0400 00FC 1302 0100 0400 0000 8B02 0300 0619 2168 2512 31" 2>&1 | tail -1 | cut -b29- | jsonpp

{
  "exabgp": "5.0.0",
  "time": 1651098043.363054,
  "host": "MacBook-Pro-2.local",
  "pid": 34994,
  "ppid": 7015,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "127.0.0.1",
      "peer": "127.0.0.1"
    },
    "asn": {
      "local": 65533,
      "peer": 65533
    },
    "direction": "in",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "local-preference": 100,
          "originator-id": "192.168.252.139",
          "cluster-list": [
            "12.4.1.1"
          ],
          "bgp-ls": {
            "node-flags": {
              "O": 0,
              "T": 0,
              "E": 0,
              "B": 0,
              "R": 0,
              "V": 0,
              "RSV": 0
            },
            "node-name": "HL5MMT1-107-IXR-R6",
            "area-id": "1346612317385085419520",
            "local-te-router-ids": [
              "192.168.175.49",
              "192.168.175.51",
              "192.168.251.231"
            ]
          }
        },
        "announce": {
          "bgp-ls bgp-ls": {
            "192.168.252.139": [
              {
                "ls-nlri-type": "bgpls-node",
                "l3-routing-topology": 4,
                "protocol-id": 1,
                "node-descriptors": {
                  "autonomous-system": 64531,
                  "bgp-ls-identifier": "139",
                  "router-id": "192168251231"
                },
                "nexthop": "192.168.252.139"
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by thomas-mangin** [comment]
Sorry for the number of bugs you are facing with bgp-ls ...

**Comment by annaisesc** [comment]
Thank you very much @thomas-mangin I can confirm this error appears to be solved now in master.

Further I see another error (different packet) decoding a _local node descriptor_ [see line](https://github.com/Exa-Networks/exabgp/blob/master/src/exabgp/bgp/message/update/nlri/bgpls/tlvs/node.py#L83). the IGP protocol_id I get is 5 which in the RFC is specified as _static_. But i think is not supported on exabgp (since the raise in line 83 is raised), this causes the connection of the exbgp with the peers to drop.

shall I open a bug for this or it would be a request for a new feature?

**Comment by annaisesc** [comment]
The message is the following:


```
"FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00D3 02 0000 00BC 4001 010 0 4002 0040 0504 0000 0064 8009 04C0 A8FC 4180 0A04 0C04 0101 801D 3F04 4400 0400 0001 F404 4700 0300 01F4 044A 0021 6578 7072 6573 732D  7372 2D62 6770 2D65 7031 2D31 3932 2E31 3638 2E32 3531 2E34 3004 4B00 0760 0100 0001 74E9 900E 005A 4004 4704 C0A8 FC41 0000 0200 4D05  0000 0000 0000 0003 0100 0018 0200 0004 0000 FC13 0201 0004 0000 0040 0203 0004 C0A8 FC41 0101 0018 0200 0004 0000 FC13 0201 0004 0000 0 040 0203 0004 C0A8 FB28 0102 0008 8000 0013 0000 0000"
configuration performing reload of exabgp master
reactor       loaded new configuration successfully
parser        could not parse the message
parser        Traceback (most recent call last):
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/configuration/check.py", line 296, in check_update
parser            update = Update.unpack_message(injected, Direction.IN, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/__init__.py", line 270, in unpack_message
parser            attributes = Attributes.unpack(_attributes, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 290, in unpack
parser            attributes = cls().parse(data, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 385, in parse
parser            return self.parse(left, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 385, in parse
parser            return self.parse(left, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 385, in parse
parser            return self.parse(left, direction, negotiated)
parser          [Previous line repeated 3 more times]
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 383, in parse
parser            raise exc
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attributes.py", line 371, in parse
parser            decoded = Attribute.unpack(aid, flag, attribute, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/attribute.py", line 278, in unpack
parser            instance = cls.klass(attribute_id, flag).unpack(data, direction, negotiated)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/attribute/mprnlri.py", line 185, in unpack
parser            nlri, left = NLRI.unpack_nlri(afi, safi, data, IN.ANNOUNCED, addpath)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/nlri/nlri.py", line 102, in unpack_nlri
parser            return cls.registered_nlri[key].unpack_nlri(a, s, data, action, addpath)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/nlri/bgpls/nlri.py", line 124, in unpack_nlri
parser            klass = cls.registered_bgpls[code].unpack_nlri(bgp[4 : length + 4], rd)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/nlri/bgpls/link.py", line 116, in unpack_nlri
parser            node, left = NodeDescriptor.unpack(value, proto_id)
parser          File "/usr/local/lib/python3.7/site-packages/exabgp-master-py3.7.egg/exabgp/bgp/message/update/nlri/bgpls/tlvs/node.py", line 83, in unpack
parser            raise Notify(3, 5, 'could not decode Local Node descriptor')
parser        exabgp.bgp.message.notification.Notify: UPDATE message error / Attribute Length Error / could not decode Local Node descriptor

```

**Comment by thomas-mangin** [comment]
Fixed, tidied the code and added IGP of type 5

```sh
❯ ./sbin/exabgp decode -f 'bgp-ls bgp-ls' "FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00D3 02 0000 00BC 4001 010 0 4002 0040 0504 0000 0064 8009 04C0 A8FC 4180 0A04 0C04 0101 801D 3F04 4400 0400 0001 F404 4700 0300 01F4 044A 0021 6578 7072 6573 732D  7372 2D62 6770 2D65 7031 2D31 3932 2E31 3638 2E32 3531 2E34 3004 4B00 0760 0100 0001 74E9 900E 005A 4004 4704 C0A8 FC41 0000 0200 4D05  0000 0000 0000 0003 0100 0018 0200 0004 0000 FC13 0201 0004 0000 0040 0203 0004 C0A8 FC41 0101 0018 0200 0004 0000 FC13 0201 0004 0000 0 040 0203 0004 C0A8 FB28 0102 0008 8000 0013 0000 0000" 2>&1 | tail -1 | cut -b29- | jsonpp
{
  "exabgp": "5.0.0",
  "time": 1651268761.44497,
  "host": "MacBook-Pro-2.local",
  "pid": 68697,
  "ppid": 60659,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "127.0.0.1",
      "peer": "127.0.0.1"
    },
    "asn": {
      "local": 65533,
      "peer": 65533
    },
    "direction": "in",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "local-preference": 100,
          "originator-id": "192.168.252.65",
          "cluster-list": [
            "12.4.1.1"
          ],
          "bgp-ls": {
            "te-metric": 500,
            "igp-metric": 500,
            "link-name": "express-sr-bgp-ep1-192.168.251.40",
            "sr-adj": {
              "flags": {
                "F": 0,
                "B": 1,
                "V": 1,
                "L": 0,
                "S": 0,
                "P": 0,
                "RSV": 0
              },
              "sids": [],
              "weight": 1,
              "undecoded-sids": [
                "0x0174E9"
              ]
            }
          }
        },
        "announce": {
          "bgp-ls bgp-ls": {
            "192.168.252.65": [
              {
                "ls-nlri-type": "bgpls-link",
                "l3-routing-topology": 3,
                "protocol-id": 5,
                "local-node-descriptors": [
                  {
                    "autonomous-system": 64531
                  },
                  {
                    "bgp-ls-identifier": "64"
                  },
                  {
                    "router-id": "192.168.252.65"
                  }
                ],
                "remote-node-descriptors": [
                  {
                    "autonomous-system": 64531
                  },
                  {
                    "bgp-ls-identifier": "64"
                  },
                  {
                    "router-id": "192.168.251.40"
                  }
                ],
                "interface-addresses": [],
                "neighbor-addresses": [],
                "multi-topology-ids": [],
                "link-identifiers": []
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by thomas-mangin** [comment]
waiting for the next issue .... 😉

**Comment by thomas-mangin** [comment]
Please open an new issue if you encounter another problem 👋

**Comment by annaisesc** [comment]
Big thank you @thomas-mangin it is working perfectly now :)
