### ISSUE TITLE
 Invalid bgp-ls bgp-ls next-hop length 16 expected 4

### ISSUE THREAD

**Issue by Aansh2** [Exa-Networks/exabgp#1078]
**Describe the bug**
Not able to parse srv6 enabled router messages-
 
**To Reproduce**

./sbin/exabgp decode -f 'bgp-ls bgp-ls' "0000 01D9 900E 0070 4004 4710 FC00 1000 0001 0000 0000 0000 0000 0001 0000 0200 5702 0000 0000 0000 0000 0100 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0000 0000 0015 0101 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0003 0000 0009 0102 0008 0000 0027 0000 0035 0107 0002 0002 4001 0100 4002 0040 0504 0000 0064 901D 0153 0404 0004 0A00 CA01 0405 0010 FC00 1000 0112 0000 0000 0000 0000 0001 0406 0004 0A00 0201 0407 0010 FC00 1000 0002 0000 0000 0000 0000 0001 0441 0004 4E95 02F9 0447 0003 0000 0A04 5200 1E00 3980 0000 00FC 0010 0001 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 0000 00FC 0010 0001 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8100 00FC 0010 0101 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8100 00FC 0010 0101 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8200 00FC 0010 0301 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8200 00FC 0010 0301 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5A00 0400 0000 0A04 5B00 0800 0000 0A00 0000 0A04 5C00 0400 0000 0004 6200 2004 0400 0010 0000 0000 0000 0004 4400 0400 0000 0A04 5B00 0800 0000 0A00 0000 00"

**Expected behavior**

Should show all parameters in json format 

 ** Error ** 
Error - 
 configuration performing reload of exabgp master-a5e0668182e2dbbd68b5b418036de0efd54bd1d2
reactor       loaded new configuration successfully
parser        could not parse the message
parser        Traceback (most recent call last):
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/configuration/check.py", line 293, in check_update
parser            update = Update.unpack_message(injected, Direction.IN, negotiated)
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/bgp/message/update/__init__.py", line 270, in unpack_message
parser            attributes = Attributes.unpack(_attributes, direction, negotiated)
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/bgp/message/update/attribute/attributes.py", line 290, in unpack
parser            attributes = cls().parse(data, direction, negotiated)
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/bgp/message/update/attribute/attributes.py", line 383, in parse
parser            raise exc
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/bgp/message/update/attribute/attributes.py", line 371, in parse
parser            decoded = Attribute.unpack(aid, flag, attribute, direction, negotiated)
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/bgp/message/update/attribute/attribute.py", line 278, in unpack
parser            instance = cls.klass(attribute_id, flag).unpack(data, direction, negotiated)
parser          File "/Users/niks/exabgp_git/exabgp/src/exabgp/bgp/message/update/attribute/mprnlri.py", line 150, in unpack
parser            raise Notify(
parser        exabgp.bgp.message.notification.Notify: UPDATE message error / Unspecific / invalid bgp-ls bgp-ls next-hop length 16 expected 4

**Comment by thomas-mangin** [comment]
```sh
❯ ./sbin/exabgp decode -f 'bgp-ls bgp-ls' "0000 01D9 900E 0070 4004 4710 FC00 1000 0001 0000 0000 0000 0000 0001 0000 0200 5702 0000 0000 0000 0000 0100 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0000 0000 0015 0101 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0003 0000 0009 0102 0008 0000 0027 0000 0035 0107 0002 0002 4001 0100 4002 0040 0504 0000 0064 901D 0153 0404 0004 0A00 CA01 0405 0010 FC00 1000 0112 0000 0000 0000 0000 0001 0406 0004 0A00 0201 0407 0010 FC00 1000 0002 0000 0000 0000 0000 0001 0441 0004 4E95 02F9 0447 0003 0000 0A04 5200 1E00 3980 0000 00FC 0010 0001 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 0000 00FC 0010 0001 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8100 00FC 0010 0101 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8100 00FC 0010 0101 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8200 00FC 0010 0301 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8200 00FC 0010 0301 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5A00 0400 0000 0A04 5B00 0800 0000 0A00 0000 0A04 5C00 0400 0000 0004 6200 2004 0400 0010 0000 0000 0000 0004 4400 0400 0000 0A04 5B00 0800 0000 0A00 0000 00" 2>&1 | tail -1 | cut -b29- | jsonpp 
{
  "exabgp": "5.0.0",
  "time": 1651092216.832499,
  "host": "MacBook-Pro-2.local",
  "pid": 21697,
  "ppid": 7015,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "127.0.0.1",
      "peer": "127.0.0.1"
    },
    "asn": {
      "local": 65533,
      "peer": 65533
    },
    "direction": "in",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "local-preference": 100,
          "bgp-ls": {
            "local-te-router-ids": [
              "10.0.202.1"
            ],
            "local-te-router-ids": [
              "fc00:1000:112::1"
            ],
            "remote-te-router-id": "10.0.2.1",
            "remote-te-router-id": "fc00:1000:2::1",
            "maximum-link-bandwidth": 1250000000.0,
            "igp-metric": 10,
            "generic-lsid-1106": "0x3E20234620202020205F202030202024325820282020202020202020202020334420203040242120200A",
            "generic-lsid-1106": "0x3E20234420202020205F2020302020243258202C2020202020202020202020334420203040242120200A",
            "generic-lsid-1106": "0x3E20234620403020205F202030203024325820282020202020202020202020334420203040242120200A",
            "generic-lsid-1106": "0x3E20234420403020205F2020302030243258202C2020202020202020202020334420203040242120200A",
            "generic-lsid-1106": "0x3E20234620404020205F202030205024325820282020202020202020202020334420203040242120200A",
            "generic-lsid-1106": "0x3E20234420404020205F2020302050243258202C2020202020202020202020334420203040242120200A",
            "generic-lsid-1114": "0x2420202020224020200A",
            "generic-lsid-1115": "0x282020202022402020202048200A",
            "generic-lsid-1116": "0x2420202020202020200A",
            "generic-lsid-1122": "0x4021203020202120202020202020202020212430202120202020204824365020282020202022402020202020200A"
          }
        },
        "announce": {
          "bgp-ls bgp-ls": {
            "fc00:1000:1::1": [
              {
                "ls-nlri-type": "bgpls-link",
                "l3-routing-topology": 0,
                "protocol-id": 2,
                "local-node-descriptors": {
                  "autonomous-system": 138384,
                  "bgp-ls-identifier": "0",
                  "router-id": "000000000015"
                },
                "remote-node-descriptors": {
                  "autonomous-system": 138384,
                  "bgp-ls-identifier": "0",
                  "router-id": "000300000009"
                },
                "interface-address": {},
                "neighbor-address": {},
                "multi-topology-id": [
                  {
                    "bits": "0000",
                    "multi-topology-id": 2
                  }
                ]
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by thomas-mangin** [comment]
Changes to the generic LSID, we can only have one key for JSON:
```sh
❯ ./sbin/exabgp decode -f 'bgp-ls bgp-ls' "0000 01D9 900E 0070 4004 4710 FC00 1000 0001 0000 0000 0000 0000 0001 0000 0200 5702 0000 0000 0000 0000 0100 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0000 0000 0015 0101 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0003 0000 0009 0102 0008 0000 0027 0000 0035 0107 0002 0002 4001 0100 4002 0040 0504 0000 0064 901D 0153 0404 0004 0A00 CA01 0405 0010 FC00 1000 0112 0000 0000 0000 0000 0001 0406 0004 0A00 0201 0407 0010 FC00 1000 0002 0000 0000 0000 0000 0001 0441 0004 4E95 02F9 0447 0003 0000 0A04 5200 1E00 3980 0000 00FC 0010 0001 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 0000 00FC 0010 0001 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8100 00FC 0010 0101 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8100 00FC 0010 0101 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8200 00FC 0010 0301 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8200 00FC 0010 0301 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5A00 0400 0000 0A04 5B00 0800 0000 0A00 0000 0A04 5C00 0400 0000 0004 6200 2004 0400 0010 0000 0000 0000 0004 4400 0400 0000 0A04 5B00 0800 0000 0A00 0000 00" 2>&1 | tail -1 | cut -b29- | jsonpp
{
  "exabgp": "5.0.0",
  "time": 1651096841.619282,
  "host": "MacBook-Pro-2.local",
  "pid": 32360,
  "ppid": 7015,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "127.0.0.1",
      "peer": "127.0.0.1"
    },
    "asn": {
      "local": 65533,
      "peer": 65533
    },
    "direction": "in",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "local-preference": 100,
          "bgp-ls": {
            "local-te-router-ids": [
              "10.0.202.1"
            ],
            "local-te-router-ids": [
              "fc00:1000:112::1"
            ],
            "remote-te-router-id": "10.0.2.1",
            "remote-te-router-id": "fc00:1000:2::1",
            "maximum-link-bandwidth": 1250000000.0,
            "igp-metric": 10,
            "generic-lsid-1106": [
              "0x3E20234620202020205F202030202024325820282020202020202020202020334420203040242120200A",
              "0x3E20234420202020205F2020302020243258202C2020202020202020202020334420203040242120200A",
              "0x3E20234620403020205F202030203024325820282020202020202020202020334420203040242120200A",
              "0x3E20234420403020205F2020302030243258202C2020202020202020202020334420203040242120200A",
              "0x3E20234620404020205F202030205024325820282020202020202020202020334420203040242120200A",
              "0x3E20234420404020205F2020302050243258202C2020202020202020202020334420203040242120200A"
            ],
            "generic-lsid-1114": [
              "0x2420202020224020200A"
            ],
            "generic-lsid-1115": [
              "0x282020202022402020202048200A"
            ],
            "generic-lsid-1116": [
              "0x2420202020202020200A"
            ],
            "generic-lsid-1122": [
              "0x4021203020202120202020202020202020212430202120202020204824365020282020202022402020202020200A"
            ]
          }
        },
        "announce": {
          "bgp-ls bgp-ls": {
            "fc00:1000:1::1": [
              {
                "ls-nlri-type": "bgpls-link",
                "l3-routing-topology": 0,
                "protocol-id": 2,
                "local-node-descriptors": {
                  "autonomous-system": 138384,
                  "bgp-ls-identifier": "0",
                  "router-id": "000000000015"
                },
                "remote-node-descriptors": {
                  "autonomous-system": 138384,
                  "bgp-ls-identifier": "0",
                  "router-id": "000300000009"
                },
                "interface-address": {},
                "neighbor-address": {},
                "multi-topology-id": [
                  {
                    "bits": "0000",
                    "multi-topology-id": 2
                  }
                ]
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by thomas-mangin** [comment]
The decoding looks suspicious to me (if wrong this is a long standing bug).

**Comment by thomas-mangin** [comment]
without uuencoding (removed with the latest patch), it now look it has half a chance of being right ...
```sh
❯ ./sbin/exabgp decode -f 'bgp-ls bgp-ls' "0000 01D9 900E 0070 4004 4710 FC00 1000 0001 0000 0000 0000 0000 0001 0000 0200 5702 0000 0000 0000 0000 0100 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0000 0000 0015 0101 001A 0200 0004 0002 1C90 0201 0004 0000 0000 0203 0006 0003 0000 0009 0102 0008 0000 0027 0000 0035 0107 0002 0002 4001 0100 4002 0040 0504 0000 0064 901D 0153 0404 0004 0A00 CA01 0405 0010 FC00 1000 0112 0000 0000 0000 0000 0001 0406 0004 0A00 0201 0407 0010 FC00 1000 0002 0000 0000 0000 0000 0001 0441 0004 4E95 02F9 0447 0003 0000 0A04 5200 1E00 3980 0000 00FC 0010 0001 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 0000 00FC 0010 0001 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8100 00FC 0010 0101 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8100 00FC 0010 0101 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3980 8200 00FC 0010 0301 12E0 0200 0000 0000 0000 0004 E400 0420 1010 0004 5200 1E00 3900 8200 00FC 0010 0301 12E0 0300 0000 0000 0000 0004 E400 0420 1010 0004 5A00 0400 0000 0A04 5B00 0800 0000 0A00 0000 0A04 5C00 0400 0000 0004 6200 2004 0400 0010 0000 0000 0000 0004 4400 0400 0000 0A04 5B00 0800 0000 0A00 0000 00" 2>&1 | tail -1 | cut -b28- | jsonpp
{
  "exabgp": "5.0.0",
  "time": 1651100776.632144,
  "host": "MacBook-Pro-2.local",
  "pid": 39807,
  "ppid": 7015,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "127.0.0.1",
      "peer": "127.0.0.1"
    },
    "asn": {
      "local": 65533,
      "peer": 65533
    },
    "direction": "in",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "local-preference": 100,
          "bgp-ls": {
            "local-te-router-ids": [
              "10.0.202.1"
            ],
            "local-te-router-ids": [
              "fc00:1000:112::1"
            ],
            "remote-te-router-id": "10.0.2.1",
            "remote-te-router-id": "fc00:1000:2::1",
            "maximum-link-bandwidth": 1250000000.0,
            "igp-metric": 10,
            "generic-lsid-1106": [
              "0x003980000000FC0010000112E002000000000000000004E4000420101000",
              "0x003900000000FC0010000112E003000000000000000004E4000420101000",
              "0x003980810000FC0010010112E002000000000000000004E4000420101000",
              "0x003900810000FC0010010112E003000000000000000004E4000420101000",
              "0x003980820000FC0010030112E002000000000000000004E4000420101000",
              "0x003900820000FC0010030112E003000000000000000004E4000420101000"
            ],
            "generic-lsid-1114": [
              "0x0000000A"
            ],
            "generic-lsid-1115": [
              "0x0000000A0000000A"
            ],
            "generic-lsid-1116": [
              "0x00000000"
            ],
            "generic-lsid-1122": [
              "0x040400001000000000000000044400040000000A045B00080000000A00000000"
            ]
          }
        },
        "announce": {
          "bgp-ls bgp-ls": {
            "fc00:1000:1::1": [
              {
                "ls-nlri-type": "bgpls-link",
                "l3-routing-topology": 0,
                "protocol-id": 2,
                "local-node-descriptors": {
                  "autonomous-system": 138384,
                  "bgp-ls-identifier": "0",
                  "router-id": "000000000015"
                },
                "remote-node-descriptors": {
                  "autonomous-system": 138384,
                  "bgp-ls-identifier": "0",
                  "router-id": "000300000009"
                },
                "interface-address": {},
                "neighbor-address": {},
                "multi-topology-id": [
                  {
                    "bits": "0000",
                    "multi-topology-id": 2
                  }
                ]
              }
            ]
          }
        }
      }
    }
  }
}
```
