### ISSUE TITLE
readlink syntax change between OS

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#231]
Issue noticed on OS X, may be also an issue on *BSD

```
./sbin/exabgp
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "app_main.py", line 581, in run_it
  File "<string>", line 7, in <module>
IndexError: list index out of range
/Users/thomas/bin/pypy: can't find '__main__' module in ''
```

**Comment by thomas-mangin** [comment]
@vincentbernat 
https://www.youtube.com/watch?v=tUncwY4SBOA

**Comment by vincentbernat** [comment]
Let me fix that! ;-)
