### ISSUE TITLE
JSON serialisation failure

### ISSUE THREAD

**Issue by pavel-odintsov** [Exa-Networks/exabgp#260]
Hello!

I can't reproduce it but I should report it.

``` bash
Thu, 14 May 2015 22:40:35 | INFO     | 3818   | network       | Connected to peer neighbor 10.0.3.114 local-ip 10.0.3.115 local-as 1234 peer-as 65001 router-id 10.0.3.115 family-allowed in-open (in)

********************************************************************************
EXABGP MISBEHAVED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP, as the problem only affects one
peer, we are trying to keep the program running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 3.4.10
Python version : 2.7.9 (default, Mar  1 2015, 12:57:24)  [GCC 4.9.2]
System Uname   : #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24)
System MaxInt  : 9223372036854775807


peer 10.0.3.114 ASN 65001   

<type 'exceptions.IndexError'>
list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 584, in _run
    for action in self._main(direction):
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 453, in _main
    for message in proto.read_message():
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/protocol.py", line 171, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 270, in closure
    return function(self,*args)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 320, in message
    self._dispatch[message_id](self,peer,message,header,*body)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 328, in wrap
    function(*args)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 347, in _update
    self.write(process,self._encoder[process].update(peer,update,header,body),peer)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/encoding.py", line 346, in update
    'message': '{ %s}' % self._update(update)})),header,body,peer.neighbor.identificator(),self.count(peer),message_type='update')
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/encoding.py", line 331, in _update
    return update.nlris[0].json()
IndexError: list index out of range

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
```

**Comment by thomas-mangin** [comment]
Do you still have the whole log ? I guess this issue came when you tried to print a flow route.

**Comment by thomas-mangin** [comment]
The previous patch will cause a much clearer error message should/when the issue occurs again.
I am closing the issue as I can not fix it without more information.

**Comment by pavel-odintsov** [comment]
Will check shortly. Thanks!

**Comment by pavel-odintsov** [comment]
Whole log here: https://gist.github.com/pavel-odintsov/223b0a3fa8e344a1c1cd

**Comment by thomas-mangin** [comment]
@pavel-odintsov Thank you, very much for helping me here. 
To debug this issue, I need to know the content of the BGP update which triggers the issue. If you are able to reproduce the issue when exabgp is running with -d then I would be able to help more.

**Comment by thomas-mangin** [comment]
I assume this was fixed and long time ago and I just never updated the ticket ...
