### ISSUE TITLE
Error on as4-path attribute

### ISSUE THREAD

**Issue by atwardowski** [Exa-Networks/exabgp#359]
I'm trying to setup exabgp for the first time and I'm constantly getting errors.  It seems to be erroring on trying to parse the as4-path attribute in the updates from my router.

```
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       | Peer     1.2.3.4 ASN 60123   << UPDATE
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute origin             flag 0x40 type 0x01 len 0x01 payload 02
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute as-path            flag 0x40 type 0x02 len 0x08 payload 0203 0B62 0513 5BA0
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute as4-path           flag 0xc0 type 0x11 len 0x0e payload 0203 0000 0B62 0000 0513 0003 0836
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | unknown transitive attribute (flag 0xC0, aid 0x11)
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute next-hop           flag 0x40 type 0x03 len 0x04 payload 80F1 02F9
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute med                flag 0x80 type 0x04 len 0x04 payload 0000 0005
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 004B
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute atomic-aggregate   flag 0x40 type 0x06 len 0x00
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute aggregator         flag 0xc0 type 0x07 len 0x06 payload 5BA0 B952 56C4
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute as4-aggregator     flag 0xc0 type 0x12 len 0x08 payload 0003 0836 B952 56C4
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | parser        | parsing attribute community          flag 0xc0 type 0x08 len 0x04 payload 4FF9 2C43
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       | Peer     1.2.3.4 ASN 60123   Could not decode message "2"
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       | Peer     1.2.3.4 ASN 60123   'GenericAttribute' object has no attribute 'as_seq'
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       | Traceback (most recent call last):
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |   File "/home/admin/lg/exabgp/lib/exabgp/reactor/protocol.py", line 197, in read_message
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |     message = Message.unpack(msg_id,body,self.negotiated)
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |   File "/home/admin/lg/exabgp/lib/exabgp/bgp/message/message.py", line 181, in unpack
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |     return cls.klass(message).unpack_message(data,negotiated)
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |   File "/home/admin/lg/exabgp/lib/exabgp/bgp/message/update/__init__.py", line 263, in unpack_message
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |     attributes = Attributes.unpack(_attributes,negotiated)
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |   File "/home/admin/lg/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 269, in unpack
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |     attributes.merge_attributes()
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |   File "/home/admin/lg/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 362, in merge_attributes
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |     len4 = len(as4path.as_seq)
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       | AttributeError: 'GenericAttribute' object has no attribute 'as_seq'
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       |
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | message       | Peer     1.2.3.4 ASN 60123   >> NOTIFICATION (1,0,"can not decode update message of type "2"")
Thu, 17 Dec 2015 13:00:27 | INFO     | 94074  | network       | Peer     1.2.3.4 ASN 60123   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
```

**Comment by atwardowski** [comment]
It looks like the issue is a missing @Attribute.register() on AS6Path in lib/exabgp/bgp/message/update/attribute/aspath.py

**Comment by thomas-mangin** [comment]
Thank you for this report and the investigation. Which version are you running please ?

**Comment by atwardowski** [comment]
I tested both HEAD of the master branch and the 3.4 branch and was getting the same error on both. After investigating the code and looking through previous commits I found 61c467198d115b13a604270e0b21b9f10df99d7a which moved Attribute.register_attribute(AS4Path) out of __init__.py but missed adding the decorator to the class.

**Comment by thomas-mangin** [comment]
/me bad ... Thank you for finding the root cause.

**Comment by thomas-mangin** [comment]
fixed with #360

**Comment by atwardowski** [comment]
This bug is not present on the 3.4 branch.

Also, it looks like #360 was closed without being merged.

**Comment by thomas-mangin** [comment]
Merged (unittest failing due to the 'on fly' next-hop self change going on) so closing as this self contained work is correct.
