### ISSUE TITLE
NOTIFICATION receive bug

### ISSUE THREAD

**Issue by droon5** [Exa-Networks/exabgp#399]
Hello,

when receiving  NOTIFICATION (6,3,"Peer De-configured") and using encoder JSON, the JSON looks like this:
(receive - parsed, packets, consolidate) There are some wrong characters in "subcode".
```
{ "exabgp": "3.4.8", "time": 1459413655, "host" : "tiger", "pid" : "23247", "ppid" : "23235", "counter": 15, "type": "notification", "notification": { "subcode": "˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙ '", "code": "Cease / Peer De-configured / Peer De-configured", "data": "0603506565722044652D636F6E66696775726564" } }
```

(receive - parsed only) Not sure, if its right, there are blank "subcode" and "data".
```
{ "exabgp": "3.4.8", "time": 1459414298, "host" : "tiger", "pid" : "23302", "ppid" : "23235", "counter": 16, "type": "notification", "notification": { "subcode": "", "code": "Cease / Peer De-configured / Peer De-configured", "data": "" } }
```
(receive - packets only) Seems ok.
```
{ "exabgp": "3.4.8", "time": 1459414429, "host" : "tiger", "pid" : "23319", "ppid" : "23235", "counter": 19, "type": "state", "neighbor": { "ip": "192.168.51.94", "address": { "local": "192.168.51.96", "peer": "192.168.51.94"}, "asn": { "local": "65000", "peer": "65000"}, "state": "down", "reason": "in loop, peer reset, message [notification received (6,3)] error[Cease / Peer De-configured / Peer De-configured]"} }
```

Also, if I use text encoder, exaBGP crashes:
```
ExaBGP version : 3.4.16
Python version : 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
System Uname   : #1 SMP Thu Jul 23 15:44:03 UTC 2015
System MaxInt  : 9223372036854775807


peer 192.168.51.94 ASN 65000

<type 'exceptions.TypeError'>
%d format: a number is required, not Notification
Traceback (most recent call last):
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/peer.py", line 587, in _run
    for action in self._main(direction):
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/peer.py", line 456, in _main
    for message in proto.read_message():
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/protocol.py", line 175, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/api/processes.py", line 270, in closure
    return function(self,*args)
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/api/processes.py", line 306, in message
    self._dispatch[message_id](self,peer,message,header,*body)
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/api/processes.py", line 314, in wrap
    function(*args)
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/api/processes.py", line 348, in _notification
    self.write(process,self._encoder[process].notification(peer,message,header,body),peer)
  File "/root/ondra/exabgp-3.4/lib/exabgp/reactor/api/encoding.py", line 88, in notification
    return 'notification code %d subcode %d data %s\n' % (code,subcode,hexstring(data))
TypeError: %d format: a number is required, not Notification
```

Thanks

**Comment by thomas-mangin** [comment]
Sorry - going to fix this ASAP.

**Comment by thomas-mangin** [comment]
@droon5 can you please let me know if the patch above fixed the issue (did not test it I expect it to do what is required).

**Comment by thomas-mangin** [comment]
s/quite/quick/ ...

**Comment by droon5** [comment]
Yes, it is working now, thank you.
