### ISSUE TITLE
'exceptions.KeyError' recv_capa[Capability.CODE.FOUR_BYTES_ASN]

### ISSUE THREAD

**Issue by toddjcrane** [Exa-Networks/exabgp#412]
Verbose output will be sent via email due to sensitive contents

<type 'exceptions.KeyError'>
65 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 584, in _run
    for action in self._[direction]['code']():
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 386, in _connect
    proto.negotiated.received(message)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/open/capability/negotiated.py", line 47, in received
    self._negotiate()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/open/capability/negotiated.py", line 62, in _negotiate
    self.peer_as = recv_capa[Capability.CODE.FOUR_BYTES_ASN]
KeyError: 65

**Comment by thomas-mangin** [comment]
What version of ExaBGP is it please ? Looks like a bug I fixed a long time ago.

**Comment by toddjcrane** [comment]
~# exabgp -v
ExaBGP : 3.4.16
Python : 2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]
Uname  : #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016

**Comment by thomas-mangin** [comment]
Thanks for the bug report. It looks like you are using AS_TRANS to establish a non ASN4 supported session. This should fix the problem.
https://github.com/Exa-Networks/exabgp/commit/7f047c13ee2c86d66dea79ce081ccd1b973ef369

**Comment by thomas-mangin** [comment]
No news, good news, closing.
