### ISSUE TITLE
4.0.0 issues with IPv6 neighbours

### ISSUE THREAD

**Issue by chrisk-de** [Exa-Networks/exabgp#419]
Hey,

I just switched from 3.4 to 4.0 for some tests and after I got my config migrated I discovered some issues with IPv6 neighbours:
```
********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 4.0.0
Python version : 2.7.5 (default, Nov 20 2015, 02:00:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
System Uname   : #1 SMP Tue Feb 16 17:03:50 UTC 2016
System MaxInt  : 9223372036854775807


peer <removed> ASN 12306

<type 'exceptions.SystemError'>
/builddir/build/BUILD/Python-2.7.5/Objects/stringobject.c:4044: bad argument to internal function
Traceback (most recent call last):
  File "/home/ckildau/exabgp/lib/exabgp/reactor/peer.py", line 615, in _run

  File "/home/ckildau/exabgp/lib/exabgp/reactor/peer.py", line 495, in _main

  File "/home/ckildau/exabgp/lib/exabgp/logger.py", line 405, in routes

  File "/home/ckildau/exabgp/lib/exabgp/logger.py", line 301, in info

  File "/home/ckildau/exabgp/lib/exabgp/logger.py", line 290, in report

  File "/home/ckildau/exabgp/lib/exabgp/logger.py", line 66, in split
    return '%s (%4d) %s' % (self.prefix,len(formated),formated)
  File "/home/ckildau/exabgp/lib/exabgp/logger.py", line 69, in __str__
    class LazyAttribute (object):
  File "/home/ckildau/exabgp/lib/exabgp/bgp/message/update/eor.py", line 41, in __repr__
    return self.extensive()
  File "/home/ckildau/exabgp/lib/exabgp/bgp/message/update/eor.py", line 44, in extensive
    return 'eor %d/%d (%s %s)' % (self.afi,self.safi,self.afi,self.safi)
SystemError: /builddir/build/BUILD/Python-2.7.5/Objects/stringobject.c:4044: bad argument to internal function

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
```

**Comment by chrisk-de** [comment]
UPDATE: sorry, it's not limited to IPv6 neighbors. IPv4 is also affected.

**Comment by thomas-mangin** [comment]
Could you please check if this change fixes the issue ?

**Comment by chrisk-de** [comment]
Nope, still the exact same issue in latest master branch.
Can I help you with any more details in private?

**Comment by thomas-mangin** [comment]
If you run exabgp with -p it will drop you into the debugger. I would like to known what "%s" % self.afi does
and if using str(self.afi) makes a difference

**Comment by thomas-mangin** [comment]
fixed by:
https://github.com/Exa-Networks/exabgp/commit/77b8e0f807d375b787bcb678027f405e0b808984
https://github.com/Exa-Networks/exabgp/commit/49fd86282657cfb65c3d4d382cd732a3fd0923b2

**Comment by chrisk-de** [comment]
I can confirm that this is now fixed in master branch. Thanks!
