### ISSUE TITLE
Extended-Communities in latest -master force crash

### ISSUE THREAD

**Issue by chrisk-de** [Exa-Networks/exabgp#420]
latest -master seems to have issues with extended communities:
```
ExaBGP version : 4.0.0
Python version : 2.7.5 (default, Nov 20 2015, 02:00:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
System Uname   : #1 SMP Tue Feb 16 17:03:50 UTC 2016
System MaxInt  : 9223372036854775807


-- Traceback


Traceback (most recent call last):
  File "/home/ckildau/exabgp/lib/exabgp/application/bgp.py", line 328, in <module>
    main()
  File "/home/ckildau/exabgp/lib/exabgp/application/bgp.py", line 246, in main
    run(env,comment,configurations)
  File "/home/ckildau/exabgp/lib/exabgp/application/bgp.py", line 280, in run
    ok = Reactor(configurations).run()
  File "/home/ckildau/exabgp/lib/exabgp/reactor/loop.py", line 223, in run
    if not self.schedule() and not keys:
  File "/home/ckildau/exabgp/lib/exabgp/reactor/loop.py", line 379, in schedule
    self._running.next()  # run
  File "/home/ckildau/exabgp/lib/exabgp/reactor/api/command/text.py", line 218, in callback
    changes = self.parser.api_route(command,peers)
  File "/home/ckildau/exabgp/lib/exabgp/reactor/api/parser/text.py", line 78, in api_route
    if not self.configuration.partial('static',line):
  File "/home/ckildau/exabgp/lib/exabgp/configuration/configuration.py", line 383, in partial
    if self.section(section) is not True:
  File "/home/ckildau/exabgp/lib/exabgp/configuration/configuration.py", line 460, in section
    and self.dispatch(name) \
  File "/home/ckildau/exabgp/lib/exabgp/configuration/configuration.py", line 432, in dispatch
    if self._run(name):
  File "/home/ckildau/exabgp/lib/exabgp/configuration/configuration.py", line 423, in _run
    if not self.run(name,command):
  File "/home/ckildau/exabgp/lib/exabgp/configuration/configuration.py", line 467, in run
    return self._structure[name]['class'].parse(name,command)
  File "/home/ckildau/exabgp/lib/exabgp/configuration/core/section.py", line 64, in parse
    insert = self.known[command](self.tokeniser.iterate)
  File "/home/ckildau/exabgp/lib/exabgp/configuration/static/__init__.py", line 75, in route
    action = ParseStatic.action[command]
KeyError: '12306:9200'


-- Configuration





-- Logging History
Tue, 31 May 2016 07:52:18 16468  debug         peer <removed> ASN 12306   Receive Timer 160 second(s) left
Tue, 31 May 2016 07:52:18 16468  debug         peer <removed> ASN 12306   Send Timer 28 second(s) left
Tue, 31 May 2016 07:52:18 16468  debug         peer <removed> ASN 12306   Receive Timer 158 second(s) left
Tue, 31 May 2016 07:52:18 16468  debug         peer <removed> ASN 12306   Send Timer 28 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Receive Timer 159 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Send Timer 27 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Receive Timer 153 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Send Timer 27 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Receive Timer 159 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Send Timer 27 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Receive Timer 160 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Send Timer 27 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Receive Timer 159 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Send Timer 27 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Receive Timer 157 second(s) left
Tue, 31 May 2016 07:52:19 16468  debug         peer <removed> ASN 12306   Send Timer 27 second(s) left
Tue, 31 May 2016 07:52:19 16468  processes     Command from process announce-routes : announce route <removed>/24 extended-community 12306:6999 12306:9200 12306:6900
Tue, 31 May 2016 07:52:19 16468  reactor       callback | handling 'announce route <removed>/24 extended-community 12306:6999 12306:9200 12306:6900' with announce_route
Tue, 31 May 2016 07:52:19 16468  reactor       callback | installing announce_route
Tue, 31 May 2016 07:52:19 16468  reactor       callback | running
Tue, 31 May 2016 07:52:19 16468  configuration . route            | '<removed>/24' 'extended-community' '12306:6999' '12306:9200' '12306:6900'
```
Just let me know if you need any more details.
Thanks!

**Comment by thomas-mangin** [comment]
could you please try extended-community [ 12306:6999 12306:9200 12306:6900 ]

**Comment by chrisk-de** [comment]
I have tried putting extended communities in [ ], which leads to:
RP/0/RSP0/CPU0:Jun  1 14:34:48.817 CEST: bgp[1050]: %ROUTING-BGP-3-MALFORM_UPDATE : Malformed UPDATE message received from neighbor <removed> (VRF: default) - message length 68 bytes, error flags 0x00000800, action taken "TreatAsWdr". Error details: "Error 0x00000800, Field "Attr-missing", Attribute 3 (Flags 0x00, Length 0), Data []". NLRIs: [IPv4 Unicast] <removed>/24

**Comment by thomas-mangin** [comment]
Hello, this is a different issue on which the message seems to be invalid - whicth is very surprising. I would need you to please:
- create a new issue for this
- include the output of exabgp when running the -d option ( the whole output, I need to see the OPEN negotiation and raw data sent on the wire to debug this )
- as much debug information from your router to try to understand why it does consider the update invalid.

Sorry for this issue.

**Comment by thomas-mangin** [comment]
Attribute 3 is next-hop and it seems it was not included in the update message - need to understand how and why.
