### ISSUE TITLE
EXABGP CRASHED

### ISSUE THREAD

**Issue by pbatkov** [Exa-Networks/exabgp#425]
Hello, Thomas!
I need ur help.. 

```
ExaBGP : 3.4.13
Python : 2.7.5 (default, Nov 20 2015, 02:00:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
Uname  : #1 SMP Mon Jan 25 22:07:14 UTC 2016
```
Traceback:

```
May 24 17:44:39 carp00 exabgp: Traceback (most recent call last):
May 24 17:44:39 carp00 exabgp: File "/usr/sbin/exabgp", line 9, in <module>
May 24 17:44:39 carp00 exabgp: load_entry_point('exabgp==3.4.13', 'console_scripts', 'exabgp')()
May 24 17:44:39 carp00 exabgp: File "/usr/lib/python2.7/site-packages/exabgp/application/__init__.py", line 12, in run_exabgp
May 24 17:44:39 carp00 exabgp: main()
May 24 17:44:39 carp00 exabgp: File "/usr/lib/python2.7/site-packages/exabgp/application/bgp.py", line 221, in main
May 24 17:44:39 carp00 exabgp: run(env,comment,configurations)
May 24 17:44:39 carp00 exabgp: File "/usr/lib/python2.7/site-packages/exabgp/application/bgp.py", line 260, in run
May 24 17:44:39 carp00 exabgp: ok = Reactor(configurations).run()
May 24 17:44:39 carp00 exabgp: File "/usr/lib/python2.7/site-packages/exabgp/reactor/loop.py", line 232, in run
May 24 17:44:39 carp00 exabgp: for connection in self.listener.connected():
May 24 17:44:39 carp00 exabgp: File "/usr/lib/python2.7/site-packages/exabgp/reactor/listener.py", line 107, in connected
May 24 17:44:39 carp00 exabgp: raise exc
May 24 17:44:39 carp00 exabgp: AcceptError: could not accept a new connection ([Errno ENOTCONN] [Errno 107] Transport endpoint is not connected)
May 24 17:44:39 carp00 exabgp: ********************************************************************************
May 24 17:44:39 carp00 exabgp: EXABGP CRASHED / HELP US FIX IT
May 24 17:44:39 carp00 exabgp: ********************************************************************************
May 24 17:44:39 carp00 exabgp: Sorry, you encountered a problem with ExaBGP and we could not keep the program
May 24 17:44:39 carp00 exabgp: running.
May 24 17:44:39 carp00 exabgp: There are a few things you can do to help us (and yourself):
May 24 17:44:39 carp00 exabgp: - make sure you are running the latest version of the code available at
May 24 17:44:39 carp00 exabgp: https://github.com/Exa-Networks/exabgp/releases/latest
May 24 17:44:39 carp00 exabgp: - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
May 24 17:44:39 carp00 exabgp: so it can be fixed (github can be searched for similar reports)
May 24 17:44:39 carp00 exabgp: PLEASE, when reporting, do include as much information as you can:
May 24 17:44:39 carp00 exabgp: - do not obfuscate any data (feel free to send us a private  email with the
May 24 17:44:39 carp00 exabgp: extra information if your business policy is strict on information sharing)
May 24 17:44:39 carp00 exabgp: https://github.com/Exa-Networks/exabgp/wiki/FAQ
May 24 17:44:39 carp00 exabgp: - if you can reproduce the issue, run ExaBGP with the command line option -d
May 24 17:44:39 carp00 exabgp: it provides us with much needed information to fix problems quickly
May 24 17:44:39 carp00 exabgp: - include the information presented below
May 24 17:44:39 carp00 exabgp: Should you not receive an acknowledgment of your issue on github (assignement,
May 24 17:44:39 carp00 exabgp: comment, or similar) within a few hours, feel free to email us to make sure
May 24 17:44:39 carp00 exabgp: it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
May 24 17:44:39 carp00 exabgp: ********************************************************************************
May 24 17:44:39 carp00 exabgp: -- Please provide ALL the information below on :
May 24 17:44:39 carp00 exabgp: -- https://github.com/Exa-Networks/exabgp/issues
May 24 17:44:39 carp00 exabgp: ********************************************************************************
May 24 17:44:39 carp00 exabgp: ExaBGP version : 3.4.13
May 24 17:44:39 carp00 exabgp: Python version : 2.7.5 (default, Nov 20 2015, 02:00:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
May 24 17:44:39 carp00 exabgp: System Uname   : #1 SMP Mon Jan 25 22:07:14 UTC 2016
May 24 17:44:39 carp00 exabgp: System MaxInt  : 9223372036854775807

May 24 17:44:39 carp00 exabgp: -- Logging History
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Receive Timer 29 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Send Timer 0 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         session 1 outgoing 10.200.0.5 / 10.200.0.2      SENDING  (47) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
May 24 17:44:39 carp00 exabgp: exabgp: 20387  info          Peer    10.200.0.2 ASN 48287   >> KEEPALIVE
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Receive Timer 28 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Send Timer 7 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Receive Timer 28 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Send Timer 9 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Receive Timer 27 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Send Timer 6 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Receive Timer 27 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Send Timer 8 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Receive Timer 26 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Send Timer 5 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Receive Timer 26 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Send Timer 7 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Receive Timer 25 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.1 ASN 48287   Send Timer 4 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Receive Timer 25 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  debug         peer 10.200.0.2 ASN 48287   Send Timer 6 second(s) left
May 24 17:44:39 carp00 exabgp: exabgp: 20387  network       could not accept a new connection ([Errno ENOTCONN] [Errno 107] Transport endpoint is not connected)
May 24 17:44:39 carp00 exabgp: ********************************************************************************
May 24 17:44:39 carp00 exabgp: -- Please provide _ALL_ the information above on :
May 24 17:44:39 carp00 exabgp: -- https://github.com/Exa-Networks/exabgp/issues
May 24 17:44:39 carp00 exabgp: ********************************************************************************
May 24 17:44:39 carp00 systemd: exabgp.service: main process exited, code=exited, status=1/FAILURE
May 24 17:44:39 carp00 systemd: Unit exabgp.service entered failed state.
May 24 17:44:39 carp00 systemd: exabgp.service failed.
```

Thanks for your attention!

**Comment by thomas-mangin** [comment]
The code will now ignore the issue - as it should - the fault was some left over debugging code.
