### ISSUE TITLE
Error processing empty UPDATEs

### ISSUE THREAD

**Issue by pierky** [Exa-Networks/exabgp#503]
This is the problem I'm having:

```
Thu, 29 Sep 2016 11:57:47 5      network       Connected to peer neighbor 192.0.2.4 local-ip 192.0.2.2 local-as 65536 peer-as 65538 router-id 192.0.2.2 family-allowed in-open (out)
Thu, 29 Sep 2016 11:57:47 5      routes        peer 192.0.2.4 ASN 65538   << UPDATE (1) (   0)

ExaBGP version : 4.0.0
Python version : 2.7.12 (default, Aug 26 2016, 20:43:47)  [GCC 4.9.2]
System Uname   : #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
System MaxInt  : 9223372036854775807


peer 192.0.2.4 ASN 65538

<type 'exceptions.TypeError'>
object of type 'NLRI' has no len()
Traceback (most recent call last):
  File "/root/exabgp-master/lib/exabgp/reactor/peer.py", line 637, in _run
    for action in self._main(direction):
  File "/root/exabgp-master/lib/exabgp/reactor/peer.py", line 517, in _main
    self.logger.routes(LazyFormat(self.me('<< UPDATE (%d) nlri ' % number),nlri,str))
  File "/root/exabgp-master/lib/exabgp/logger.py", line 408, in routes
    getattr(self,recorder)(message,'routes',level)
  File "/root/exabgp-master/lib/exabgp/logger.py", line 304, in info
    self.report(message,source,level)
  File "/root/exabgp-master/lib/exabgp/logger.py", line 293, in report
    for line in message.split('\n'):
  File "/root/exabgp-master/lib/exabgp/logger.py", line 67, in split
    return str(self).split(char)
  File "/root/exabgp-master/lib/exabgp/logger.py", line 71, in __str__
    return '%s (%4d) %s' % (self.prefix,len(self.message),formated)
TypeError: object of type 'NLRI' has no len()
```

I'm trying to bring up a session with a BIRD instance: ExaBGP config follows:

```
neighbor 192.0.2.4 {
        router-id 192.0.2.2;
        local-address 192.0.2.2;
        local-as 65536;
        peer-as 65538;

        static {
                route 203.0.113.1/32 {
                        next-hop 192.0.2.2;
                        large-community [ 65536:1:2 ];
                }
        }
}
```

BIRD config follows:

```
router id 192.0.2.4;
log "/etc/bird/log.log" all;
debug protocols all;

protocol bgp ExaBGP {
        local as 65538;
        neighbor 192.0.2.2 as 65536;
        import all;
        source address 192.0.2.4;
        multihop;
}
```

This is the UPDATE that I think it's causing the issue:

![image](https://cloud.githubusercontent.com/assets/6806218/18953705/fa5cca84-864f-11e6-9219-cef7dc83a8ce.png)

**Comment by job** [comment]
Can you try:

```
neighbor 192.0.2.4 {
        router-id 192.0.2.2;
        local-address 192.0.2.2;
        local-as 65536;
        peer-as 65538;

        static {
                route 203.0.113.1/32 {
                        next-hop 192.0.2.2
                        large-community [ 65536:1:2 ];
                }
        }
}

**Comment by thomas-mangin** [comment]
Can I ask if you are you using master ?

The `<< UPDATE` mean we are processing an incoming update.

Taking you packet dump and getting ExaBGP to decode it with your configuration works for me

```
./sbin/exabgp test --decode ffffffffffffffffffffffffffffffff00170200000000
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | environment file missing
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | generate it using "exabgp --fi > /Users/thomas/source/git/exabgp/thomas/etc/exabgp/exabgp.env"
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | reactor       | performing reload of exabgp master-2cf365a84e8320c8acff602d289e53fd686138bc
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | > neighbor         | '192.0.2.4'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | . router-id        | '192.0.2.2'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | . local-address    | '192.0.2.2'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | . local-as         | '65536'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | . peer-as          | '65538'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | > static           |
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | > route            | '203.0.113.1/32'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | . next-hop         | '192.0.2.2'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | . large-community  | '[' '65536:1:2' ']'
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | < route            |
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | < static           |
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | configuration | < neighbor         |
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        |
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        | decoding routes in configuration
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        | the message is an update
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        | parsing UPDATE (   4) 0000 0000
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        |
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        | decoded update 1 eor 1/1 (ipv4 unicast)
Thu, 29 Sep 2016 14:33:20 | INFO     | 9858   | parser        | update json { "exabgp": "3.5.0", "time": 1475156000.82, "host" : "Thomas.local", "pid" : 9858, "ppid" : 9267, "counter": 1, "type": "update", "neighbor": { "address": { "local": "192.0.2.2", "peer": "192.0.2.4" }, "asn": { "local": "65536", "peer": "65538" }, "direction": "in", "message": { "update": { "announce": { "ipv4 unicast": { "null": [ "eor": { "afi" : "ipv4", "safi" : "unicast" } ] } } } } } }
```

You can notice a difference between your output  `<< UPDATE (1) (   0)` and mine `UPDATE (   4) 0000 0000` so I am surprised as ExaBGP is saying in effect that your update has _zero_ byte of payload when the wireshark shows _four_ ...

**Comment by pierky** [comment]
I've just tested with the master and I got the same problem.

It only happens if `exabgp.log.routes=true` is used. Even with the only `exabgp.log.all=true` it works fine.

This is the output when using `exabgp.log.routes=true exabgp.log.all=true`:

```
Thu, 29 Sep 2016 13:51:51 | INFO     | 289    | network       | Peer       192.0.2.4 ASN 65538   out loop, peer reset, message [] error[]
Thu, 29 Sep 2016 13:51:52 | WARNING  | 289    | network       | attempting to establish connection
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | message       | Peer       192.0.2.4 ASN 65538   >> OPEN version=4 asn=65536 hold_time=180 router_id=192.0.2.2 capabilities=[Multiprotocol(ipv4 unicast,ipv4 multicast,ipv4 nlri-mpls,ipv4 mpls-vpn,ipv4 rtc,ipv4 flow,ipv4 flow-vpn,ipv6 unicast,ipv6 multicast,ipv6 nlri-mpls,ipv6 mpls-vpn,ipv6 flow,ipv6 flow-vpn,l2vpn vpls,l2vpn evpn), ASN4(65536)]
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | message       | Peer       192.0.2.4 ASN 65538   << OPEN
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | message       | Peer       192.0.2.4 ASN 65538   << OPEN version=4 asn=23456 hold_time=240 router_id=192.0.2.4 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, Graceful Restart Flags 0x0 Time 0 , ASN4(65538), Enhanced Route Refresh]
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | message       | Peer       192.0.2.4 ASN 65538   >> KEEPALIVE (OPENCONFIRM)
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | message       | Peer       192.0.2.4 ASN 65538   << KEEPALIVE
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | network       | Connected to peer neighbor 192.0.2.4 local-ip 192.0.2.2 local-as 65536 peer-as 65538 router-id 192.0.2.2 family-allowed in-open (out)
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | message       | Peer       192.0.2.4 ASN 65538   << UPDATE
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | parser        | parsing UPDATE (   4) 0000 0000
Thu, 29 Sep 2016 13:51:54 | INFO     | 289    | routes        | peer 192.0.2.4 ASN 65538   << UPDATE (1) (   0)
```

Also it works if I use `exabgp.log.routes=true` but I set `graceful restart off;` on the BIRD-side:

```
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   >> OPEN version=4 asn=65536 hold_time=180 router_id=192.0.2.2 capabilities=[Multiprotocol(ipv4 unicast,ipv4 multicast,ipv4 nlri-mpls,ipv4 mpls-vpn,ipv4 rtc,ipv4 flow,ipv4 flow-vpn,ipv6 unicast,ipv6 multicast,ipv6 nlri-mpls,ipv6 mpls-vpn,ipv6 flow,ipv6 flow-vpn,l2vpn vpls,l2vpn evpn), ASN4(65536)]
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   << OPEN
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   << OPEN version=4 asn=23456 hold_time=240 router_id=192.0.2.4 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, ASN4(65538), Enhanced Route Refresh]
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   >> KEEPALIVE (OPENCONFIRM)
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   << KEEPALIVE
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | network       | Connected to peer neighbor 192.0.2.4 local-ip 192.0.2.2 local-as 65536 peer-as 65538 router-id 192.0.2.2 family-allowed in-open (out)
Thu, 29 Sep 2016 13:47:40 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   >> 1 UPDATE(s)
Thu, 29 Sep 2016 13:47:41 | INFO     | 205    | message       | Peer       192.0.2.4 ASN 65538   >> EOR ipv4 unicast
Thu, 29 Sep 2016 13:47:41 | INFO     | 205    | message       | peer 192.0.2.4 ASN 65538   >> EOR(s)
```

(`Graceful Restart Flags 0x0 Time 0` capability missing)

**Comment by thomas-mangin** [comment]
Ok - works for me now :-)

**Comment by thomas-mangin** [comment]
If master is not displaying correctly the capabilities could you open another issue too please ?

**Comment by pierky** [comment]
Perfect:

```
Thu, 29 Sep 2016 15:32:20 5      network       Connected to peer neighbor 192.0.2.4 local-ip 192.0.2.2 local-as 65536 peer-as 65538 router-id 192.0.2.2 family-allowed in-open (out)
Thu, 29 Sep 2016 15:32:20 5      routes        peer 192.0.2.4 ASN 65538   << UPDATE (1) (   0)
Thu, 29 Sep 2016 15:32:20 5      routes        peer 192.0.2.4 ASN 65538   << UPDATE (1) nlri  (   4) eor 1/1 (1 1)
```

With regards of capabilities everything works fine, I was just showing you the difference between the two output messages after I set `graceful restart off` on BIRD.

Thanks

**Comment by thomas-mangin** [comment]
Great to hear ! :-)
