### ISSUE TITLE
ExaBGP does not establish the session when using parsed in the api configuration

### ISSUE THREAD

**Issue by ubajze** [Exa-Networks/exabgp#527]
I am using the the following exaBgp version:

```
[exabgp] --version
ExaBGP : 4.0.0
Python : 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
```

And this is the configuration:

```
process announce-routes {
        run ./vpnv4.run;
        encoder text;
}

template controller {
        family {
                ipv4 nlri-mpls;
                ipv4 unicast;
                ipv4 mpls-vpn;
        }
}

neighbor 172.16.1.1 {
        inherit controller;
        router-id 172.16.1.100;
        local-address 172.16.1.100;
        local-as 65001;
        peer-as 65001;
        group-updates false;

        api {
                processes [ announce-routes ];
                receive {
                        parsed;
                        keepalive;
                }
        }
}
```

And this is the vpn4.run

```
#!/usr/bin/env python

import sys
import time

messages = [
        'announce route 1.1.0.0/24 next-hop 101.1.101.1',
        'neighbor 172.16.1.1 announce route 1.4.0.0/16 rd 65000:1 next-hop 101.1.101.1 community 100:1 extended-community 0x0002FDE900000001 label 1000',
        'announce route 1.5.0.0/16 rd 65000:1 next-hop 101.1.101.1 community 100:1 extended-community 0x0002FDE900000001 label 1000',
]

time.sleep(10)

while messages:
        time.sleep(2)
        message = messages.pop(0)
        sys.stdout.write(message + '\n')
        sys.stdout.flush()

time.sleep(10)
```

When I run this configuration the following Traceback is received and the session is not established:

```
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | routes        | peer 172.16.1.1 ASN 65001   << UPDATE (1) (   4)  attributes origin incomplete med 0 local-preference 100 extended-community target:65001:1
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | routes        | peer 172.16.1.1 ASN 65001   << UPDATE (1) nlri  (  16) 1.1.1.1/32 label [ 18 ] label [ 18 ] route-distinguisher 65001:1 route-distinguisher 65001:1 next-hop 172.16.1.1
Thu, 03 Nov 2016 13:56:12 | DEBUG    | 10170  | wire          | session 1 outgoing 172.16.1.100 / 172.16.1.1        RECEIVED  (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001D 02
Thu, 03 Nov 2016 13:56:12 | DEBUG    | 10170  | wire          | session 1 outgoing 172.16.1.100 / 172.16.1.1        RECEIVED  (  10) 0000 0006 800F 0300 0180
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       | Peer      172.16.1.1 ASN 65001   << UPDATE
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | parser        | parsing UPDATE (  10) 0000 0006 800F 0300 0180
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | parser        | withdrawn NLRI none
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | parser        | attribute mp-unreach-nlri    flag 0x80 type 0x0f len 0x03 payload 0001 80
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | parser        | announced NLRI none
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       | Peer      172.16.1.1 ASN 65001   Could not decode message "2"
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       | Peer      172.16.1.1 ASN 65001   'MPURNLRI' object does not support indexing
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       | Traceback (most recent call last):
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |   File "/usr/lib/python2.6/site-packages/exabgp-4.0.0-py2.6.egg/exabgp/reactor/protocol.py", line 208, in read_message
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |     message = Message.unpack(msg_id,body,self.negotiated)
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |   File "/usr/lib/python2.6/site-packages/exabgp-4.0.0-py2.6.egg/exabgp/bgp/message/message.py", line 181, in unpack
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |     return cls.klass(message).unpack_message(data,negotiated)
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |   File "/usr/lib/python2.6/site-packages/exabgp-4.0.0-py2.6.egg/exabgp/bgp/message/update/__init__.py", line 311, in unpack_message
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |     return EOR(unreach[0].afi,unreach[0].safi)
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       | TypeError: 'MPURNLRI' object does not support indexing
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       |
Thu, 03 Nov 2016 13:56:12 | DEBUG    | 10170  | wire          | session 1 outgoing 172.16.1.100 / 172.16.1.1        SENDING  (  62) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003E 0301 0063 616E 206E 6F74 2064 6563 6F64 6520 7570 6461 7465 206D 6573 7361 6765 206F 6620 7479 7065 2022 3222
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | message       | Peer      172.16.1.1 ASN 65001   >> NOTIFICATION (1,0,"can not decode update message of type "2"")
Thu, 03 Nov 2016 13:56:12 | INFO     | 10170  | network       | Peer      172.16.1.1 ASN 65001   out loop, peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
```

When I remove `parsed` from the configuration, the session is successfully established, and exaBgp send the update.

The peer router is Cisco CSR1000v.

**Comment by ubajze** [comment]
I have removed indexes from `exabgp/bgp/message/update/__init__.py` line 311.

```return EOR(unreach[0].afi,unreach[0].safi) -> return EOR(unreach.afi,unreach.safi)```

Now it works as expected.

**Comment by thomas-mangin** [comment]
I can reproduce `./sbin/exabgp test --decode "0000 0006 800F 0300 0180"`

**Comment by thomas-mangin** [comment]
Yes, this is right, the bug was caused the the RFC7606 implementation (last week?) - ExaBGP would accept multiple MP attributes but now only accepts one.

Fixed with https://github.com/Exa-Networks/exabgp/commit/7c5c9867d96d5d7eb1c2d77f4d5cc86f05ebd9d3

Thank you.
