### ISSUE TITLE
EXABGP Crashes When Sending Labeled route via API

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#547]
Hi Thomas,

I've come back  to do some more testing with 4.0 and it seems theres an issue now with accepting labelled routes via the API (postman).  This used to work with 4.0 from Sept after bug fix https://github.com/Exa-Networks/exabgp/issues/476

This still works just fine with 3.4.17

Command sent:  announce route 100.0.0.0/24 next-hop 192.168.58.11 label [80001] 

Below is the debug output:

```

192.168.0.1 - - [07/Dec/2016 02:54:43] "POST / HTTP/1.1" 200 -
Wed, 07 Dec 2016 02:54:43 | DEBUG    | 19798  | timers        | peer 192.168.58.10 ASN 64512   Receive Timer 160 second(s) left
Wed, 07 Dec 2016 02:54:43 | DEBUG    | 19798  | timers        | peer 192.168.58.10 ASN 64512   Send Timer 41 second(s) left
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | processes     | Command from process http-api : announce route 100.0.0.0/24 next-hop 192.168.58.11 label [80001] 
Wed, 07 Dec 2016 02:54:43 | WARNING  | 19798  | reactor       | callback | handling 'announce route 100.0.0.0/24 next-hop 192.168.58.11 label [ 80001 ]' with announce_route
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | reactor       | callback | installing announce_route
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | reactor       | callback | running
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | configuration | . route            | '100.0.0.0/24' 'next-hop' '192.168.58.11' 'label' '[' '80001' ']'
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | reactor       | route added to neighbor 192.168.58.10 local-ip 192.168.0.2 local-as 64512 peer-as 64512 router-id 192.168.0.2 family-allowed in-open : 100.0.0.0/24 label [ 80001 ] next-hop 192.168.58.11
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | reactor       | responding to http-api : done
Wed, 07 Dec 2016 02:54:43 | INFO     | 19798  | reactor       | callback | removing
Wed, 07 Dec 2016 02:54:44 | INFO     | 19798  | reactor       | performing dynamic route update
Wed, 07 Dec 2016 02:54:44 | INFO     | 19798  | reactor       | updated peers dynamic routes successfully
Wed, 07 Dec 2016 02:54:44 | DEBUG    | 19798  | timers        | peer 192.168.58.10 ASN 64512   Receive Timer 159 second(s) left
Wed, 07 Dec 2016 02:54:44 | DEBUG    | 19798  | timers        | peer 192.168.58.10 ASN 64512   Send Timer 40 second(s) left

********************************************************************************
EXABGP MISBEHAVED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP, as the problem only affects one
peer, we are trying to keep the program running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 4.0.0
Python version : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
System Uname   : #1 SMP Wed Oct 26 14:21:29 UTC 2016
System MaxInt  : 9223372036854775807


peer 192.168.58.10 ASN 64512   

<type 'exceptions.RuntimeError'>
dictionary changed size during iteration
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/peer.py", line 637, in _run
    for action in self._main(direction):
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/peer.py", line 586, in _main
    new_routes.next()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.0-py2.7.egg/exabgp/reactor/protocol.py", line 306, in new_update
    for update in updates:
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.0-py2.7.egg/exabgp/rib/store.py", line 242, in updates
    for change in dict_change.itervalues():
RuntimeError: dictionary changed size during iteration

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
```

**Comment by thomas-mangin** [comment]
Something I changed as I would have bet the house it could not happen ...

**Comment by russellkelly** [comment]
Should I verify the fix in the latest master?

**Comment by thomas-mangin** [comment]
Yes please.

**Comment by russellkelly** [comment]
Yes this fixed the crash.  Thanks!
