### ISSUE TITLE
Get Some Error....

### ISSUE THREAD

**Issue by xssec** [Exa-Networks/exabgp#554]
root@ubuntu:~# exabgp -version
`ExaBGP : 3.4.17
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
Uname  : #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016`

root@ubuntu:~# python -m exabgp healthcheck
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/exabgp/__main__.py", line 44, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/__main__.py", line 33, in main
    run_healthcheck()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/__init__.py", line 21, in run_healthcheck
    from exabgp.application.healthcheck import main
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/healthcheck.py", line 69, in <module>
    from ipaddr import IPAddress as ip_address
ImportError: No module named ipaddr`

root@ubuntu:~#

**Comment by thomas-mangin** [comment]
As you installed from source, from the folder:
```
> pip install -r requirements.txt
```
