### ISSUE TITLE
ImportError: No module named six.moves

### ISSUE THREAD

**Issue by wydrych** [Exa-Networks/exabgp#589]
##### ISSUE TYPE

 - Bug Report

##### OS
```
$ uname -mrsv
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
```

##### VERSION

Cannot execute "exabgp --version", pasting git information
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
$ git log -n 1
commit 15dfe038d41e0c2c2622bd4e28d548a7b248a02d
Merge: 0067c0e 88ef753
Author: Vincent Bernat <vincent@bernat.im>
Date:   Thu Mar 16 15:07:20 2017 +0100

    Merge pull request #587 from aj-gh/healthcheck-dynip-fix
    
    healthcheck.py: Fix nonexistent option name - ips_deleted vs. ip_dynamic
```

##### ENVIRONMENT 

Cannot execute "exabgp --di"

##### CONFIGURATION

n/a

##### SUMMARY

ExaBGP doesn't start. If fails loading anything from "six.moves"

##### STEPS TO REPRODUCE

Execute ExaBGP.

##### EXPECTED RESULTS

Running ExaBGP

##### ACTUAL RESULTS

```
$ pwd
/tmp/exabgp
$ sbin/exabgp 
Traceback (most recent call last):
  File "/tmp/exabgp/lib/exabgp/application/bgp.py", line 19, in <module>
    from exabgp.reactor.loop import Reactor
  File "/tmp/exabgp/lib/exabgp/reactor/loop.py", line 29, in <module>
    from exabgp.reactor.peer import Peer
  File "/tmp/exabgp/lib/exabgp/reactor/peer.py", line 35, in <module>
    from exabgp.util.trace import trace
  File "/tmp/exabgp/lib/exabgp/util/trace.py", line 11, in <module>
    from six.moves import StringIO
ImportError: No module named six.moves
```

##### IMPORTANCE

It's affecting my test/QA environment

**Comment by thomas-mangin** [comment]
@tmmorin one for you !

**Comment by thomas-mangin** [comment]
Sorry need to install six with pip or link to the version in exabgp vending .. will fix.
