### ISSUE TITLE
UnboundLocalError: local variable 'fd' referenced before assignment

### ISSUE THREAD

**Issue by amarao** [Exa-Networks/exabgp#593]
##### ISSUE TYPE

 - Bug Report

##### OS
- ubuntu 14.04

##### VERSION

```
ExaBGP : 3.4.18
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
Uname  : #152-Ubuntu SMP Fri Dec 2 15:37:11 UTC 201
```

##### ENVIRONMENT 

```

[exabgp.daemon]
pid = '/tmp/exabgp.pid'
user = 'exabgp'

[exabgp.log]
destination = 'syslog'

```

##### SUMMARY

Exabgp crashes: UnboundLocalError: local variable 'fd' referenced before assignment
##### STEPS TO REPRODUCE
Exabgp is run from upstart job:

description     "EXABGP"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 022

env exabgp.daemon.user=exabgp
env exabgp.log.destination=syslog
env exabgp.daemon.pid=/tmp/exabgp.pid

exec exabgp /etc/exabgp/exabgp.conf

##### EXPECTED RESULTS
Working exa

##### ACTUAL RESULTS

Traceback (most recent call last):
  File "/usr/local/bin/exabgp", line 11, in <module>
    sys.exit(run_exabgp())
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/__init__.py", line 12, in run_exabgp
    main()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/bgp.py", line 221, in main
    run(env,comment,configurations)
  File "/usr/local/lib/python2.7/dist-packages/exabgp/application/bgp.py", line 260, in run
    ok = Reactor(configurations).run()
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/loop.py", line 174, in run
    if not self.daemon.savepid():
  File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/daemon.py", line 79, in savepid
    f = os.fdopen(fd,'w')
UnboundLocalError: local variable 'fd' referenced before assignment

**Comment by amarao** [comment]
This had happened because /tmp/exabgp.pid had been owned by nobody:nobody and exabgp had been run as 'exabgp' user.

Nevertheless it shouldn't cause such a tremolos trace.

**Comment by thomas-mangin** [comment]
Thank you very much for the report. It has been fixed with the above patches (hopefully 😉)
