### ISSUE TITLE
BGP peering error on 4.0.1

### ISSUE THREAD

**Issue by nidotech** [Exa-Networks/exabgp#670]
##### ISSUE TYPE
 - Bug Report

##### OS
Linux fastnetmon 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64

##### VERSION
```
ExaBGP version : 4.0.1-4501ddf3
Python version : 3.4.2 (default, Oct  8 2014, 10:45:20)  [GCC 4.9.1]
System Uname   : #1 SMP Debian 3.16.43-2 (2017-04-30)
System MaxInt  : 9223372036854775807
```
##### ENVIRONMENT 
```
[exabgp.daemon]
daemonize = true
pid = '/var/run/exabgp.pid'
user = 'root'

[exabgp.log]
destination = '/var/log/exabgp.log'
```

##### CONFIGURATION

```
process announce-routes {
        run /usr/bin/socat stdout pipe:/var/run/exabgp.cmd;
        encoder json;
}

neighbor 1.1.1.3 {
                router-id 1.1.1.9;
                local-address 1.1.1.9;
                local-as 65001;
                peer-as 4594;
                hold-time 180;
                capability {
                        graceful-restart 120;
                }
                api { processes [ announce-routes ]; }
}
neighbor 1.1.1.4 {
                router-id 1.1.1.9;
                local-address 1.1.1.9;
                local-as 65001;
                peer-as 4594;
                hold-time 180;
                capability {
                        graceful-restart 120;
                }
                api { processes [ announce-routes ]; }
}
```

##### SUMMARY
peering problem on both peers on 4.0.1 when starting which did not happen on 4.0.0

##### STEPS TO REPRODUCE
the error keep popping up every few seconds

##### ACTUAL RESULTS
```
<class 'struct.error'>
argument for 's' must be a bytes object
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/exabgp/reactor/peer.py", line 503, in _run
    for action in self._establish():
  File "/usr/local/lib/python3.4/dist-packages/exabgp/reactor/peer.py", line 294, in _establish
    for action in self._connect():
  File "/usr/local/lib/python3.4/dist-packages/exabgp/reactor/peer.py", line 244, in _connect
    connected = six.next(generator)
  File "/usr/local/lib/python3.4/dist-packages/exabgp/reactor/protocol.py", line 107, in connect
    self.connection = Outgoing(afi,peer,local,self.port,md5,md5_base64,ttl_out)
  File "/usr/local/lib/python3.4/dist-packages/exabgp/reactor/network/outgoing.py", line 31, in __init__
    MD5(self.io,self.peer,port,md5,md5_base64)
  File "/usr/local/lib/python3.4/dist-packages/exabgp/reactor/network/tcp.py", line 166, in MD5
    key = pack('2xH4x%ds' % TCP_MD5SIG_MAXKEYLEN, 0, '')
struct.error: argument for 's' must be a bytes object

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

Mon, 26 Jun 2017 09:55:12 6652   outgoing-1    connection to 1.1.1.3 closed
Mon, 26 Jun 2017 09:55:12 6652   outgoing-1    outgoing-1 1.1.1.9-1.1.1.3, closing connection from 1.1.1.9 to 1.1.1.3
Mon, 26 Jun 2017 09:55:12 6652   wire          attempting connection outgoing-1 to 1.1.1.4:179
```

**Comment by thomas-mangin** [comment]
Can you please let me know if master fixes the issue. I will most likely release 4.0.2 very soon.

**Comment by nidotech** [comment]
i was using pip version.  
I've just downloaded the latest master and try but it showed this error:
Traceback (most recent call last):
  File "/root/exabgp/exabgp-master/lib/exabgp/application/bgp.py", line 16, in <module>
    from exabgp.util.dns import warn
ImportError: No module named 'exabgp.util'

**Comment by thomas-mangin** [comment]
How are you running this exabgp instance ? To me it looks like the new program is trying to use the code installed by pip.
from the folder it should be `./sbin/exabgp` or the full path and/or use `pip uninstall exabgp`

**Comment by nidotech** [comment]
tried uninstall, same error.

I was running through the cli './sbin/exabgp  -e /etc/exabgp/exabgp.env -d /etc/exabgp/exabgp.conf'

**Comment by thomas-mangin** [comment]
Can you please please provide the output of `exabgp -d` so I can see the debug information please.

**Comment by nidotech** [comment]
oh, look like something is missing...
```
root@fastnetmon:~/exabgp-master# ./sbin/exabgp --help
Traceback (most recent call last):
  File "/root/exabgp-master/lib/exabgp/application/bgp.py", line 17, in <module>
    from exabgp.util.dns import warn
ImportError: No module named 'exabgp.util'
```

**Comment by thomas-mangin** [comment]
Can you please look if there is a file in your repo called `lib/exabgp/utils/dns.py` it is in mine !!
I would invite you to run './qa/bin/rmpyc' and see if it fixes the issue.

**Comment by thomas-mangin** [comment]
and if it does not could you please give me the output of `echo $PYTHONPATH` from the shell used.

**Comment by nidotech** [comment]
thanks for helping, there was a corrupted ZIP file that i didn't notice. =/
