### ISSUE TITLE
unimplemented in NLRI children class ()

### ISSUE THREAD

**Issue by dmkovalenko** [Exa-Networks/exabgp#675]
Bug Report
```
ExaBGP version : 4.0.1-4501ddf3
Python version : 2.7.13 (default, Jul  2 2017, 01:18:12)  [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]
System Uname   : FreeBSD 11.0-RELEASE-p9 #0: Tue Apr 11 08:48:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
System MaxInt  : 9223372036854775807
```

```
<type 'exceptions.Exception'>
unimplemented in NLRI children class
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/exabgp/reactor/peer.py", line 506, in _run
    for action in self._main():
  File "/usr/local/lib/python2.7/site-packages/exabgp/reactor/peer.py", line 385, in _main
    self.neighbor.rib.incoming.update_cache(Change(nlri,message.attributes))
  File "/usr/local/lib/python2.7/site-packages/exabgp/rib/cache.py", line 74, in update_cache
    index = change.index()
  File "/usr/local/lib/python2.7/site-packages/exabgp/rib/change.py", line 37, in index
    self.__index = '%02x%02x' % self.nlri.family() + self.nlri.index()
  File "/usr/local/lib/python2.7/site-packages/exabgp/bgp/message/update/nlri/nlri.py", line 67, in index
    return self._index() + str(self.pack_nlri())
  File "/usr/local/lib/python2.7/site-packages/exabgp/bgp/message/update/nlri/nlri.py", line 74, in pack_nlri
    raise Exception('unimplemented in NLRI children class')
Exception: unimplemented in NLRI children class
```
##### CONFIGURATION
```
neighbor 10.1.1.2 {
        description "addpath route reception";
        router-id 10.1.1.1;
        local-address 10.1.1.1;
        local-as 65412;
        peer-as 65412;
        hold-time 180;
        group-updates false;

        capability {
                add-path send/receive;
        }

        family {
                ipv4 unicast;
        }

}
```
##### SUMMARY

Crash occurs when BGP UPDATE Message is received with no NLRI (Total Path Attribute Length: 0)
```
Border Gateway Protocol - UPDATE Message
    Marker: ffffffffffffffffffffffffffffffff
    Length: 23
    Type: UPDATE Message (2)
    Withdrawn Routes Length: 0
    Total Path Attribute Length: 0
```

**Comment by thomas-mangin** [comment]
AFAICS this should have already been fixed in master. I am due to release 4.0.2 any day now.

**Comment by thomas-mangin** [comment]
```
08:30:33 | 42565  | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 02
08:30:33 | 42565  | outgoing-1    | received TCP payload (   4) 0000 0000
08:30:33 | 42565  | outgoing-1    | << message of type UPDATE
08:30:33 | 42565  | parser        | parsing UPDATE (   4) 0000 0000
08:30:33 | 42565  | outgoing-1    | send-timer 60 second(s) left
08:30:33 | 42565  | peer-1        | << UPDATE #1
08:30:33 | 42565  | peer-1        |    UPDATE #1 nlri  (   4) eor 1/1 (ipv4 unicast)
```
