### ISSUE TITLE
ExaBGP does not work on Windows

### ISSUE THREAD

**Issue by WenceyWang** [Exa-Networks/exabgp#687]
##### ISSUE TYPE
 - Bug Report

##### OS
Windows Server 2016 Datacenter
Build 14393.1480

##### VERSION

```
C:\Users\WenceyWang>exabgp --version
Traceback (most recent call last):
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\WenceyWang\AppData\Local\Programs\Python\Python36\Scripts\exabgp.exe\__main__.py", line 9, in <module>
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\site-packages\exabgp\application\__init__.py", line 12, in run_exabgp
    from exabgp.application.bgp import main
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\site-packages\exabgp\application\bgp.py", line 14, in <module>
    import syslog
ModuleNotFoundError: No module named 'syslog'
```

pip told me "exabgp-4.0.2-py3-none-any.whl"
My python is 3.6.2

##### ENVIRONMENT 

```
C:\Users\WenceyWang>exabgp --di
Traceback (most recent call last):
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\WenceyWang\AppData\Local\Programs\Python\Python36\Scripts\exabgp.exe\__main__.py", line 9, in <module>
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\site-packages\exabgp\application\__init__.py", line 12, in run_exabgp
    from exabgp.application.bgp import main
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\site-packages\exabgp\application\bgp.py", line 14, in <module>
    import syslog
ModuleNotFoundError: No module named 'syslog'
```

##### CONFIGURATION

I have no config file

##### SUMMARY

On Windows there is no syslog and maybe https://docs.python.org/3/library/logging.html is better ?

##### STEPS TO REPRODUCE

pip install exabgp
exabgp --help

##### EXPECTED RESULTS

I get the help content.

##### ACTUAL RESULTS
```
C:\Users\WenceyWang>exabgp --help
Traceback (most recent call last):
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\WenceyWang\AppData\Local\Programs\Python\Python36\Scripts\exabgp.exe\__main__.py", line 9, in <module>
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\site-packages\exabgp\application\__init__.py", line 12, in run_exabgp
    from exabgp.application.bgp import main
  File "c:\users\wenceywang\appdata\local\programs\python\python36\lib\site-packages\exabgp\application\bgp.py", line 14, in <module>
    import syslog
ModuleNotFoundError: No module named 'syslog'
```

**Comment by WenceyWang** [comment]
I have some hack and bypass the log and I get ```ModuleNotFoundError: No module named 'pwd'```

**Comment by thomas-mangin** [comment]
Windows is not a supported platform ATM

**Comment by thomas-mangin** [comment]
To explain some more. ExaBGP makes use of specific unix features which I do not believe are available on windows. I am not opposed to adding windows support but as I have not run a computer under windows since Windows CE, I will clearly not be the best person for it..
