### ISSUE TITLE
parser.py resetting peer

### ISSUE THREAD

**Issue by abreu75** [Exa-Networks/exabgp#698]
##### ISSUE TYPE
 - Bug Report

##### OS
Linux

##### VERSION
```
Linux xxx 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
```

##### ENVIRONMENT 
```
exabgp --di
output is empty
```

##### CONFIGURATION
```
process handleit {
	encoder json;
	run /home/abreual/scripts/readroutes.py;
#	run /home/abreual/scripts/dummy.py;
}

neighbor 83.174.51.241 {
	router-id 213.30.19.219;
	local-address 213.30.19.219;
	hold-time 180;
	local-as 12353;
	peer-as 12353;
	family {
		ipv4 mpls-vpn;
	}
	api speaking {
		processes [ handleit ];
		receive {
			parsed;
#			keepalive;
			update;
		}
	}
}
```

##### SUMMARY
exabgp resets session with
```
11:01:15 | 22359  | reactor       | ********************************************************************************
11:01:15 | 22359  | reactor       | -- Please provide ALL the information below on :
11:01:15 | 22359  | reactor       | -- https://github.com/Exa-Networks/exabgp/issues
11:01:15 | 22359  | reactor       | ********************************************************************************
11:01:15 | 22359  | reactor       |         
11:01:15 | 22359  | reactor       | ExaBGP version : 4.0.2-1c737d99
11:01:15 | 22359  | reactor       | Python version : 2.7.12+ (default, Aug  4 2016, 20:04:34)  [GCC 6.1.1 20160724]
11:01:15 | 22359  | reactor       | System Uname   : #1 SMP Debian 4.6.4-1kali1 (2016-07-21)
11:01:15 | 22359  | reactor       | System MaxInt  : 9223372036854775807
11:01:15 | 22359  | reactor       |         
11:01:15 | 22359  | reactor       |         
11:01:15 | 22359  | reactor       |         
11:01:15 | 22359  | reactor       |         
11:01:15 | 22359  | reactor       | <type 'exceptions.TypeError'>
11:01:15 | 22359  | reactor       | %d format: a number is required, not str
11:01:15 | 22359  | reactor       | Traceback (most recent call last):
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 519, in _run
11:01:15 | 22359  | reactor       |     for action in self._main():
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 390, in _main
11:01:15 | 22359  | reactor       |     for message in self.proto.read_message():
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/protocol.py", line 249, in read_message
11:01:15 | 22359  | reactor       |     self.peer.reactor.processes.message(msg_id,self.neighbor,'receive',message,negotiated,b'',b'')
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 289, in closure
11:01:15 | 22359  | reactor       |     return function(self,*args)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 335, in message
11:01:15 | 22359  | reactor       |     self._dispatch[message_id](self,neighbor,direction,message,negotiated,header,*body)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 343, in wrap
11:01:15 | 22359  | reactor       |     function(*args)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/processes.py", line 358, in _update
11:01:15 | 22359  | reactor       |     self._write(process,self._encoder[process].update(peer,direction,update,negotiated,header,body),peer)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/response/json.py", line 277, in update
11:01:15 | 22359  | reactor       |     message = self._update(update)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/api/response/json.py", line 266, in _update
11:01:15 | 22359  | reactor       |     attributes = '' if not update.attributes else '"attribute": { %s }' % update.attributes.json()
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/attributes.py", line 271, in json
11:01:15 | 22359  | reactor       |     self._json = ', '.join(self._generate_json())
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/attributes.py", line 173, in _generate_json
11:01:15 | 22359  | reactor       |     yield '"%s": %s' % (name, presentation % attribute.json())
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/community/initial/communities.py", line 57, in json
11:01:15 | 22359  | reactor       |     return "[ %s ]" % ", ".join(community.json() for community in self.communities)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/community/initial/communities.py", line 57, in <genexpr>
11:01:15 | 22359  | reactor       |     return "[ %s ]" % ", ".join(community.json() for community in self.communities)
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/community/extended/community.py", line 93, in json
11:01:15 | 22359  | reactor       |     s = self.klass.__repr__(self) if self.klass else ''
11:01:15 | 22359  | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/community/extended/rt.py", line 107, in __repr__
11:01:15 | 22359  | reactor       |     return "%s:%d:%d" % (self.DESCRIPTION,self.ip,self.number)
11:01:15 | 22359  | reactor       | TypeError: %d format: a number is required, not str
11:01:15 | 22359  | reactor       |         
11:01:15 | 22359  | reactor       | ********************************************************************************
11:01:15 | 22359  | reactor       | -- Please provide _ALL_ the information above on :
11:01:15 | 22359  | reactor       | -- https://github.com/Exa-Networks/exabgp/issues
11:01:15 | 22359  | reactor       | ********************************************************************************
```

##### STEPS TO REPRODUCE
Just start exabgp with a process to handle updates and wait.

##### EXPECTED RESULTS
update processing until EoR received

##### ACTUAL RESULTS
exabgp tear session down due to parsing error

##### IMPORTANCE
It affects current development of a monitoring solution.

**Comment by thomas-mangin** [comment]
Could you please confirm what is now printed ?

**Comment by abreu75** [comment]
Hi

It has been running for over an hour now without apparent issues so I'd say it's fixed. Thanks

AA

**Comment by rat2k4** [comment]
Changing %d to %s seems to be working fine now.
