### ISSUE TITLE
Route refresh request crashes ExaBGP

### ISSUE THREAD

**Issue by nfz1** [Exa-Networks/exabgp#708]
##### ISSUE TYPE

 - Bug Report

##### OS
Ubuntu 16.04.3 LTS

##### VERSION

_Current master_
```
ExaBGP : 4.0.2-1c737d99
Python : 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
Uname  : Linux 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64
Root   : /usr/local
```

##### CONFIGURATION

```
process app {
    run /usr/bin/python3 /scratch/bgpsdn/Controller.py /tmp/mn-test_route_refresh-pxoOcp/config/c1.yaml;
    encoder json;
}
neighbor 10.0.2.1 {
    router-id 127.0.0.1;
    local-address 10.0.2.2;
    local-as 1;
    peer-as 2;
    group-updates;

    family {
        ipv4 unicast;
    }

    capability {
        route-refresh;
    }

    api {
        processes [ app ];
        neighbor-changes;

        receive {
            parsed;
            open;
            update;
        }

        send {
            update;
        }
    }
}
```

##### SUMMARY

ExaBGP seems to crash when it encounters a route refresh request. When a route refresh request is received an exception is thrown and ExaBGP closes and re-establishes the connection to the peer.

##### STEPS TO REPRODUCE

Connect and pair two ExaBGP instances. Send a route refresh request from one of the peers to the other.
```
neighbor 10.0.2.2 announce route-refresh ipv4 unicast
```

##### EXCEPTION OUTPUT
```
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | EXABGP MISBEHAVED / HELP US FIX IT
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | Sorry, you encountered a problem with ExaBGP, as the problem only affects one
13:46:16 | 13734  | reactor         | peer, we are trying to keep the program running.
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | There are a few things you can do to help us (and yourself):
13:46:16 | 13734  | reactor         | - make sure you are running the latest version of the code available at
13:46:16 | 13734  | reactor         |   https://github.com/Exa-Networks/exabgp/releases/latest
13:46:16 | 13734  | reactor         | - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         |   so it can be fixed (github can be searched for similar reports)
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | PLEASE, when reporting, do include as much information as you can:
13:46:16 | 13734  | reactor         | - do not obfuscate any data (feel free to send us a private  email with the
13:46:16 | 13734  | reactor         |   extra information if your business policy is strict on information sharing)
13:46:16 | 13734  | reactor         |   https://github.com/Exa-Networks/exabgp/wiki/FAQ
13:46:16 | 13734  | reactor         | - if you can reproduce the issue, run ExaBGP with the command line option -d
13:46:16 | 13734  | reactor         |   it provides us with much needed information to fix problems quickly
13:46:16 | 13734  | reactor         | - include the information presented below
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | Should you not receive an acknowledgment of your issue on github (assignement,
13:46:16 | 13734  | reactor         | comment, or similar) within a few hours, feel free to email us to make sure
13:46:16 | 13734  | reactor         | it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | -- Please provide ALL the information below on :
13:46:16 | 13734  | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ExaBGP version : 4.0.2-1c737d99
13:46:16 | 13734  | reactor         | Python version : 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
13:46:16 | 13734  | reactor         | System Uname   : #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017
13:46:16 | 13734  | reactor         | System MaxInt  : 9223372036854775807
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | <class 'TypeError'>
13:46:16 | 13734  | reactor         | 'RouteRefresh' object is not iterable
13:46:16 | 13734  | reactor         | Traceback (most recent call last):
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/peer.py", line 519, in _run
13:46:16 | 13734  | reactor         |     for action in self._main():
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/peer.py", line 469, in _main
13:46:16 | 13734  | reactor         |     six.next(new_routes)
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/protocol.py", line 347, in new_update
13:46:16 | 13734  | reactor         |     for message in update.messages(self.negotiated,include_withdraw):
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/bgp/message/update/__init__.py", line 115, in messages
13:46:16 | 13734  | reactor         |     for nlri in sorted(self.nlris):
13:46:16 | 13734  | reactor         | TypeError: 'RouteRefresh' object is not iterable
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | -- Please provide _ALL_ the information above on :
13:46:16 | 13734  | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | EXABGP MISBEHAVED / HELP US FIX IT
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | Sorry, you encountered a problem with ExaBGP, as the problem only affects one
13:46:16 | 13734  | reactor         | peer, we are trying to keep the program running.
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | There are a few things you can do to help us (and yourself):
13:46:16 | 13734  | reactor         | - make sure you are running the latest version of the code available at
13:46:16 | 13734  | reactor         |   https://github.com/Exa-Networks/exabgp/releases/latest
13:46:16 | 13734  | reactor         | - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         |   so it can be fixed (github can be searched for similar reports)
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | PLEASE, when reporting, do include as much information as you can:
13:46:16 | 13734  | reactor         | - do not obfuscate any data (feel free to send us a private  email with the
13:46:16 | 13734  | reactor         |   extra information if your business policy is strict on information sharing)
13:46:16 | 13734  | reactor         |   https://github.com/Exa-Networks/exabgp/wiki/FAQ
13:46:16 | 13734  | reactor         | - if you can reproduce the issue, run ExaBGP with the command line option -d
13:46:16 | 13734  | reactor         |   it provides us with much needed information to fix problems quickly
13:46:16 | 13734  | reactor         | - include the information presented below
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | Should you not receive an acknowledgment of your issue on github (assignement,
13:46:16 | 13734  | reactor         | comment, or similar) within a few hours, feel free to email us to make sure
13:46:16 | 13734  | reactor         | it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | -- Please provide ALL the information below on :
13:46:16 | 13734  | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ExaBGP version : 4.0.2-1c737d99
13:46:16 | 13734  | reactor         | Python version : 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
13:46:16 | 13734  | reactor         | System Uname   : #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017
13:46:16 | 13734  | reactor         | System MaxInt  : 9223372036854775807
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | <class 'TypeError'>
13:46:16 | 13734  | reactor         | 'RouteRefresh' object is not iterable
13:46:16 | 13734  | reactor         | Traceback (most recent call last):
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/peer.py", line 519, in _run
13:46:16 | 13734  | reactor         |     for action in self._main():
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/peer.py", line 469, in _main
13:46:16 | 13734  | reactor         |     six.next(new_routes)
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/protocol.py", line 347, in new_update
13:46:16 | 13734  | reactor         |     for message in update.messages(self.negotiated,include_withdraw):
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/bgp/message/update/__init__.py", line 115, in messages
13:46:16 | 13734  | reactor         |     for nlri in sorted(self.nlris):
13:46:16 | 13734  | reactor         | TypeError: 'RouteRefresh' object is not iterable
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | -- Please provide _ALL_ the information above on :
13:46:16 | 13734  | reactor         | -- Please provide ALL the information below on :
13:46:16 | 13734  | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ExaBGP version : 4.0.2-1c737d99
13:46:16 | 13734  | reactor         | Python version : 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
13:46:16 | 13734  | reactor         | System Uname   : #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017
13:46:16 | 13734  | reactor         | System MaxInt  : 9223372036854775807
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | <class 'TypeError'>
13:46:16 | 13734  | reactor         | 'RouteRefresh' object is not iterable
13:46:16 | 13734  | reactor         | Traceback (most recent call last):
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/peer.py", line 519, in _run
13:46:16 | 13734  | reactor         |     for action in self._main():
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/peer.py", line 469, in _main
13:46:16 | 13734  | reactor         |     six.next(new_routes)
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/protocol.py", line 347, in new_update
13:46:16 | 13734  | reactor         |     for message in update.messageamp-servers(self.negotiated,include_withdraw):
13:46:16 | 13734  | reactor         |   File "/usr/local/lib/python3.5/dist-packages/exabgp/bgp/message/update/__init__.py", line 115, in messages
13:46:16 | 13734  | reactor         |     for nlri in sorted(self.nlris):
13:46:16 | 13734  | reactor         | TypeError: 'RouteRefresh' object is not iterable
13:46:16 | 13734  | reactor         |
13:46:16 | 13734  | reactor         | ********************************************************************************
13:46:16 | 13734  | reactor         | -- Please provide _ALL_ the information above on :
13:46:16 | 13734  | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
13:46:16 | 13734  | reactor         | ********************************************************************************
```

**Comment by thomas-mangin** [comment]
Thank you for this report, I will look into it.

**Comment by thomas-mangin** [comment]
would this patch fix the issue please ?
```patch
20:28 $ git diff
diff --git a/lib/exabgp/reactor/api/__init__.py b/lib/exabgp/reactor/api/__init__.py
index ab2d7410..1754af5c 100644
--- a/lib/exabgp/reactor/api/__init__.py
+++ b/lib/exabgp/reactor/api/__init__.py
@@ -104,7 +104,7 @@ class API (Command):
                safi = SAFI.value(tokens.pop(0))
                if afi is None or safi is None:
                        return False
-               return RouteRefresh(afi,safi)
+               return [RouteRefresh(afi,safi)]

        def api_eor (self, command):
                tokens = formated(command).split(' ')[2:]
```

**Comment by nfz1** [comment]
Hi,

I wrote two test programs to try to the patch. ExaBGP seems to no longer send route refresh messages after applying it. There is now a new error, here is the log output from the sender of the route-refresh request.

```
10:11:34 | 21857  | welcome       | Thank you for using ExaBGP
10:11:34 | 21857  | version       | 4.0.2-1c737d99
10:11:34 | 21857  | interpreter   | 3.5.2 (default, Sep 14 2017, 22:51:06)  [GCC 5.4.0 20160609]
10:11:34 | 21857  | os            | Linux amp-server 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64
10:11:34 | 21857  | installation  | /usr/local
10:11:34 | 21857  | advice        | environment file missing
10:11:34 | 21857  | advice        | generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"
10:11:34 | 21857  | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
10:11:34 | 21857  | cli           | we scanned the following folders (the number is your PID):
10:11:34 | 21857  | cli control   |  - /run/exabgp/
10:11:34 | 21857  | cli control   |  - /run/0/
10:11:34 | 21857  | cli control   |  - /run/
10:11:34 | 21857  | cli control   |  - /var/run/exabgp/
10:11:34 | 21857  | cli control   |  - /var/run/0/
10:11:34 | 21857  | cli control   |  - /var/run/
10:11:34 | 21857  | cli control   |  - /usr/local/run/exabgp/
10:11:34 | 21857  | cli control   |  - /usr/local/run/0/
10:11:34 | 21857  | cli control   |  - /usr/local/run/
10:11:34 | 21857  | cli control   |  - /usr/local/var/run/exabgp/
10:11:34 | 21857  | cli control   |  - /usr/local/var/run/0/
10:11:34 | 21857  | cli control   |  - /usr/local/var/run/
10:11:34 | 21857  | cli control   | please make them in one of the folder with the following commands:
10:11:34 | 21857  | cli control   | > mkfifo /scratch/com_test/run/exabgp.{in,out}
10:11:34 | 21857  | cli control   | > chmod 600 /scratch/com_test/run/exabgp.{in,out}
10:11:34 | 21857  | configuration | performing reload of exabgp 4.0.2-1c737d99
10:11:34 | 21857  | configuration | > process          | 'app'
10:11:34 | 21857  | configuration | . run              | '/usr/bin/python3' '/scratch/com_test/tester.py'
10:11:34 | 21857  | configuration | . encoder          | 'json'
10:11:34 | 21857  | configuration | < process          | 
10:11:34 | 21857  | configuration | > neighbor         | '10.0.2.1'
10:11:34 | 21857  | configuration | . router-id        | '127.0.0.2'
10:11:34 | 21857  | configuration | . local-address    | '10.0.2.2'
10:11:34 | 21857  | configuration | . local-as         | '2'
10:11:34 | 21857  | configuration | . peer-as          | '1'
10:11:34 | 21857  | configuration | . group-updates    | 
10:11:34 | 21857  | configuration | . listen           | '179'
10:11:34 | 21857  | configuration | > family           | 
10:11:34 | 21857  | configuration | . ipv4             | 'unicast'
10:11:34 | 21857  | configuration | < family           | 
10:11:34 | 21857  | configuration | > capability       | 
10:11:34 | 21857  | configuration | . route-refresh    | 
10:11:34 | 21857  | configuration | < capability       | 
10:11:34 | 21857  | configuration | > api              | 
10:11:34 | 21857  | configuration | . processes        | '[' 'app' ']'
10:11:34 | 21857  | configuration | . neighbor-changes | 
10:11:34 | 21857  | configuration | > receive          | 
10:11:34 | 21857  | configuration | . parsed           | 
10:11:34 | 21857  | configuration | . open             | 
10:11:34 | 21857  | configuration | . update           | 
10:11:34 | 21857  | configuration | . refresh          | 
10:11:34 | 21857  | configuration | < receive          | 
10:11:34 | 21857  | configuration | > send             | 
10:11:34 | 21857  | configuration | . update           | 
10:11:34 | 21857  | configuration | < send             | 
10:11:34 | 21857  | configuration | < api              | 
10:11:34 | 21857  | configuration | route-refresh requested, enabling adj-rib-out
10:11:34 | 21857  | configuration | < neighbor         | 
10:11:34 | 21857  | reactor       | new peer: neighbor 10.0.2.1 local-ip 10.0.2.2 local-as 2 peer-as 1 router-id 127.0.0.2 family-allowed in-open
10:11:34 | 21857  | reactor       | loaded new configuration successfully
10:11:34 | 21857  | network       | listening for BGP session(s) on 10.0.2.2:179
10:11:34 | 21857  | process       | forked process app
10:11:34 | 21857  | reactor       | initialising connection to peer-1
10:11:34 | 21857  | outgoing-1    | attempting connection to 10.0.2.1:179
10:11:34 | 21857  | outgoing-1    | connection to 10.0.2.1 closed
10:11:34 | 21857  | outgoing-1    | outgoing-1 10.0.2.2-10.0.2.1, closing connection
10:11:34 | 21857  | reactor       | initialising connection to peer-1
10:11:34 | 21857  | outgoing-2    | attempting connection to 10.0.2.1:179
10:11:34 | 21857  | outgoing-2    | connection to 10.0.2.1 closed
10:11:34 | 21857  | outgoing-2    | outgoing-2 10.0.2.2-10.0.2.1, closing connection
10:11:35 | 21857  | reactor       | initialising connection to peer-1
10:11:36 | 21857  | outgoing-3    | attempting connection to 10.0.2.1:179
10:11:36 | 21857  | outgoing-3    | connection to 10.0.2.1 closed
10:11:36 | 21857  | outgoing-3    | outgoing-3 10.0.2.2-10.0.2.1, closing connection
10:11:37 | 21857  | reactor       | async | 98e1b302-b2b6-11e7-b8c2-52540070bba8 | check new connection
10:11:37 | 21857  | network       | connection from 10.0.2.2
10:11:37 | 21857  | network       | accepted connection from incoming-1 10.0.2.1-10.0.2.2
10:11:37 | 21857  | reactor       | initialising connection to peer-1
10:11:37 | 21857  | incoming-1    | sending TCP payload (  53) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0035 0104 0002 00B4 7F00 0002 1802 0601 0400 0100 0102 0202 0002 0246 0002 0641 0400 0000 02
10:11:37 | 21857  | incoming-1    | >> OPEN version=4 asn=2 hold_time=180 router_id=127.0.0.2 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, ASN4(2), Enhanced Route Refresh]
10:11:37 | 21857  | incoming-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0035 01
10:11:37 | 21857  | incoming-1    | received TCP payload (  34) 0400 0100 B47F 0000 0118 0206 0104 0001 0001 0202 0200 0202 4600 0206 4104 0000 0001
10:11:37 | 21857  | incoming-1    | << message of type OPEN
10:11:37 | 21857  | incoming-1    | << OPEN version=4 asn=1 hold_time=180 router_id=127.0.0.1 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, ASN4(1), Enhanced Route Refresh]
10:11:37 | 21857  | ka-incoming-1 | receive-timer 59 second(s) left
10:11:37 | 21857  | incoming-1    | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
10:11:37 | 21857  | incoming-1    | >> KEEPALIVE (OPENCONFIRM)
10:11:37 | 21857  | incoming-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
10:11:37 | 21857  | incoming-1    | << message of type KEEPALIVE
10:11:37 | 21857  | ka-incoming-1 | receive-timer 179 second(s) left
10:11:37 | 21857  | reactor       | connected to peer-1 with incoming-1 10.0.2.1-10.0.2.2
INJECTING ROUTES TO NEIGHBOURS 10.0.2.1
Sleeping 5 seconds
10:11:37 | 21857  | incoming-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 02
10:11:37 | 21857  | incoming-1    | received TCP payload (   4) 0000 0000
10:11:37 | 21857  | incoming-1    | << message of type UPDATE
10:11:37 | 21857  | parser        | parsing UPDATE (   4) 0000 0000
10:11:37 | 21857  | peer-1        | << UPDATE #1
10:11:37 | 21857  | peer-1        |    UPDATE #1 nlri  (   4) eor 1/1 (ipv4 unicast)
10:11:37 | 21857  | incoming-1    | sending TCP payload (  23) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
10:11:37 | 21857  | incoming-1    | >> EOR ipv4 unicast
10:11:37 | 21857  | peer-1        | >> EOR(s)
10:11:37 | 21857  | ka-incoming-1 | send-timer 59 second(s) left
10:11:38 | 21857  | ka-incoming-1 | receive-timer 178 second(s) left
10:11:38 | 21857  | ka-incoming-1 | send-timer 58 second(s) left
10:11:39 | 21857  | ka-incoming-1 | receive-timer 177 second(s) left
10:11:40 | 21857  | ka-incoming-1 | send-timer 57 second(s) left
10:11:40 | 21857  | ka-incoming-1 | receive-timer 176 second(s) left
10:11:40 | 21857  | ka-incoming-1 | send-timer 56 second(s) left
10:11:41 | 21857  | ka-incoming-1 | receive-timer 175 second(s) left
10:11:42 | 21857  | ka-incoming-1 | send-timer 55 second(s) left
done
neighbor 10.0.2.1 announce route-refresh ipv4 unicast
ANNOUNCED ROUTE REFRESH



10:11:42 | 21857  | ka-incoming-1 | receive-timer 174 second(s) left
10:11:42 | 21857  | process       | command from process app : neighbor 10.0.2.1 announce route-refresh ipv4 unicast 
10:11:42 | 21857  | reactor       | async | app | announce route-refresh ipv4 unicast
10:11:42 | 21857  | reactor       | async | app | problem with function
10:11:42 | 21857  | reactor       | async | app | 'list' object has no attribute 'afi'



10:11:42 | 21857  | ka-incoming-1 | send-timer 54 second(s) left
10:11:43 | 21857  | ka-incoming-1 | receive-timer 173 second(s) left
10:11:43 | 21857  | ka-incoming-1 | send-timer 53 second(s) left
10:11:44 | 21857  | ka-incoming-1 | receive-timer 172 second(s) left
10:11:44 | 21857  | ka-incoming-1 | send-timer 52 second(s) left
10:11:45 | 21857  | ka-incoming-1 | receive-timer 171 second(s) left
10:11:45 | 21857  | ka-incoming-1 | send-timer 51 second(s) left
10:11:46 | 21857  | ka-incoming-1 | receive-timer 170 second(s) left
10:11:47 | 21857  | ka-incoming-1 | send-timer 50 second(s) left
10:11:47 | 21857  | ka-incoming-1 | receive-timer 169 second(s) left
10:11:48 | 21857  | ka-incoming-1 | send-timer 49 second(s) left
10:11:48 | 21857  | ka-incoming-1 | receive-timer 168 second(s) left
10:11:48 | 21857  | ka-incoming-1 | send-timer 48 second(s) left
^C10:11:49 | 21857  | reactor       | ^C received
10:11:49 | 21857  | reactor       | performing shutdown
10:11:49 | 21857  | network       | stopped listening on 10.0.2.2:179
10:11:49 | 21857  | process       | terminating process app
10:11:49 | 21857  | incoming-1    | connection to 10.0.2.2 closed
10:11:49 | 21857  | incoming-1    | incoming-1 10.0.2.1-10.0.2.2, closing connection
```

If I remove the patch the sending works fine.

```
10:26:01 | 22148  | ka-incoming-1 | send-timer 57 second(s) left
10:26:02 | 22148  | ka-incoming-1 | receive-timer 176 second(s) left
10:26:02 | 22148  | ka-incoming-1 | send-timer 56 second(s) left
10:26:03 | 22148  | ka-incoming-1 | receive-timer 175 second(s) left
10:26:03 | 22148  | ka-incoming-1 | send-timer 55 second(s) left
done
neighbor 10.0.2.1 announce route-refresh ipv4 unicast
ANNOUNCED ROUTE REFRESH
10:26:04 | 22148  | process       | command from process app : neighbor 10.0.2.1 announce route-refresh ipv4 unicast 
10:26:04 | 22148  | reactor       | async | app | announce route-refresh ipv4 unicast
10:26:04 | 22148  | api           | Sent to neighbor 10.0.2.1 local-ip 10.0.2.2 local-as 2 peer-as 1 router-id 127.0.0.2 family-allowed in-open : route refresh ipv4/0/unicast
10:26:04 | 22148  | process       | responding to app : done
10:26:04 | 22148  | incoming-1    | sending TCP payload (  23) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0500 0100 01
10:26:04 | 22148  | ka-incoming-1 | receive-timer 174 second(s) left
10:26:04 | 22148  | incoming-1    | >> REFRESH REFRESH
10:26:05 | 22148  | ka-incoming-1 | send-timer 54 second(s) left
10:26:05 | 22148  | ka-incoming-1 | receive-timer 173 second(s) left
10:26:06 | 22148  | ka-incoming-1 | send-timer 53 second(s) left
10:26:06 | 22148  | ka-incoming-1 | receive-timer 172 second(s) left
10:26:06 | 22148  | ka-incoming-1 | send-timer 52 second(s) left
10:26:07 | 22148  | ka-incoming-1 | receive-timer 171 second(s) left
10:26:07 | 22148  | ka-incoming-1 | send-timer 51 second(s) left
10:26:08 | 22148  | ka-incoming-1 | receive-timer 170 second(s) left
10:26:09 | 22148  | ka-incoming-1 | send-timer 50 second(s) left
10:26:09 | 22148  | ka-incoming-1 | receive-timer 169 second(s) left
10:26:09 | 22148  | ka-incoming-1 | send-timer 49 second(s) left
```

**Comment by nfz1** [comment]
Here is a stack trace from the above error, hopefully this will help:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/async.py", line 52, in run
    six.next(generator)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/reactor/api/command/announce.py", line 406, in callback
    reactor.configuration.inject_refresh(peers,refresh)
  File "/usr/local/lib/python3.5/dist-packages/exabgp/configuration/configuration.py", line 103, in inject_refresh
    family = (refresh.afi,refresh.safi)
AttributeError: 'list' object has no attribute 'afi'
```

I implemented a quick fix for the error. It may not be a good idea to actually implement the fix this way but I just wanted to see if the route-refresh messages are being received okay.

```
index 95a39a8..db4e603 100644
--- a/lib/exabgp/reactor/api/command/announce.py
+++ b/lib/exabgp/reactor/api/command/announce.py
@@ -403,6 +403,9 @@ def announce_refresh (self, reactor, service, command):
                        yield True
                        return
 
+               if isinstance(refresh, list):
+                       refresh = refresh[0]
                reactor.configuration.inject_refresh(peers,refresh)
                self.log_message("Sent to %s : %s" % (', '.join(peers if peers else []) if peers is not None else 'all peers',refresh.extensive()))
```

The patch you provided seems to fix the route-refresh received message problem. I also noticed another issue. The JSON string for the route-refresh message is invalid. The route-refresh section has strings that are not double quoted.

```
{  
   "exabgp":"4.0.1",
   "time":1508190815.0027232,
   "host":"amp-server",
   "pid":22799,
   "ppid":21514,
   "counter":5,
   "type":"refresh",
   "neighbor":{  
      "address":{  
         "local":"10.0.2.1",
         "peer":"10.0.2.2"
      },
      "asn":{  
         "local":1,
         "peer":2
      },
      "direction":"receive",
      "route-refresh":{  
         "subtype":query,
         "safi":unicast,
         "afi":ipv4
      }
   }
}
```

**Comment by thomas-mangin** [comment]
Sorry I missed this issue for quite a LONG time ... Hopefully all fixed now.
