### ISSUE TITLE
EVPN connection reset on receipt of type-4 nlri

### ISSUE THREAD

**Issue by kvlangenhove** [Exa-Networks/exabgp#739]
##### ISSUE TYPE

 - Bug Report

##### OS

CentOS Linux release 7.3.1611

##### VERSION

```
ExaBGP : master-406238dff43c4e48e02c986fcb325129d5f5ab54
Python : 3.6.2 (default, Jul 18 2017, 22:59:34)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Uname  : Linux steffi.telenet-ops.be 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64
Root   : /home/kvanlang/exabgp
```

##### ENVIRONMENT 

```
Empty
```

##### CONFIGURATION

```
neighbor 10.15.25.1 {
	family {
		l2vpn evpn;
	}
	router-id 192.168.234.189;
	local-address 192.168.234.189;
	local-as 65018;
	peer-as 65018;
	hold-time 180;
}
```

##### SUMMARY

EVPN connection resets with NOTIFICATION (1,0,"b'can not decode update message of type "2"'") on receipt of type-4 route.

##### STEPS TO REPRODUCE

Run with provided configuration towards Juniper QFX with JunOS 15.1X53-D63.9.

##### EXPECTED RESULTS

Exabgp should properly handle type-4 routes.

##### ACTUAL RESULTS

```
23:14:29 | 26696  | parser        | parsing UPDATE (  89) 0000 0055 4001 0100 4002 0040 0504 0000 0064 C010 1003 0C00 0000 0000 0806 0200 0000 0000 1E80 0904 D5E0 FB05 800A 04D5 E0FB 0190 0E00 2200 1946 04D5 E0FB 0500 0417 0001 D5E0 FB05 0000 0000 0000 0000 1E00 0000 20D5 E0FB 05
23:14:29 | 26696  | parser        | withdrawn NLRI none
23:14:29 | 26696  | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
23:14:29 | 26696  | parser        | attribute as-path            flag 0x40 type 0x02 len 0x00
23:14:29 | 26696  | parser        | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
23:14:29 | 26696  | parser        | attribute extended-community flag 0xc0 type 0x10 len 0x10 payload 030C 0000 0000 0008 0602 0000 0000 001E
23:14:29 | 26696  | parser        | attribute originator-id      flag 0x80 type 0x09 len 0x04 payload D5E0 FB05
23:14:29 | 26696  | parser        | attribute cluster-list       flag 0x80 type 0x0a len 0x04 payload D5E0 FB01
23:14:29 | 26696  | parser        | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0x22 payload 0019 4604 D5E0 FB05 0004 1700 01D5 E0FB 0500 0000 0000 0000 001E 0000 0020 D5E0 FB05
23:14:29 | 26696  | parser        | NLRI      l2vpn evpn         without path-information     payload 0417 0001 D5E0 FB05 0000 0000 0000 0000 1E00 0000 20D5 E0FB 05
23:14:29 | 26696  | outgoing-3    | could not decode message "2"
23:14:29 | 26696  | outgoing-3    | slice indices must be integers or None or have an __index__ method
23:14:29 | 26696  | outgoing-3    | Traceback (most recent call last):
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/reactor/protocol.py", line 229, in read_message
23:14:29 | 26696  | outgoing-3    |     message = Message.unpack(msg_id,body,self.negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/message.py", line 188, in unpack
23:14:29 | 26696  | outgoing-3    |     return cls.klass(message).unpack_message(data,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/__init__.py", line 204, in unpack_message
23:14:29 | 26696  | outgoing-3    |     attributes = Attributes.unpack(_attributes,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 292, in unpack
23:14:29 | 26696  | outgoing-3    |     attributes = cls().parse(data,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
23:14:29 | 26696  | outgoing-3    |     return self.parse(left,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
23:14:29 | 26696  | outgoing-3    |     return self.parse(left,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
23:14:29 | 26696  | outgoing-3    |     return self.parse(left,negotiated)
23:14:29 | 26696  | outgoing-3    |   [Previous line repeated 2 more times]
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 370, in parse
23:14:29 | 26696  | outgoing-3    |     decoded = Attribute.unpack(aid,flag,attribute,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/attribute.py", line 282, in unpack
23:14:29 | 26696  | outgoing-3    |     instance = cls.klass(attribute_id,flag).unpack(data,negotiated)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/attribute/mprnlri.py", line 159, in unpack
23:14:29 | 26696  | outgoing-3    |     nlri,left = NLRI.unpack_nlri(afi,safi,data,IN.ANNOUNCED,addpath)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/nlri/nlri.py", line 109, in unpack_nlri
23:14:29 | 26696  | outgoing-3    |     return cls.registered_nlri[key].unpack_nlri(a,s,data,action,addpath)
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/nlri/evpn/nlri.py", line 89, in unpack_nlri
23:14:29 | 26696  | outgoing-3    |     klass = cls.registered_evpn[code].unpack(bgp[2:length+2])
23:14:29 | 26696  | outgoing-3    |   File "/home/kvanlang/exabgp/lib/exabgp/bgp/message/update/nlri/evpn/segment.py", line 98, in unpack
23:14:29 | 26696  | outgoing-3    |     ip = IP.unpack(data[19:19+(iplen/8)])
23:14:29 | 26696  | outgoing-3    | TypeError: slice indices must be integers or None or have an __index__ method
23:14:29 | 26696  | outgoing-3    |
23:14:29 | 26696  | outgoing-3    | sending TCP payload (  62) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003E 0301 0063 616E 206E 6F74 2064 6563 6F64 6520 7570 6461 7465 206D 6573 7361 6765 206F 6620 7479 7065 2022 3222
23:14:29 | 26696  | outgoing-3    | >> NOTIFICATION (1,0,"b'can not decode update message of type "2"'")
23:14:29 | 26696  | outgoing-3    | peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
```

##### IMPORTANCE

Testing only for now.

##### CAUSE / SOLUTION
Python 3 'true division' typo:
```
diff --git a/lib/exabgp/bgp/message/update/nlri/evpn/segment.py b/lib/exabgp/bgp/message/update/nlri/evpn/segment.py
index 5616b30..0028cf1 100644
--- a/lib/exabgp/bgp/message/update/nlri/evpn/segment.py
+++ b/lib/exabgp/bgp/message/update/nlri/evpn/segment.py
@@ -95,8 +95,7 @@ class EthernetSegment (EVPN):

                if iplen not in (32,128):
                        raise Notify(3,5,"IP length field is given as %d in current Segment, expecting 32 (IPv4) or 128 (IPv6) bits" % iplen)
-
-               ip = IP.unpack(data[19:19+(iplen/8)])
+               ip = IP.unpack(data[19:19+(iplen//8)])

                return cls(rd,esi,ip,data)
```

**Comment by thomas-mangin** [comment]
Thank you very much - proposed patch merged :-)
