### ISSUE TITLE
Connection will be crashed when ExaBGP try to log the specific flowspec routes

### ISSUE THREAD

**Issue by fujimoto-s** [Exa-Networks/exabgp#745]
Hi.

##### ISSUE TYPE
 - Bug Report

##### OS
Ubuntu 14.04

##### VERSION

```
# sbin/exabgp --version
ExaBGP : 3.4.21
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
Uname  : #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017
```

##### ENVIRONMENT 

```
# sbin/exabgp --di     

[exabgp.cache]
attributes = false
nexthops = false

[exabgp.daemon]
user = 'root'

[exabgp.log]
configuration = false
destination = '/mnt/exabgpd.log'
```

##### CONFIGURATION
__exabgp.conf__
```
neighbor 172.17.0.2 {
    process announce-routes {
        run /root/shared_volume/log_routes.py;
        receive-routes;
        encoder json;
    }
    router-id 192.168.0.2;
    local-address 172.17.0.3;
    local-as 65000;
    peer-as 65000;
    flow {
        route flow1{
            match {
                destination 10.0.0.0/24;
                source 20.0.0.0/24;
            }
            then {
                discard;
            }
        }
        route flow2{
            match {
                destination 2001::/24/10;
                source 2002::/24/15;
            }
            then {
                discard;
            }
        }
    }
}
```

__log_routes.py__
```
#!/usr/bin/python
import sys

f = open("/tmp/log", "aw")
line = sys.stdin.readline().strip()
while True:
    f.write(line)
    f.write("\n")
    f.flush()
    line = sys.stdin.readline().strip()
f.close()
```

##### SUMMARY
I use ExaBGP and GoBGP.
I want to announce flowspec routes from GoBGP, and make ExaBGP to output the routes to a log file.
However, When I announce a specific route to ExaBGP, the connection will crash and the route won't be output.

##### STEPS TO REPRODUCE
* make the connection established between ExaBGP and GoBGP, and add the following route to GoBGP:
`gobgp global rib -a ipv4-flowspec add match tcp-flags S then rate-limit 9600`
* ExaBGP dumps the following log:
```
********************************************************************************
EXABGP MISBEHAVED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP, as the problem only affects one
peer, we are trying to keep the program running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 3.4.21
Python version : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
System Uname   : #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017
System MaxInt  : 9223372036854775807


peer 172.17.0.2 ASN 65000   

<type 'exceptions.KeyError'>
0
Traceback (most recent call last):
  File "/root/exabgp/lib/exabgp/reactor/peer.py", line 611, in _run
    for action in self._main(direction):
  File "/root/exabgp/lib/exabgp/reactor/peer.py", line 480, in _main
    for message in proto.read_message():
  File "/root/exabgp/lib/exabgp/reactor/protocol.py", line 177, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 270, in closure
    return function(self,*args)
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 306, in message
    self._dispatch[message_id](self,peer,message,header,*body)
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 314, in wrap
    function(*args)
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 333, in _update
    self.write(process,self._encoder[process].update(peer,update,header,body),peer)
  File "/root/exabgp/lib/exabgp/reactor/api/encoding.py", line 340, in update
    'message': '{ %s}' % self._update(update)})),header,body,peer.neighbor.identificator(),self.count(peer),message_type='update')
  File "/root/exabgp/lib/exabgp/reactor/api/encoding.py", line 307, in _update
    m += ', '.join('%s' % nlri.json() for nlri in nlris)
  File "/root/exabgp/lib/exabgp/reactor/api/encoding.py", line 307, in <genexpr>
    m += ', '.join('%s' % nlri.json() for nlri in nlris)
  File "/root/exabgp/lib/exabgp/bgp/message/update/nlri/flow.py", line 594, in json
    return '"flow-%d": %s' % (self.unique,self._json())
  File "/root/exabgp/lib/exabgp/bgp/message/update/nlri/flow.py", line 584, in _json
    s.append('"%s"' % rule)
  File "/root/exabgp/lib/exabgp/bgp/message/update/nlri/flow.py", line 246, in __str__
    return "%s%s" % (self._string[self.operations & (CommonOperator.EOL ^ 0xFF)], self.value)
KeyError: 0

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
```

* FYI, the following route did not cause the problem, and the route is output successfully:
`gobgp global rib -a ipv4-flowspec add match tcp-flags =S then rate-limit 9600`

##### EXPECTED RESULTS
The route is successfully output to the log.

##### ACTUAL RESULTS
The connection was lost and the route was not output.

**Comment by thomas-mangin** [comment]
Hello @fujimoto-s,

Thank you for reporting this issue with ExaBGP. I am trying to not change the 3.4 code much - but I have made sure the missing key(s) are present. Hopefully this address the root cause of the issue.

Sincerely,

Thomas

**Comment by fujimoto-s** [comment]
Thanks! I've confirmed your commit fixes this issue.
I hope this commit will be published in a stable release at an early date.

**Comment by thomas-mangin** [comment]
Thank you - there is a few more issues needing fixing before I can release the next version but all being fine I will have time over the xmas break to release it on this side of 2017.

**Comment by thomas-mangin** [comment]
sorry - I thought about master exabgp-3.4.23 released.
