### ISSUE TITLE
ExaBGP cannot log "not equal" operator in flowspec routes

### ISSUE THREAD

**Issue by fujimoto-s** [Exa-Networks/exabgp#752]
Hi, all.

Thanks for fixing #745, the fix works well.
But I found a further issue.

##### ISSUE TYPE

 - Bug Report

##### OS
Ubuntu 14.04

##### VERSION

```
# exabgp/sbin/exabgp --version
ExaBGP : 3.4.23
Python : 2.7.6 (default, Nov 23 2017, 15:49:48)  [GCC 4.8.4]
Uname  : #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017
```

##### ENVIRONMENT 

```
exabgp/sbin/exabgp --di 

[exabgp.cache]
attributes = false
nexthops = false

[exabgp.daemon]
user = 'root'

[exabgp.log]
configuration = false
destination = '/mnt/exabgpd.log'
```

##### SUMMARY
Same as the previous issue, I want to make ExaBGP to output the flowspec routes announced by GoBGP to a log file.
However, When I announce a specific route including '!=' operator to ExaBGP, the connection crashes and the route won't be output.

##### STEPS TO REPRODUCE

* make the connection established between ExaBGP and GoBGP, and add the following route to GoBGP:
```
gobgp global rib -a ipv4-flowspec add match source-port !=443 then rate-limit 9600
```
* ExaBGP dumps the following log:
```
********************************************************************************
EXABGP MISBEHAVED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP, as the problem only affects one
peer, we are trying to keep the program running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 3.4.23
Python version : 2.7.6 (default, Nov 23 2017, 15:49:48)  [GCC 4.8.4]
System Uname   : #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017
System MaxInt  : 9223372036854775807


peer 172.17.0.2 ASN 65000

<type 'exceptions.KeyError'>
6
Traceback (most recent call last):
  File "/root/exabgp/lib/exabgp/reactor/peer.py", line 611, in _run
    for action in self._main(direction):
  File "/root/exabgp/lib/exabgp/reactor/peer.py", line 480, in _main
    for message in proto.read_message():
  File "/root/exabgp/lib/exabgp/reactor/protocol.py", line 177, in read_message
    self.peer.reactor.processes.message(msg_id,self.peer,message,'','')
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 270, in closure
    return function(self,*args)
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 306, in message
    self._dispatch[message_id](self,peer,message,header,*body)
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 314, in wrap
    function(*args)
  File "/root/exabgp/lib/exabgp/reactor/api/processes.py", line 333, in _update
    self.write(process,self._encoder[process].update(peer,update,header,body),peer)
  File "/root/exabgp/lib/exabgp/reactor/api/encoding.py", line 340, in update
    'message': '{ %s}' % self._update(update)})),header,body,peer.neighbor.identificator(),self.count(peer),message_type='update')
  File "/root/exabgp/lib/exabgp/reactor/api/encoding.py", line 307, in _update
    m += ', '.join('%s' % nlri.json() for nlri in nlris)
  File "/root/exabgp/lib/exabgp/reactor/api/encoding.py", line 307, in <genexpr>
    m += ', '.join('%s' % nlri.json() for nlri in nlris)
  File "/root/exabgp/lib/exabgp/bgp/message/update/nlri/flow.py", line 598, in json
    return '"flow-%d": %s' % (self.unique,self._json())
  File "/root/exabgp/lib/exabgp/bgp/message/update/nlri/flow.py", line 588, in _json
    s.append('"%s"' % rule)
  File "/root/exabgp/lib/exabgp/bgp/message/update/nlri/flow.py", line 234, in __str__
    return "%s%s" % (self._string[self.operations & (CommonOperator.EOL ^ 0xFF)], self.value)
KeyError: 6

********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
```

GoBGP creates numeric operators according to the following table(written in [draft-ietf-idr-rfc5575bis-06](https://tools.ietf.org/html/draft-ietf-idr-rfc5575bis-06#section-4.2.3)):
```
            +----+----+----+----------------------------------+
            | lt | gt | eq | Resulting operation              |
            +----+----+----+----------------------------------+
            | 0  | 0  | 0  | true (independent of the value)  |
            | 0  | 0  | 1  | == (equal)                       |
            | 0  | 1  | 0  | > (greater than)                 |
            | 0  | 1  | 1  | >= (greater than or equal)       |
            | 1  | 0  | 0  | < (less than)                    |
            | 1  | 0  | 1  | <= (less than or equal)          |
            | 1  | 1  | 0  | != (not equal value)             |
            | 1  | 1  | 1  | false (independent of the value) |
            +----+----+----+----------------------------------+
```

Is ExaBGP implemented to decode these?

**Comment by thomas-mangin** [comment]
The code was massively improved with master and it may be best to run ExaBGP 4.0 for what you are trying to achieve but I will fix this problem.

**Comment by thomas-mangin** [comment]
Thank you very much for your help. closing this issue as the patch is in and I assume all is fine, should it not please feel free to let me know.
