### ISSUE TITLE
Invalid 'Rate-limit' and 'Value' in JSON output for extended communities

### ISSUE THREAD

**Issue by pratiklotia** [Exa-Networks/exabgp#753]
ISSUE TYPE
Bug Report

OS
Ubuntu 16.04.5 (Debian/Linux)

VERSION
```
ExaBGP : 4.0.2-1c737d99
Python : 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Uname  : Linux exabgp01 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64
Root   : /opt/exabgp

```

ENVIRONMENT 
```
[exabgp.api]
encoder = text
respawn = false

[exabgp.daemon]
user = 'root'

[exabgp.log]
destination = '/var/log/exabgp.log'
level = DEBUG
routes = true


```

CONFIGURATION

```

process syslog {
        run /usr/bin/python /home/path/to/script.py;
        encoder json;
}


neighbor 192.168.194.100 {
        description "some-description";
        hold-time 180;
        listen 179;
        peer-as 65534;
        router-id 192.168.194.200;
        local-as 65534;
        local-address 192.168.194.200;
    api {
        processes [ syslog ];
        neighbor-changes;
        receive {
            parsed;
            update;
        }
    }

    }

```

SUMMARY
The exabgp is configured to receive messages from a BGP peer in the JSON format. For BGP Update (Flowspec) messages, the JSON contains key-value pair for the key - 'extended-community' containing values like 'rate-limit' and 'value'. Firstly, the rate-limit always shows as '0' in spite of the peer being configured to send a non-zero rate limit. Secondly, the 'value' which contains the decimal representation of the packet has a 'L' appended to end of the integer value. This creates issues when processing the JSON, since a value with a letter is seen as 'string' but results in an error since it does not have 'quotes' around it. For example: "value":  9225340944352543000L

STEPS TO REPRODUCE
Advertise a Flowspec route from a Cisco IOS-XR BGP Speaker and receive route with ExaBGP with encoder set to JSON. The error was seen when the JSON data (read as STDIN & loaded as JSON) is passed to MongoDB instead of a log file. Below is the error:
```

13:38:24 | 8064   | welcome       | Thank you for using ExaBGP
13:38:24 | 8064   | version       | master-9a0ed78936e24097a225b491197f01459e0b95c0
13:38:24 | 8064   | interpreter   | 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
13:38:24 | 8064   | os            | Linux exabgp01 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64
13:38:24 | 8064   | installation  | /opt/exabgp
13:38:24 | 8064   | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
13:38:24 | 8064   | cli           | we scanned the following folders (the number is your PID):
13:38:24 | 8064   | cli control   |  - /run/exabgp/
13:38:24 | 8064   | cli control   |  - /run/0/
13:38:24 | 8064   | cli control   |  - /run/
13:38:24 | 8064   | cli control   |  - /var/run/exabgp/
13:38:24 | 8064   | cli control   |  - /var/run/0/
13:38:24 | 8064   | cli control   |  - /var/run/
13:38:24 | 8064   | cli control   |  - /opt/exabgp/run/exabgp/
13:38:24 | 8064   | cli control   |  - /opt/exabgp/run/0/
13:38:24 | 8064   | cli control   |  - /opt/exabgp/run/
13:38:24 | 8064   | cli control   |  - /opt/exabgp/var/run/exabgp/
13:38:24 | 8064   | cli control   |  - /opt/exabgp/var/run/0/
13:38:24 | 8064   | cli control   |  - /opt/exabgp/var/run/
13:38:24 | 8064   | cli control   | please make them in one of the folder with the following commands:
13:38:24 | 8064   | cli control   | > mkfifo /home/path/to/exabgp/run/exabgp.{in,out}
13:38:24 | 8064   | cli control   | > chmod 600 /home/path/to/exabgp/run/exabgp.{in,out}
13:38:24 | 8064   | configuration | performing reload of exabgp master-9a0ed78936e24097a225b491197f01459e0b95c0
13:38:24 | 8064   | configuration | > process          | 'syslog'
13:38:24 | 8064   | configuration | . run              | '/usr/bin/python' '/home/path/to/script.py'
13:38:24 | 8064   | configuration | . encoder          | 'json'
13:38:24 | 8064   | configuration | < process          |
13:38:24 | 8064   | configuration | > neighbor         | '192.168.194.100'
13:38:24 | 8064   | configuration | . description      | 'some-description'
13:38:24 | 8064   | configuration | . hold-time        | '180'
13:38:24 | 8064   | configuration | . listen           | '179'
13:38:24 | 8064   | configuration | . peer-as          | '65534'
13:38:24 | 8064   | configuration | . router-id        | '192.168.194.200'
13:38:24 | 8064   | configuration | . local-as         | '65534'
13:38:24 | 8064   | configuration | . local-address    | '192.168.194.200'
13:38:24 | 8064   | configuration | > api              |
13:38:24 | 8064   | configuration | . processes        | '[' 'syslog' ']'
13:38:24 | 8064   | configuration | . neighbor-changes |
13:38:24 | 8064   | configuration | > receive          |
13:38:24 | 8064   | configuration | . parsed           |
13:38:24 | 8064   | configuration | . update           |
13:38:24 | 8064   | configuration | < receive          |
13:38:24 | 8064   | configuration | < api              |
13:38:24 | 8064   | configuration | < neighbor         |
13:38:24 | 8064   | reactor       | new peer: neighbor 192.168.194.100 local-ip 192.168.194.200 local-as 65534 peer-as 65534 router-id 192.168.194.200 family-allowed in-open
13:38:24 | 8064   | reactor       | loaded new configuration successfully
13:38:24 | 8064   | network       | listening for BGP session(s) on 192.168.194.200:179
13:38:24 | 8064   | process       | forked process syslog
Traceback (most recent call last):
  File "/home/path/to/script.py", line 107, in <module>
    updates.insert_one(original_peer_message)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 670, in insert_one
    bypass_doc_val=bypass_document_validation),
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 575, in _insert
    check_keys, manipulate, write_concern, op_id, bypass_doc_val)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 556, in _insert_one
    check_keys=check_keys)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 482, in command
    self._raise_connection_failure(error)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 610, in _raise_connection_failure
    raise error
OverflowError: MongoDB can only handle up to 8-byte ints



```

EXPECTED RESULTS
In the 'extended-community' entry: 'rate-limit' should be a non-zero value sent by the BGP peer (5 bps in our case). The 'value' should be an integer value.

ACTUAL RESULTS
Debugged by passing the JSON data to log file. In the 'extended-community' entry: 'rate-limit' is '0' and 'value' is  '9225340944352543000L'. Notice the 'L' appended at the end (perhaps, Long Int).

IMPORTANCE
This neither allows us to log the BGP messages in a DB nor process it further. Also, we cannot the use the rate-limit value to implement a rate-limiting flowspec rule.

**Comment by pratiklotia** [comment]
I just noticed. This issue is **NOT** a bug related to ExaBGP.

I was using the json.loads() function to convert the received JSON to a dictionary so as to insert it in Mongo DB. The json.loads() function is responsible for converting the value to a Long Int and appending the 'L' in the value.
The rate-limit is also received as a non-zero number for bits/sec value of greater than 8 - as ExaBGP converts it into Bytes per second.

The raw JSON received is AS EXPECTED.

Apologies for the oversight.
Please disregard this issue. I am closing the issue but not deleting it as this might be useful to others who might face a similar problem.

**Comment by pratiklotia** [comment]
Upon review, to load the JSON data directly into MongoDB, we had to do the following:

We modified the source code at "/opt/exabgp/lib/exabgp/bgp/message/update/attribute/community/extended/community.py", line number 95 was changed from  "return '{ "value": %ld, "string": "%s" }' % (h,s)" to return '{ "value": %s, "string": "%s" }' % (h,s).

Not sure if this is the recommended way of doing it, please let us know.

**Comment by thomas-mangin** [comment]
Thank you will update the code.

**Comment by thomas-mangin** [comment]
Hello, I can not replicate this issue on my MAC !!
```
Python 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print("%ld" % 0x999999999999999999999999999999999999999999999999999999999999999999999)
72850083458464840159479821505881958999090256464455232046942965365208910695195318681
>>> print("%ld" % 0x9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)
579680628452588751704302783639798101644839099455965249798585287717727871343434063680429064987288386694369542404725326576604761799156448148361436301020062112304547122223513
```

```
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print("%ld" % 0x9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)
579680628452588751704302783639798101644839099455965249798585287717727871343434063680429064987288386694369542404725326576604761799156448148361436301020062112304547122223513
```

but as `%s` make no difference .. changed with fb0349aa

**Comment by james-powis** [comment]
@thomas-mangin I won't disagree, python is not to blame here (by itself), namely the issue comes from MongoDB (https://jira.mongodb.org/browse/PYTHON-186) and its inability to receive integers larger than 8 bytes. Additionally serializing from yaml or json actually demonstrates the part of this issue:

```
16:14  ~/longmongo.py$ python --version
Python 2.7.12
16:14  ~/longmongo.py$ cat test.py 
import json
import yaml


var1 = '{"foo": 111111111111111111111111111111111111111111111111111111111111111111111111111111111111}'
var2 = 'foo: 111111111111111111111111111111111111111111111111111111111111111111111111111111111111'


print(json.loads(var1))
print(yaml.load(var2))
16:14  ~/longmongo.py$ python test.py 
{u'foo': 111111111111111111111111111111111111111111111111111111111111111111111111111111111111L}
{'foo': 111111111111111111111111111111111111111111111111111111111111111111111111111111111111L}
```

With exabgp receiving the payload with long ints in excess of mongodb's capability, there needs to be a streaming conversion int->string:string->int to prevent long munging or encountered exceptions.

I think the best solution to address this issue is when encountering >8Byte ints is to convert them to a string prior to serializing into bson destined for mongodb. This is what @pratiklotia was suggesting in https://github.com/Exa-Networks/exabgp/issues/753#issuecomment-349495562
