### ISSUE TITLE
BGP-LS Decoding

### ISSUE THREAD

**Issue by steiler** [Exa-Networks/exabgp#765]
##### ISSUE TYPE
 - Bug Report

##### OS
Ubuntu Server 16.04.3 LTS (xenial)

##### VERSION
```
ExaBGP : (HEAD-d45ab365d004da00acf71888de23c836c069f21b
Python : 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Uname  : Linux SRC 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64
Root   : /exabgp
```

##### SUMMARY
Exabgp is unable to parse BGP-LS message hence drops the BGP connection.

##### STEPS TO REPRODUCE
Using Junos vMX 17.3R1.10 as BGP peer.
Segment Routing is enabled via isis.
BGP-LS towards ExaBGP is used to export the topology.

##### ACTUAL RESULTS
Truncated logfile as follows:

```
...
exabgp_1      | 09:17:30 | 11     | ka-outgoing-1   | receive-timer 80 second(s) left
exabgp_1      | 09:17:30 | 11     | ka-outgoing-3   | receive-timer 80 second(s) left
exabgp_1      | 09:17:30 | 11     | ka-outgoing-7   | receive-timer 80 second(s) left
exabgp_1      | 09:17:30 | 11     | ka-outgoing-5   | receive-timer 80 second(s) left
exabgp_1      | 09:17:30 | 11     | ka-outgoing-9   | receive-timer 80 second(s) left
exabgp_1      | 09:17:30 | 11     | ka-outgoing-6   | receive-timer 80 second(s) left
exabgp_1      | 09:17:30 | 11     | outgoing-13     | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 008A 02
exabgp_1      | 09:17:30 | 11     | outgoing-13     | received TCP payload ( 119) 0000 0073 4001 0100 4002 0040 0504 0000 0064 801D 3204 0000 0100 0402 0005 436F 7265 3604 0300 0349 0004 0404 0004 0A09 0906
040A 000C C000 0010 0004 8900 030C 3500 040B 0001 0090 0E00 2C40 0447 040A 0909 0300 0001 001F 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 06
exabgp_1      | 09:17:30 | 11     | outgoing-13     | << message of type UPDATE
exabgp_1      | 09:17:30 | 11     | parser          | parsing UPDATE ( 119) 0000 0073 4001 0100 4002 0040 0504 0000 0064 801D 3204 0000 0100 0402 0005 436F 7265 3604 0300 0349 0004 0404 0004 0A09 0906 040A 0
00C C000 0010 0004 8900 030C 3500 040B 0001 0090 0E00 2C40 0447 040A 0909 0300 0001 001F 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 06
exabgp_1      | 09:17:30 | 11     | parser          | withdrawn NLRI none
exabgp_1      | 09:17:30 | 11     | parser          | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
exabgp_1      | 09:17:30 | 11     | parser          | attribute as-path            flag 0x40 type 0x02 len 0x00
exabgp_1      | 09:17:30 | 11     | parser          | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
exabgp_1      | 09:17:30 | 11     | parser          | attribute bgp-ls             flag 0x80 type 0x1d len 0x32 payload 0400 0001 0004 0200 0543 6F72 6536 0403 0003 4900 0404 0400 040A 0909 0604 0A00 0CC0 00
00 1000 0489 0003 0C35 0004 0B00 0100
exabgp_1      | 09:17:30 | 11     | parser          | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0x2c payload 4004 4704 0A09 0903 0000 0100 1F02 0000 0000 0000 0000 0100 0012 0200 0004 0000 FDE8 02
03 0006 1000 0000 0006
exabgp_1      | 09:17:30 | 11     | parser          | NLRI      bgp-ls bgp-ls      without path-information     payload 0001 001F 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 06
exabgp_1      | 09:17:30 | 11     | parser          | announced NLRI none
exabgp_1      | 09:17:30 | 11     | peer-1          | << UPDATE #4
exabgp_1      | 09:17:30 | 11     | peer-1          |    UPDATE #4 nlri  (   2) { "ls-nlri-type": 1, "l3-routing-topology": 0, "protocol-id": 2, "node-descriptors": { "autonomous-system": 65000, "router-id":
 "100000000006" }, "nexthop": "10.9.9.3" }
exabgp_1      | 09:17:30 | 11     | outgoing-13     | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 008A 02
exabgp_1      | 09:17:30 | 11     | outgoing-13     | received TCP payload ( 119) 0000 0073 4001 0100 4002 0040 0504 0000 0064 801D 3204 0000 0100 0402 0005 436F 7265 3204 0300 0349 0004 0404 0004 0A09 0902
040A 000C C000 0010 0004 8900 030C 3500 040B 0001 0090 0E00 2C40 0447 040A 0909 0300 0001 001F 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 02
exabgp_1      | 09:17:30 | 11     | outgoing-13     | << message of type UPDATE
exabgp_1      | 09:17:30 | 11     | parser          | parsing UPDATE ( 119) 0000 0073 4001 0100 4002 0040 0504 0000 0064 801D 3204 0000 0100 0402 0005 436F 7265 3204 0300 0349 0004 0404 0004 0A09 0902 040A 0
00C C000 0010 0004 8900 030C 3500 040B 0001 0090 0E00 2C40 0447 040A 0909 0300 0001 001F 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 02
exabgp_1      | 09:17:30 | 11     | parser          | withdrawn NLRI none
exabgp_1      | 09:17:30 | 11     | parser          | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
exabgp_1      | 09:17:30 | 11     | parser          | attribute as-path            flag 0x40 type 0x02 len 0x00
exabgp_1      | 09:17:30 | 11     | parser          | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
exabgp_1      | 09:17:30 | 11     | parser          | attribute bgp-ls             flag 0x80 type 0x1d len 0x32 payload 0400 0001 0004 0200 0543 6F72 6532 0403 0003 4900 0404 0400 040A 0909 0204 0A00 0CC0 00
00 1000 0489 0003 0C35 0004 0B00 0100
exabgp_1      | 09:17:30 | 11     | parser          | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0x2c payload 4004 4704 0A09 0903 0000 0100 1F02 0000 0000 0000 0000 0100 0012 0200 0004 0000 FDE8 02
03 0006 1000 0000 0002
exabgp_1      | 09:17:30 | 11     | parser          | NLRI      bgp-ls bgp-ls      without path-information     payload 0001 001F 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 02
exabgp_1      | 09:17:30 | 11     | parser          | announced NLRI none
exabgp_1      | 09:17:30 | 11     | peer-1          | << UPDATE #5
exabgp_1      | 09:17:30 | 11     | peer-1          |    UPDATE #5 nlri  (   2) { "ls-nlri-type": 1, "l3-routing-topology": 0, "protocol-id": 2, "node-descriptors": { "autonomous-system": 65000, "router-id":
 "100000000002" }, "nexthop": "10.9.9.3" }
exabgp_1      | 09:17:30 | 11     | outgoing-13     | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 006D 02
exabgp_1      | 09:17:30 | 11     | outgoing-13     | received TCP payload (  90) 0000 0056 4001 0100 4002 0040 0504 0000 0064 801D 0C04 8600 0840 0000 0000 0000 BE90 0E00 3540 0447 040A 0909 0300 0003 0028 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 0901 0900 0520 0A09 0909
exabgp_1      | 09:17:30 | 11     | outgoing-13     | << message of type UPDATE
exabgp_1      | 09:17:30 | 11     | parser          | parsing UPDATE (  90) 0000 0056 4001 0100 4002 0040 0504 0000 0064 801D 0C04 8600 0840 0000 0000 0000 BE90 0E00 3540 0447 040A 0909 0300 0003 0028 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 0901 0900 0520 0A09 0909
exabgp_1      | 09:17:30 | 11     | parser          | withdrawn NLRI none
exabgp_1      | 09:17:30 | 11     | outgoing-13     | << message of type UPDATE
exabgp_1      | 09:17:30 | 11     | parser          | parsing UPDATE (  90) 0000 0056 4001 0100 4002 0040 0504 0000 0064 801D 0C04 8600 0840 0000 0000 0000 BE90 0E00 3540 0447 040A 0909 0300 0003 0028 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 0901 0900 0520 0A09 0909
exabgp_1      | 09:17:30 | 11     | parser          | withdrawn NLRI none
exabgp_1      | 09:17:30 | 11     | parser          | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
exabgp_1      | 09:17:30 | 11     | parser          | attribute as-path            flag 0x40 type 0x02 len 0x00
exabgp_1      | 09:17:30 | 11     | parser          | attribute local-preference   flag 0x40 type 0x05 len 0x04 payload 0000 0064
exabgp_1      | 09:17:30 | 11     | parser          | attribute bgp-ls             flag 0x80 type 0x1d len 0x0c payload 0486 0008 4000 0000 0000 00BE
exabgp_1      | 09:17:30 | 11     | parser          | attribute mp-reach-nlri      flag 0x90 type 0x0e len 0x35 payload 4004 4704 0A09 0903 0000 0300 2802 0000 0000 0000 0000 0100 0012 0200 0004 0000 FDE8 0203 0006 1000 0000 0009 0109 0005 200A 0909 09
exabgp_1      | 09:17:30 | 11     | parser          | NLRI      bgp-ls bgp-ls      without path-information     payload 0003 0028 0200 0000 0000 0000 0001 0000 1202 0000 0400 00FD E802 0300 0610 0000 0000 0901 0900 0520 0A09 0909
exabgp_1      | 09:17:30 | 11     | outgoing-13     | could not decode message "2"
exabgp_1      | 09:17:30 | 11     | outgoing-13     | sequence item 0: expected a bytes-like object, str found
exabgp_1      | 09:17:30 | 11     | outgoing-13     | Traceback (most recent call last):
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/reactor/protocol.py", line 229, in read_message
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     message = Message.unpack(msg_id,body,self.negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/message.py", line 188, in unpack
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     return cls.klass(message).unpack_message(data,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/__init__.py", line 204, in unpack_message
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     attributes = Attributes.unpack(_attributes,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 292, in unpack
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     attributes = cls().parse(data,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     return self.parse(left,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     return self.parse(left,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     return self.parse(left,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 384, in parse
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     return self.parse(left,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attributes.py", line 370, in parse
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     decoded = Attribute.unpack(aid,flag,attribute,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/attribute.py", line 282, in unpack
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     instance = cls.klass(attribute_id,flag).unpack(data,negotiated)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/attribute/mprnlri.py", line 159, in unpack
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     nlri,left = NLRI.unpack_nlri(afi,safi,data,IN.ANNOUNCED,addpath)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/nlri/nlri.py", line 109, in unpack_nlri
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     return cls.registered_nlri[key].unpack_nlri(a,s,data,action,addpath)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/nlri/bgpls/nlri.py", line 120, in unpack_nlri
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     klass = cls.registered_bgpls[code].unpack_nlri(bgp[4:length+4],rd)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/nlri/bgpls/prefixv4.py", line 85, in unpack_nlri
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     prefix = IpReach.unpack(values)
exabgp_1      | 09:17:30 | 11     | outgoing-13     |   File "/exabgp/lib/exabgp/bgp/message/update/nlri/bgpls/tlvs/ipreach.py", line 62, in unpack
exabgp_1      | 09:17:30 | 11     | outgoing-13     |     prefix = b".".join(prefix_list)
exabgp_1      | 09:17:30 | 11     | outgoing-13     | TypeError: sequence item 0: expected a bytes-like object, str found
exabgp_1      | 09:17:30 | 11     | outgoing-13     |
exabgp_1      | 09:17:30 | 11     | outgoing-13     | sending TCP payload (  62) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 003E 0301 0063 616E 206E 6F74 2064 6563 6F64 6520 7570 6461 7465 206D 6573 7361 6765 206F 6620 7479 7065 2022 3222
exabgp_1      | 09:17:30 | 11     | outgoing-13     | >> NOTIFICATION (1,0,"b'can not decode update message of type "2"'")
exabgp_1      | 09:17:30 | 11     | outgoing-13     | peer reset, message [notification sent (1,0)] error[Message header error / Unspecific / can not decode update message of type "2"]
exabgp_1      | 09:17:30 | 11     | outgoing-13     | outgoing-13 172.24.100.80-10.9.9.3, closing connection
```

**Comment by ruissalo** [comment]
@steiler This issue was resolved in master. Can you update your branch? You seem to be a few commits behind.

`{
  "exabgp": "4.0.1",
  "time": 1514576574.9619,
  "host": "ruissalo",
  "pid": 28751,
  "ppid": 98485,
  "counter": 1,
  "type": "update",
  "neighbor": {
    "address": {
      "local": "172.24.182.21",
      "peer": "10.113.63.241"
    },
    "asn": {
      "local": 4804,
      "peer": 65533
    },
    "direction": "in",
    "message": {
      "update": {
        "attribute": {
          "origin": "igp",
          "local-preference": 100,
          "bgp-ls": {
            "sr-prefix-flags": {
              "R": 0,
              "N": 1,
              "P": 0,
              "E": 0,
              "V": 0,
              "L": 0,
              "RSV": 0
            },
            "sids": [
              190
            ],
            "sr-algorithm": 0
          }
        },
        "announce": {
          "bgp-ls bgp-ls": {
            "10.9.9.3": [
              {
                "ls-nlri-type": 3,
                "l3-routing-topology": 0,
                "protocol-id": 2,
                "node-descriptors": {
                  "autonomous-system": 65000,
                  "router-id": "100000000009"
                },
                "ip-reachability-tlv": "10.9.9.9",
                "nexthop": "10.9.9.3"
              }
            ]
          }
        }
      }
    }
  }
}`

**Comment by steiler** [comment]
Was jumping between versions. Thought I had tested it with latest master. My bad!
Sorry and thanks for pointing it out!
