### ISSUE TITLE
exabgp cli is broken

### ISSUE THREAD

**Issue by fser** [Exa-Networks/exabgp#773]
##### ISSUE TYPE

 - Bug Report

##### OS

Debian GNU/Linux 9

##### VERSION

```
ExaBGP : 4.0.2-1c737d99
Python : 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
Uname  : Linux exa2 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
Root   : /usr/local
```

##### ENVIRONMENT 

```
empty output
```

##### SUMMARY

I'm trying to run the cli using the following: `exabgp -d --run cli  'show version'` and I get:

```
********************************************************************************
EXABGP CRASHED / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP and we could not keep the program
running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 4.0.2-1c737d99
Python version : 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]
System Uname   : #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
System MaxInt  : 9223372036854775807


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgp", line 11, in <module>
    sys.exit(run_exabgp())
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/bgp.py", line 134, in main
    run_cli()
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/__init__.py", line 28, in run_cli
    main()
  File "/usr/local/lib/python3.5/dist-packages/exabgp/application/cli.py", line 95, in main
    os.write(writer,command + '\n')
TypeError: a bytes-like object is required, not 'str'


-- Configuration





-- Logging History







********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

```

##### STEPS TO REPRODUCE

Install exabgp using pip, and run `exabgp --run cli`.

```
     - name: install python modules
       pip: name={{ item }} executable=pip3
       when: pip_present|bool == False
       with_items:
         - exabgp
         ...
```

##### EXPECTED RESULTS

have an output from cli
##### ACTUAL RESULTS

I get an error message
##### IMPORTANCE

It's kind of blocking while experimenting..

**Comment by thomas-mangin** [comment]
This is already fixed on master and need to be released.
