### ISSUE TITLE
Bailing out during import of full table

### ISSUE THREAD

**Issue by jlixfeld** [Exa-Networks/exabgp#792]
##### ISSUE TYPE

 - Bug Report

##### OS

```
root@pgen:/usr/local/var/run/exabgp# cat /etc/debian_version
8.8
root@pgen:/usr/local/var/run/exabgp#
```

##### VERSION

```
root@pgen:/usr/local/var/run/exabgp# exabgp --version
ExaBGP : 4.0.5-67a808ae
Python : 2.7.9 (default, Jun 29 2016, 13:08:31)  [GCC 4.9.2]
Uname  : Linux pgen 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64
Root   : /usr/local
root@pgen:/usr/local/var/run/exabgp#
```

##### ENVIRONMENT 

```
root@pgen:/usr/local/var/run/exabgp# exabgp --di

[exabgp.api]
ack = false

[exabgp.log]
all = true
parser = true
root@pgen:/usr/local/var/run/exabgp#
```

##### CONFIGURATION
```
process cogent {
	run /home/jlixfeld/mrtparse/examples/mrt2exabgp.py -l 174 -p 21949 -L 38.104.158.173 -n 38.104.158.174 -4 38.104.158.173 -A /home/jlixfeld/latest-bview.gz;
	encoder json;
}
process ntt {
	run /home/jlixfeld/mrtparse/examples/mrt2exabgp.py -l 2914 -p 21949 -L 168.143.229.149 -n 168.143.229.150 -4 168.143.229.149 -A /home/jlixfeld/latest-bview.gz;
	encoder json;
}

neighbor 38.104.158.174 {
	router-id 38.104.158.173;
        local-address 38.104.158.173;
        local-as 174;
        peer-as 21949;
	capability {
        	graceful-restart;
	}
        api {
		processes [ cogent ];
        }
}
neighbor 168.143.229.150 {
        router-id 168.143.229.149;
        local-address 168.143.229.149;
        local-as 2914;
        peer-as 21949;
	capability {
        	graceful-restart;
	}
        api {
		processes [ cogent ];
        }
}
```

##### SUMMARY
Throughout the ```process```, logs throw CRC errors for certain prefixes.  Eventually it dies.

##### STEPS TO REPRODUCE
```exabgp exabgp_api.conf```

##### ACTUAL RESULTS
```
...
...
...
...
13:59:07 | 13801  | api           | route added to neighbor 38.104.158.174 local-ip 38.104.158.173 local-as 174 peer-as 21949 router-id 38.104.158.173 family-allowed in-open, neighbor 168.143.229.150 local-ip 168.143.229.149 local-as 2914 peer-as 21949 router-id 168.143.229.149 family-allowed in-open : 5.119.64.0/20 next-hop 38.104.158.173 origin igp as-path [ 45896 3356 200612 48159 48159 48159 44244 ] community [ 0:0 3356:2 3356:22 3356:100 3356:123 3356:500 3356:2106 20061:7 ]
Traceback (most recent call last):
  File "/home/jlixfeld/mrtparse/examples/mrt2exabgp.py", line 498, in <module>
    main()
  File "/home/jlixfeld/mrtparse/examples/mrt2exabgp.py", line 495, in main
    conv_format(args, flags, d)
  File "/home/jlixfeld/mrtparse/examples/mrt2exabgp.py", line 191, in conv_format
    for m in d:
  File "/usr/local/lib/python2.7/dist-packages/mrtparse-1.6-py2.7.egg/mrtparse/__init__.py", line 609, in __next__
    self.unpack_data()
  File "/usr/local/lib/python2.7/dist-packages/mrtparse-1.6-py2.7.egg/mrtparse/__init__.py", line 640, in unpack_data
    data = self.f.read(self.mrt.len)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x579c0579 != 0xd1fd5a7dL
13:59:07 | 13801  | api           | route added to neighbor 38.104.158.174 local-ip 38.104.158.173 local-as 174 peer-as 21949 router-id 38.104.158.173 family-allowed in-open, neighbor 168.143.229.150 local-ip 168.143.229.149 local-as 2914 peer-as 21949 router-id 168.143.229.149 family-allowed in-open : 5.127.48.0/20 next-hop 168.143.229.149 origin igp as-path [ 45896 6939 15412 48159 48159 48159 48159 44244 ] community 19996:2001
13:59:07 | 13801  | api           | route added to neighbor 38.104.158.174 local-ip 38.104.158.173 local-as 174 peer-as 21949 router-id 38.104.158.173 family-allowed in-open, neighbor 168.143.229.150 local-ip 168.143.229.149 local-as 2914 peer-as 21949 router-id 168.143.229.149 family-allowed in-open : 5.119.80.0/20 next-hop 38.104.158.173 origin igp as-path [ 45896 3356 200612 48159 48159 48159 44244 ] community [ 0:0 3356:2 3356:22 3356:100 3356:123 3356:500 3356:2106 20061:7 ]
13:59:07 | 13801  | api           | route added to neighbor 38.104.158.174 local-ip 38.104.158.173 local-as 174 peer-as 21949 router-id 38.104.158.173 family-allowed in-open, neighbor 168.143.229.150 local-ip 168.143.229.149 local-as 2914 peer-as 21949 router-id 168.143.229.149 family-allowed in-open : 5.119.96.0/20 next-hop 38.104.158.173 origin igp as-path [ 45896 3356 200612 48159 48159 48159 44244 ] community [ 0:0 3356:2 3356:22 3356:100 3356:123 3356:500 3356:2106 20061:7 ]
13:59:07 | 13801  | process       | Too many death for ntt (5) terminating program
13:59:07 | 13801  | reactor       | Problem when sending message(s) to helper program, stopping
13:59:07 | 13801  | reactor       | performing shutdown
root@pgen:/usr/local/etc/exabgp# exabgp exabgp_api.conf
```

**Comment by thomas-mangin** [comment]
There is no CRC in BGP itself. Please open this issue with mrtparse. Could it be a python2 / python3 issue with the interpreter not being explicit ?

**Comment by jlixfeld** [comment]
Thanks.

It looks like it was some data corruption in the latest-bview.gz.
