### ISSUE TITLE
exabgp will tear down it's peer when updating flow route with action redirect

### ISSUE THREAD

**Issue by jasonsdn** [Exa-Networks/exabgp#793]
##### ISSUE TYPE

 - Bug Report
 
##### VERSION

```
lab@ubuntu-120:~/exabgp$ exabgp --version
ExaBGP : 4.0.2-1c737d99
Python : 2.7.6 (default, Nov 23 2017, 15:49:48)  [GCC 4.8.4]
Uname  : Linux ubuntu-120 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
Root   : /usr/local
lab@ubuntu-120:~/exabgp$ 

```

##### ENVIRONMENT 

```
11:53:27 | 2895   | welcome         | Thank you for using ExaBGP
11:53:27 | 2895   | version         | 4.0.2-1c737d99
11:53:27 | 2895   | interpreter     | 2.7.6 (default, Nov 23 2017, 15:49:48)  [GCC 4.8.4]
11:53:27 | 2895   | os              | Linux ubuntu-120 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
11:53:27 | 2895   | installation    | /usr/local
11:53:27 | 2895   | advice          | environment file missing
11:53:27 | 2895   | advice          | generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"
11:53:27 | 2895   | cli             | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
11:53:27 | 2895   | cli             | we scanned the following folders (the number is your PID):
11:53:27 | 2895   | cli control     |  - /run/1000/
11:53:27 | 2895   | cli control     |  - /run/
11:53:27 | 2895   | cli control     |  - /var/run/1000/
11:53:27 | 2895   | cli control     |  - /var/run/
11:53:27 | 2895   | cli control     |  - /usr/local/run/1000/
11:53:27 | 2895   | cli control     |  - /usr/local/run/
11:53:27 | 2895   | cli control     |  - /usr/local/var/run/1000/
11:53:27 | 2895   | cli control     |  - /usr/local/var/run/
11:53:27 | 2895   | cli control     | please make them in one of the folder with the following commands:
11:53:27 | 2895   | cli control     | > mkfifo /home/lab/exabgp/run/exabgp.{in,out}
11:53:27 | 2895   | cli control     | > chmod 600 /home/lab/exabgp/run/exabgp.{in,out}
11:53:27 | 2895   | cli control     | > chown 1000:1000 /home/lab/exabgp/run/exabgp.{in,out}
11:53:27 | 2895   | configuration   | performing reload of exabgp 4.0.2-1c737d99
11:53:27 | 2895   | configuration   | > neighbor         | '172.27.10.202'
11:53:27 | 2895   | configuration   | . router-id        | '172.27.10.120'
11:53:27 | 2895   | configuration   | . local-address    | '172.27.10.120'
11:53:27 | 2895   | configuration   | . local-as         | '1'
11:53:27 | 2895   | configuration   | . peer-as          | '1'
11:53:27 | 2895   | configuration   | . hold-time        | '60'
11:53:27 | 2895   | configuration   | . group-updates    | 
11:53:27 | 2895   | configuration   | > family           | 
11:53:27 | 2895   | configuration   | . ipv4             | 'unicast'
11:53:27 | 2895   | configuration   | . ipv4             | 'nlri-mpls'
11:53:27 | 2895   | configuration   | . ipv4             | 'flow'
11:53:27 | 2895   | configuration   | < family           | 
11:53:27 | 2895   | configuration   | > capability       | 
11:53:27 | 2895   | configuration   | . graceful-restart | 
11:53:27 | 2895   | configuration   | . route-refresh    | 'enable'
11:53:27 | 2895   | configuration   | < capability       | 
11:53:27 | 2895   | configuration   | route-refresh requested, enabling adj-rib-out
11:53:27 | 2895   | configuration   | < neighbor         | 
11:53:27 | 2895   | configuration   | > neighbor         | '172.27.10.77'
11:53:27 | 2895   | configuration   | . router-id        | '172.27.10.120'
11:53:27 | 2895   | configuration   | . local-address    | '172.27.10.120'
11:53:27 | 2895   | configuration   | . local-as         | '1'
11:53:27 | 2895   | configuration   | . peer-as          | '1'
11:53:27 | 2895   | configuration   | . hold-time        | '60'
11:53:27 | 2895   | configuration   | > family           | 
11:53:27 | 2895   | configuration   | . ipv4             | 'unicast'
11:53:27 | 2895   | configuration   | . ipv4             | 'flow'
11:53:27 | 2895   | configuration   | < family           | 
11:53:27 | 2895   | configuration   | route-refresh requested, enabling adj-rib-out
11:53:27 | 2895   | configuration   | < neighbor         | 
11:53:27 | 2895   | configuration   | > process          | 'abc'
11:53:27 | 2895   | configuration   | . run              | 'python' '/home/lab/exabgp/http-api.py'
11:53:27 | 2895   | configuration   | . encoder          | 'json'
11:53:27 | 2895   | configuration   | < process          | 
11:53:27 | 2895   | reactor         | new peer: neighbor 172.27.10.202 local-ip 172.27.10.120 local-as 1 peer-as 1 router-id 172.27.10.120 family-allowed in-open
11:53:27 | 2895   | reactor         | new peer: neighbor 172.27.10.77 local-ip 172.27.10.120 local-as 1 peer-as 1 router-id 172.27.10.120 family-allowed in-open
11:53:27 | 2895   | reactor         | loaded new configuration successfully
11:53:27 | 2895   | process         | forked process abc
11:53:27 | 2895   | reactor         | initialising connection to peer-1
11:53:27 | 2895   | reactor         | initialising connection to peer-2
11:53:27 | 2895   | outgoing-1      | attempting connection to 172.27.10.202:179
11:53:27 | 2895   | outgoing-2      | attempting connection to 172.27.10.77:179
11:53:27 | 2895   | outgoing-1      | sending TCP payload (  87) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0057 0104 0001 003C AC1B 0A78 3A02 1040 0E80 3C00 0185 8000 0101 8000 0104 8002 0601 0400 0100 0102 0601 0400 0100 0402 0601 0400 0100 8502 0202 0002 0246 0002 0641 0400 0000 01
11:53:27 | 2895   | outgoing-2      | sending TCP payload (  87) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0057 0104 0001 003C AC1B 0A78 3A02 1040 0E80 3C00 0185 8000 0101 8000 0104 8002 0601 0400 0100 0102 0601 0400 0100 0402 0601 0400 0100 8502 0202 0002 0246 0002 0641 0400 0000 01
11:53:27 | 2895   | outgoing-1      | >> OPEN version=4 asn=1 hold_time=60 router_id=172.27.10.120 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), Route Refresh, Graceful Restart Flags 0x8 Time 60 ipv4/flow=0x80 ipv4/unicast=0x80 ipv4/nlri-mpls=0x80, ASN4(1), Enhanced Route Refresh]
11:53:27 | 2895   | outgoing-1      | receive-timer 59 second(s) left
11:53:27 | 2895   | outgoing-2      | >> OPEN version=4 asn=1 hold_time=60 router_id=172.27.10.120 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), Route Refresh, Graceful Restart Flags 0x8 Time 60 ipv4/flow=0x80 ipv4/unicast=0x80 ipv4/nlri-mpls=0x80, ASN4(1), Enhanced Route Refresh]
11:53:27 | 2895   | outgoing-2      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0043 01
11:53:27 | 2895   | outgoing-2      | received TCP payload (  48) 0400 0100 3C64 6464 0226 0206 0104 0001 0004 0206 0104 0001 0085 0202 8000 0202 0200 0204 4002 0078 0206 4104 0000 0001
11:53:27 | 2895   | outgoing-2      | << message of type OPEN
11:53:27 | 2895   | outgoing-2      | << OPEN version=4 asn=1 hold_time=60 router_id=100.100.100.2 capabilities=[Multiprotocol(ipv4 nlri-mpls,ipv4 flow), Route Refresh, Graceful Restart Flags 0x0 Time 120 , ASN4(1), Route Refresh]
11:53:27 | 2895   | outgoing-2      | receive-timer 59 second(s) left
11:53:27 | 2895   | outgoing-2      | --------------------------------------------------------------------
11:53:27 | 2895   | outgoing-2      | the connection can not carry the following family/families
11:53:27 | 2895   | outgoing-2      |  - peer is not configured for ipv4/unicast
11:53:27 | 2895   | outgoing-2      | therefore no routes of this kind can be announced on the connection
11:53:27 | 2895   | outgoing-2      | --------------------------------------------------------------------
11:53:27 | 2895   | outgoing-2      | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:27 | 2895   | process         | command from process abc : serving at port 5001 
11:53:27 | 2895   | process         | responding to abc : error
11:53:27 | 2895   | api             | command from process not understood : serving at port 5001
11:53:27 | 2895   | outgoing-1      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0057 01
11:53:27 | 2895   | outgoing-1      | received TCP payload (  68) 0400 0100 3C64 6464 013A 0206 0104 0001 0080 0206 0104 0001 0081 0206 0104 0001 0004 0206 0104 0001 0085 0202 8000 0202 0200 0204 4002 4078 0206 4104 0000 0001 0202 4700
11:53:27 | 2895   | outgoing-1      | << message of type OPEN
11:53:27 | 2895   | outgoing-1      | << OPEN version=4 asn=1 hold_time=60 router_id=100.100.100.1 capabilities=[Multiprotocol(ipv4 mpls-vpn,ipv4 unknown safi 129,ipv4 nlri-mpls,ipv4 flow), Route Refresh, Graceful Restart Flags 0x4 Time 120 , ASN4(1), Unassigned 71, Route Refresh]
11:53:27 | 2895   | outgoing-1      | --------------------------------------------------------------------
11:53:27 | 2895   | outgoing-1      | the connection can not carry the following family/families
11:53:27 | 2895   | outgoing-1      |  - exabgp is not configured for ipv4/mpls-vpn
11:53:27 | 2895   | outgoing-1      |  - exabgp is not configured for ipv4/unknown safi 129
11:53:27 | 2895   | outgoing-1      |  - peer is not configured for ipv4/unicast
11:53:27 | 2895   | outgoing-1      | therefore no routes of this kind can be announced on the connection
11:53:27 | 2895   | outgoing-1      | --------------------------------------------------------------------
11:53:27 | 2895   | outgoing-1      | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:27 | 2895   | outgoing-2      | >> KEEPALIVE (OPENCONFIRM)
11:53:27 | 2895   | outgoing-1      | >> KEEPALIVE (OPENCONFIRM)
11:53:27 | 2895   | outgoing-2      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:27 | 2895   | outgoing-2      | << message of type KEEPALIVE
11:53:27 | 2895   | outgoing-2      | receive-timer 59 second(s) left
11:53:27 | 2895   | outgoing-1      | receive-timer 59 second(s) left
11:53:27 | 2895   | reactor         | connected to peer-2 with outgoing-2 172.27.10.120-172.27.10.77
11:53:27 | 2895   | outgoing-2      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:27 | 2895   | outgoing-2      | << message of type KEEPALIVE
11:53:27 | 2895   | outgoing-2      | send-timer 20 second(s) left
11:53:27 | 2895   | outgoing-2      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 02
11:53:27 | 2895   | outgoing-2      | received TCP payload (  11) 0000 0007 900F 0003 0001 04
11:53:27 | 2895   | outgoing-2      | << message of type UPDATE
11:53:27 | 2895   | parser          | parsing UPDATE (  11) 0000 0007 900F 0003 0001 04
11:53:27 | 2895   | peer-2          | << UPDATE #1
11:53:27 | 2895   | peer-2          |    UPDATE #1 nlri  (  11) eor 1/4 (ipv4 nlri-mpls)
11:53:27 | 2895   | outgoing-2      | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0104
11:53:27 | 2895   | outgoing-2      | >> EOR ipv4 nlri-mpls
11:53:27 | 2895   | outgoing-2      | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0185
11:53:27 | 2895   | outgoing-2      | >> EOR ipv4 flow
11:53:27 | 2895   | peer-2          | >> EOR(s)
11:53:27 | 2895   | outgoing-2      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 02
11:53:27 | 2895   | outgoing-2      | received TCP payload (  11) 0000 0007 900F 0003 0001 85
11:53:27 | 2895   | outgoing-2      | << message of type UPDATE
11:53:27 | 2895   | parser          | parsing UPDATE (  11) 0000 0007 900F 0003 0001 85
11:53:27 | 2895   | peer-2          | << UPDATE #2
11:53:27 | 2895   | peer-2          |    UPDATE #2 nlri  (  11) eor 1/133 (ipv4 flow)
11:53:27 | 2895   | outgoing-1      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:27 | 2895   | outgoing-1      | << message of type KEEPALIVE
11:53:27 | 2895   | reactor         | connected to peer-1 with outgoing-1 172.27.10.120-172.27.10.202
11:53:27 | 2895   | outgoing-1      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 02
11:53:27 | 2895   | outgoing-1      | received TCP payload (  11) 0000 0007 900F 0003 0001 04
11:53:27 | 2895   | outgoing-1      | << message of type UPDATE
11:53:27 | 2895   | parser          | parsing UPDATE (  11) 0000 0007 900F 0003 0001 04
11:53:27 | 2895   | outgoing-1      | send-timer 20 second(s) left
11:53:27 | 2895   | peer-1          | << UPDATE #1
11:53:27 | 2895   | peer-1          |    UPDATE #1 nlri  (  11) eor 1/4 (ipv4 nlri-mpls)
11:53:27 | 2895   | outgoing-1      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 02
11:53:27 | 2895   | outgoing-1      | received TCP payload (  11) 0000 0007 900F 0003 0001 85
11:53:27 | 2895   | outgoing-1      | << message of type UPDATE
11:53:27 | 2895   | parser          | parsing UPDATE (  11) 0000 0007 900F 0003 0001 85
11:53:27 | 2895   | peer-1          | << UPDATE #2
11:53:27 | 2895   | peer-1          |    UPDATE #2 nlri  (  11) eor 1/133 (ipv4 flow)
11:53:27 | 2895   | outgoing-1      | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0104
11:53:27 | 2895   | outgoing-1      | >> EOR ipv4 nlri-mpls
11:53:27 | 2895   | outgoing-1      | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0185
11:53:27 | 2895   | outgoing-1      | >> EOR ipv4 flow
11:53:27 | 2895   | peer-1          | >> EOR(s)
11:53:28 | 2895   | outgoing-1      | send-timer 19 second(s) left
11:53:28 | 2895   | outgoing-2      | send-timer 19 second(s) left
11:53:28 | 2895   | outgoing-2      | receive-timer 58 second(s) left
11:53:28 | 2895   | outgoing-1      | receive-timer 58 second(s) left
11:53:29 | 2895   | outgoing-1      | send-timer 18 second(s) left
11:53:29 | 2895   | outgoing-2      | send-timer 18 second(s) left
11:53:29 | 2895   | outgoing-2      | receive-timer 57 second(s) left
11:53:29 | 2895   | outgoing-1      | receive-timer 57 second(s) left
11:53:30 | 2895   | outgoing-1      | send-timer 17 second(s) left
11:53:30 | 2895   | outgoing-2      | send-timer 17 second(s) left
11:53:30 | 2895   | outgoing-2      | receive-timer 56 second(s) left
11:53:30 | 2895   | outgoing-1      | receive-timer 56 second(s) left
11:53:31 | 2895   | outgoing-1      | send-timer 16 second(s) left
11:53:31 | 2895   | outgoing-2      | send-timer 16 second(s) left
11:53:31 | 2895   | outgoing-2      | receive-timer 55 second(s) left
11:53:31 | 2895   | outgoing-1      | receive-timer 55 second(s) left
11:53:32 | 2895   | outgoing-1      | send-timer 15 second(s) left
11:53:32 | 2895   | outgoing-2      | send-timer 15 second(s) left
11:53:32 | 2895   | outgoing-2      | receive-timer 54 second(s) left
11:53:32 | 2895   | outgoing-1      | receive-timer 54 second(s) left
11:53:33 | 2895   | outgoing-1      | send-timer 14 second(s) left
11:53:33 | 2895   | outgoing-2      | send-timer 14 second(s) left
11:53:33 | 2895   | process         | command from process abc : neighbor 172.27.10.77 announce flow route source 10.30.2.0/24 destination 210.210.210.0/24 redirect 65000:1 
11:53:33 | 2895   | reactor         | async | abc | neighbor 172.27.10.77 announce flow route source 10.30.2.0/24 destination 210.210.210.0/24 redirect 65000:1
11:53:33 | 2895   | configuration   | . route            | 'source' '10.30.2.0/24' 'destination' '210.210.210.0/24' 'redirect' '65000:1'
11:53:33 | 2895   | api             | flow added to neighbor 172.27.10.77 local-ip 172.27.10.120 local-as 1 peer-as 1 router-id 172.27.10.120 family-allowed in-open : flow destination-ipv4 210.210.210.0/24 source-ipv4 10.30.2.0/24 next-hop None extended-community redirect:65000:1
11:53:33 | 2895   | reactor         | performing dynamic route update
11:53:33 | 2895   | process         | responding to abc : done
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | ********************************************************************************
11:53:33 | 2895   | reactor         | EXABGP MISBEHAVED / HELP US FIX IT
11:53:33 | 2895   | reactor         | ********************************************************************************
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | Sorry, you encountered a problem with ExaBGP, as the problem only affects one
11:53:33 | 2895   | reactor         | peer, we are trying to keep the program running.
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | There are a few things you can do to help us (and yourself):
11:53:33 | 2895   | reactor         | - make sure you are running the latest version of the code available at
11:53:33 | 2895   | reactor         |   https://github.com/Exa-Networks/exabgp/releases/latest
11:53:33 | 2895   | reactor         | - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
11:53:33 | 2895   | reactor         |   so it can be fixed (github can be searched for similar reports)
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | PLEASE, when reporting, do include as much information as you can:
11:53:33 | 2895   | reactor         | - do not obfuscate any data (feel free to send us a private  email with the
11:53:33 | 2895   | reactor         |   extra information if your business policy is strict on information sharing)
11:53:33 | 2895   | reactor         |   https://github.com/Exa-Networks/exabgp/wiki/FAQ
11:53:33 | 2895   | reactor         | - if you can reproduce the issue, run ExaBGP with the command line option -d
11:53:33 | 2895   | reactor         |   it provides us with much needed information to fix problems quickly
11:53:33 | 2895   | reactor         | - include the information presented below
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | Should you not receive an acknowledgment of your issue on github (assignement,
11:53:33 | 2895   | reactor         | comment, or similar) within a few hours, feel free to email us to make sure
11:53:33 | 2895   | reactor         | it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | ********************************************************************************
11:53:33 | 2895   | reactor         | -- Please provide ALL the information below on :
11:53:33 | 2895   | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
11:53:33 | 2895   | reactor         | ********************************************************************************
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | ExaBGP version : 4.0.2-1c737d99
11:53:33 | 2895   | reactor         | Python version : 2.7.6 (default, Nov 23 2017, 15:49:48)  [GCC 4.8.4]
11:53:33 | 2895   | reactor         | System Uname   : #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014
11:53:33 | 2895   | reactor         | System MaxInt  : 9223372036854775807
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | <type 'exceptions.AttributeError'>
11:53:33 | 2895   | reactor         | 'NoneType' object has no attribute 'ton'
11:53:33 | 2895   | reactor         | Traceback (most recent call last):
11:53:33 | 2895   | reactor         |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 530, in _run
11:53:33 | 2895   | reactor         |     for action in self._main():
11:53:33 | 2895   | reactor         |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/peer.py", line 479, in _main
11:53:33 | 2895   | reactor         |     six.next(new_routes)
11:53:33 | 2895   | reactor         |   File "/usr/local/lib/python2.7/dist-packages/exabgp/reactor/protocol.py", line 347, in new_update
11:53:33 | 2895   | reactor         |     for message in update.messages(self.negotiated,include_withdraw):
11:53:33 | 2895   | reactor         |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/__init__.py", line 157, in messages
11:53:33 | 2895   | reactor         |     for mprnlri in mp_announce.packed_attributes(negotiated, msg_size - len(withdraws + announced)):
11:53:33 | 2895   | reactor         |   File "/usr/local/lib/python2.7/dist-packages/exabgp/bgp/message/update/attribute/mprnlri.py", line 73, in packed_attributes
11:53:33 | 2895   | reactor         |     nexthop = nh_rd + nlri.nexthop.ton(negotiated,nlri.afi)
11:53:33 | 2895   | reactor         | AttributeError: 'NoneType' object has no attribute 'ton'
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | ********************************************************************************
11:53:33 | 2895   | reactor         | -- Please provide _ALL_ the information above on :
11:53:33 | 2895   | reactor         | -- https://github.com/Exa-Networks/exabgp/issues
11:53:33 | 2895   | reactor         | ********************************************************************************
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | outgoing-2      | peer reset, message [] error[]
11:53:33 | 2895   | outgoing-2      | outgoing-2 172.27.10.120-172.27.10.77, closing connection
11:53:33 | 2895   | reactor         | initialising connection to peer-2
11:53:33 | 2895   | outgoing-3      | attempting connection to 172.27.10.77:179
11:53:33 | 2895   | outgoing-3      | sending TCP payload (  87) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0057 0104 0001 003C AC1B 0A78 3A02 1040 0E80 3C00 0185 8000 0101 8000 0104 8002 0601 0400 0100 0102 0601 0400 0100 0402 0601 0400 0100 8502 0202 0002 0246 0002 0641 0400 0000 01
11:53:33 | 2895   | outgoing-3      | >> OPEN version=4 asn=1 hold_time=60 router_id=172.27.10.120 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), Route Refresh, Graceful Restart Flags 0x8 Time 60 ipv4/flow=0x80 ipv4/unicast=0x80 ipv4/nlri-mpls=0x80, ASN4(1), Enhanced Route Refresh]
11:53:33 | 2895   | outgoing-3      | receive-timer 59 second(s) left
11:53:33 | 2895   | outgoing-3      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0043 01
11:53:33 | 2895   | outgoing-3      | received TCP payload (  48) 0400 0100 3C64 6464 0226 0206 0104 0001 0004 0206 0104 0001 0085 0202 8000 0202 0200 0204 4002 0078 0206 4104 0000 0001
11:53:33 | 2895   | outgoing-3      | << message of type OPEN
11:53:33 | 2895   | outgoing-3      | << OPEN version=4 asn=1 hold_time=60 router_id=100.100.100.2 capabilities=[Multiprotocol(ipv4 nlri-mpls,ipv4 flow), Route Refresh, Graceful Restart Flags 0x0 Time 120 , ASN4(1), Route Refresh]
11:53:33 | 2895   | outgoing-3      | --------------------------------------------------------------------
11:53:33 | 2895   | outgoing-3      | the connection can not carry the following family/families
11:53:33 | 2895   | outgoing-3      |  - peer is not configured for ipv4/unicast
11:53:33 | 2895   | outgoing-3      | therefore no routes of this kind can be announced on the connection
11:53:33 | 2895   | outgoing-3      | --------------------------------------------------------------------
11:53:33 | 2895   | outgoing-3      | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:33 | 2895   | outgoing-3      | >> KEEPALIVE (OPENCONFIRM)
11:53:33 | 2895   | outgoing-3      | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
11:53:33 | 2895   | outgoing-3      | << message of type KEEPALIVE
11:53:33 | 2895   | outgoing-3      | receive-timer 59 second(s) left
11:53:33 | 2895   | reactor         | connected to peer-2 with outgoing-3 172.27.10.120-172.27.10.77
11:53:33 | 2895   | outgoing-3      | send-timer 20 second(s) left
11:53:33 | 2895   | reactor         | 
11:53:33 | 2895   | reactor         | ********************************************************************************

```

##### SUMMARY

I am testing flowspec with exabgp, and updating routes by using http api. I use the curl form.
exabgp works fine when using accept/discard options, for example:
curl --form "command=neighbor 172.27.10.77 announce flow route source 10.30.2.0/24 destination 210.210.210.0/24 accept" http://localhost:5001/neighbor 172.27.10.77 announce flow route source 10.30.2.0/24 destination 210.210.210.0/24 accept

But exabgp will tear down neighbor when using redirect option, for example:
curl --form "command=neighbor 172.27.10.77 announce flow route source 10.30.2.0/24 destination 210.210.210.0/24 redirect 65000:1" http://localhost:5001/neighbor 172.27.10.77 announce flow route source 10.30.2.0/24 destination 210.210.210.0/24 redirect 65000:1

##### EXPECTED RESULTS

I expect exabgp can update routes to peer when using redirect option.

##### ACTUAL RESULTS

exabgp tears down it's peer and try to reopen

**Comment by thomas-mangin** [comment]
Sorry for this bug report, I should be able to look into this issue in the next few days.

**Comment by jasonsdn** [comment]
ok, thank Thomas.

**Comment by jasonsdn** [comment]
Hi Thomas，
any updates ？

**Comment by thomas-mangin** [comment]
found the cause - fixed - tested - should just now work as expected.

**Comment by jasonsdn** [comment]
Thanks Thomas, I will test it.
