### ISSUE TITLE
Exabgp to collect RouteReflector Changes!

### ISSUE THREAD

**Issue by Jitoxxx** [Exa-Networks/exabgp#810]
##### OS

```

##### Installation
<!--
> pip install exabgp
-->

##### Environment 
<!--
exabgp --di is empty
-->

```

```

##### Configuration
<!--- 
####pprint-json-from-file.py

#!/usr/bin/env python
import sys
from pprint import pprint
import json


infile = open(sys.argv[1])
for line in infile.readlines():
  jsonin = json.loads(line)
  pprint(jsonin)


####transfrom-exabgp-json-py
#!/usr/bin/env python
import sys
import socket
import json
from pprint import pprint

sock = socket.socket()
sock.connect( ('MYIP', 5150) )

def get_attrs(json_in):
    attrs = {}
    attrs['neighbor'] =     json_in['neighbor']['address']['peer']
    attrs['peeras'] =       json_in['neighbor']['asn']['peer']

    msgtype =               json_in['neighbor']['message'].keys()[0]
    attrs['msgtype'] = msgtype

    if 'announce' in        json_in['neighbor']['message'][msgtype].keys():
      action = 'announce'
    elif 'withdraw' in      json_in['neighbor']['message'][msgtype].keys():
      action = 'withdraw'
    else:
      print "funky action in this message, %s" % json_in
    attrs['action'] = action

    afisafi  =              json_in['neighbor']['message'][msgtype][action].keys()[0]
    attrs['afi'] = afisafi.split()[0]
    attrs['safi'] = afisafi.split()[1]

    if action == 'announce':
      nexthop =             json_in['neighbor']['message'][msgtype][action][afisafi].keys()[0]
      attrs['nexthop'] =      nexthop

      # simple mapping, but substitute hyphens since elastic doesn't like em
      simple_attributes = ['local-preference','origin','med','originator-id','cluster-list']
      for simple_attribute in simple_attributes:
        if json_in['neighbor']['message'][msgtype]['attribute'].has_key(simple_attribute):
          attrs[simple_attribute.replace('-','')] = json_in['neighbor']['message'][msgtype]['attribute'][simple_attribute]

      # as-path needs to be casted from list to string
      if json_in['neighbor']['message'][msgtype]['attribute'].has_key('as-path'):
        if type(json_in['neighbor']['message'][msgtype]['attribute']['as-path']) == type([]):
          attrs['aspath'] = ' '.join(str(x) for x in json_in['neighbor']['message'][msgtype]['attribute']['as-path'])
        else:
          attrs['aspath'] =   json_in['neighbor']['message'][msgtype]['attribute']['as-path']

      # ext comms are string/value pairs by exa, only keep strings
      if json_in['neighbor']['message'][msgtype]['attribute'].has_key('extended-community'):
        extcomms = []
        for extcomm in json_in['neighbor']['message'][msgtype]['attribute']['extended-community']:
          extcomms.append(extcomm['string'])
        attrs['extcomms'] = extcomms

      # regular comms are lists, rewrite to colon=separated
      if json_in['neighbor']['message'][msgtype]['attribute'].has_key('community'):
        comms = []
        for comm in json_in['neighbor']['message'][msgtype]['attribute']['community']:
          comms.append("%s:%s" % (comm[0],comm[1]))
        attrs['community'] = comms
    return attrs


def get_evpn_routes(announce_in):
    announce = {}
    announce['rd'] =           announce_in['rd']
    routetype =                announce_in['code']
    routetypename =            announce_in['name']
    announce['routetype'] =    routetype
    announce['routetypename'] =    routetypename
    if routetype == 1:
      announce['esi'] = announce_in['esi']
      announce['ethernettag'] = announce_in['ethernet-tag']
      announce['label'] = announce_in['label']
    elif routetype == 2:
      announce['esi'] = announce_in['esi']
      announce['mac'] = announce_in['mac']
      announce['ethernettag'] = announce_in['ethernet-tag']
      try:
        announce['ip'] = announce_in['ip']
      except KeyError:
        pass
      announce['label'] = announce_in['label']
    elif routetype == 3:
      announce['ethernettag'] = announce_in['ethernet-tag']
      announce['ip'] = announce_in['ip']
    elif routetype == 4:
      announce['ip'] = announce_in['ip']
      announce['esi'] = announce_in['esi']
    elif routetype == 5:
      pass
    else: # not supported
      pass
    return announce

def get_mpls_vpn_routes(announce_in):
    announce = {}
    announce['rd'] =           announce_in['rd']
    announce['label'] = announce_in['label']
    announce['prefix'] = announce_in['nlri']

    return announce

def get_unicast_routes(announce_in):
    announce = {}
    announce['prefix'] = announce_in['nlri']

    return announce

def get_flow_routes(announce_in):
    announce = {}
    announce['rule'] = announce_in['string']
    return announce

logfile = open('/tmp/transform.log','a')
counter = 0
while True:
    try:
        line = sys.stdin.readline().strip()
        if line == "":
            counter += 1
            if counter > 100:
                break
            continue
        counter = 0
        json_in = json.loads(line)
        json_out_list = []

        #logfile.write(line)
        attrs = get_attrs(json_in)
        attrs['orig'] = line # only when developing/troubleshooting
        #print "ATTRS:",attrs
        routes_to_parse = []
        if attrs['action'] == 'announce':
          routes_to_parse = json_in['neighbor']['message'][attrs['msgtype']][attrs['action']][attrs['afi'] + ' ' + attrs['safi']][attrs['nexthop']]
        elif attrs['action'] == 'withdraw':
          routes_to_parse = json_in['neighbor']['message'][attrs['msgtype']][attrs['action']][attrs['afi'] + ' ' + attrs['safi']]
        else:
          print "ERROR: we're not supposed to get here, funky action in ", line
        #print "RTP:", routes_to_parse
        for route in routes_to_parse:
          newroute = {}
          newroute.update(attrs)
          if attrs['safi'] == 'evpn':
            newroute.update(get_evpn_routes(route))
            json_newroute = json.dumps(newroute)
            json_out_list.append(json_newroute)
          elif attrs['safi'] == 'mpls-vpn':
            newroute.update(get_mpls_vpn_routes(route))
            json_newroute = json.dumps(newroute)
            json_out_list.append(json_newroute)
          elif attrs['safi'] == 'unicast':
            newroute.update(get_unicast_routes(route))
            json_newroute = json.dumps(newroute)
            json_out_list.append(json_newroute)
          elif attrs['safi'] == 'flow':
            newroute.update(get_flow_routes(route))
            json_newroute = json.dumps(newroute)
            json_out_list.append(json_newroute)
          else:
            logfile.write(line)
        #print "OUT LIST:",len(json_out_list), pprint(json_out_list)
        msg = '\n'.join(json_out_list)
        #print "MSG", type(msg),len(msg),msg
        sock.sendall(msg + '\n')
    except KeyboardInterrupt:
        sock.close()
#        logfile.close()
    except IOError:
        # most likely a signal during readline
        sock.close()
#        logfile.close()

sock.close()
#logfile.close()


####exabgp.env

[exabgp.api]
encoder = text
highres = false
respawn = false
socket = ''

[exabgp.bgp]
openwait = 60

[exabgp.cache]
attributes = true
nexthops = true

[exabgp.daemon]
daemonize = true
pid = ''
user = 'nobody'

[exabgp.log]
all = false
configuration = true
daemon = true
destination = 'exa.log'
enable = true
level = INFO
message = false
network = true
packets = false
parser = false
processes = true
reactor = true
rib = false
routes = false
short = false
timers = false

[exabgp.pdb]
enable = false

[exabgp.profile]
enable = false
file = ''

[exabgp.reactor]
speed = 1.0

[exabgp.tcp]
acl = false
bind = ''
delay = 0
once = false
port = 179

-->
```

####collector.conf

process parsed-route-backend {
        run /home/ubuntu/exabgp-4.0.5/routecollector/bin/transform-exabgp-json.py;
	encoder json;
}

template {
    neighbor VPN-RR {
	    router-id xx.xxx.xx.xxx;
        local-address xx.xxx.xx.xxx;
        local-as xxxx;
        peer-as xxxx;
        hold-time 180;
	family {
			ipv4 mpls-vpn;
			ipv6 mpls-vpn;
		}
	api speaking {
		processes [ parsed-route-backend ];
		receive {
			parsed;
			#keepalive;
			update;
		}
	}
   }
}

neighbor xxx.xxx.xxx.xxx {
	inherit VPN-RR;
```

##### Program output
<!-- 

^C14:25:40 | 10545  | reactor       | ^C received
14:25:40 | 10545  | reactor       | performing shutdown
Traceback (most recent call last):
  File "/home/ubuntu/exabgp-4.0.5/routecollector/bin/transform-exabgp-json.py", line 129, in <module>
    attrs = get_attrs(json_in)
  File "/home/ubuntu/exabgp-4.0.5/routecollector/bin/transform-exabgp-json.py", line 12, in get_attrs
    attrs['neighbor'] =     json_in['neighbor']['address']['peer']
KeyError: 'neighbor'
14:25:40 | 10545  | process       | terminating process parsed-route-backend

###### This is the only error i seem to get.

**Comment by thomas-mangin** [comment]
The json does not have a 'neighbor' key ... please print it to see what was sent and why it is not there ... I can not really help you much here.

**Comment by Jitoxxx** [comment]
Yea, working on that still, another question;

When I run Exabgp --env exabgp.env I get the following : 

´´´´
no configuration file providedubuntu@modern-roughy:~/exabgp-4.0.5/routecollector/etc$ exabgp -env exabgp.env
08:13:21 | 15219  | welcome       | Thank you for using ExaBGP
08:13:21 | 15219  | version       | 4.0.5-67a808ae
08:13:21 | 15219  | interpreter   | 2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
08:13:21 | 15219  | os            | Linux modern-roughy 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64
08:13:21 | 15219  | installation  | /home/ubuntu/.local
08:13:21 | 15219  | advice        | environment file missing
08:13:21 | 15219  | advice        | generate it using "exabgp --fi > /home/ubuntu/.local/etc/exabgp/nv"
08:13:21 | 15219  | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
08:13:21 | 15219  | cli           | we scanned the following folders (the number is your PID):
08:13:21 | 15219  | cli control   |  - /run/exabgp/
08:13:21 | 15219  | cli control   |  - /run/1000/
08:13:21 | 15219  | cli control   |  - /run/
08:13:21 | 15219  | cli control   |  - /var/run/exabgp/
08:13:21 | 15219  | cli control   |  - /var/run/1000/
08:13:21 | 15219  | cli control   |  - /var/run/
08:13:21 | 15219  | cli control   |  - /home/ubuntu/.local/run/exabgp/
08:13:21 | 15219  | cli control   |  - /home/ubuntu/.local/run/1000/
08:13:21 | 15219  | cli control   |  - /home/ubuntu/.local/run/
08:13:21 | 15219  | cli control   |  - /home/ubuntu/.local/var/run/exabgp/
08:13:21 | 15219  | cli control   |  - /home/ubuntu/.local/var/run/1000/
08:13:21 | 15219  | cli control   |  - /home/ubuntu/.local/var/run/
08:13:21 | 15219  | cli control   | please make them in one of the folder with the following commands:
08:13:21 | 15219  | cli control   | > mkfifo /home/ubuntu/exabgp-4.0.5/routecollector/etc/run/exabgp.{in,out}
08:13:21 | 15219  | cli control   | > chmod 600 /home/ubuntu/exabgp-4.0.5/routecollector/etc/run/exabgp.{in,out}
08:13:21 | 15219  | cli control   | > chown 1000:1000 /home/ubuntu/exabgp-4.0.5/routecollector/etc/run/exabgp.{in,out}
08:13:21 | 15219  | configuration | performing reload of exabgp 4.0.5-67a808ae
08:13:21 | 15219  | configuration | problem with the configuration file, no change done
08:13:21 | 15219  | configuration | problem parsing configuration file line 2
08:13:21 | 15219  | configuration | error message: invalid syntax
´´´´

**Comment by thomas-mangin** [comment]
it is `--env` and not '-env`

**Comment by Jitoxxx** [comment]
If I used --env exabgp.env

I get help from all the options Env had and what it does ?? 
It doesn't load the exabgp.env

**Comment by Jitoxxx** [comment]
Sorry for all these questions, I'm working on a project and I'm new to BGP and EXABGP.

Is there a way to know if EXABGP receives messages, cause my BGP router say's its sending the data, but I have no clue of how to display it or where to check if it's been deliverd.

Sorry and thank you

**Comment by Jitoxxx** [comment]
Also I get this when trying starting exabgp:

```
13:10:29 | 28862  | reactor       | loaded new configuration successfully
13:10:29 | 28862  | process       | forked process parsed-route-backend
13:10:29 | 28862  | reactor       | initialising connection to peer-1
13:10:29 | 28862  | outgoing-1    | attempting connection to xxx.xxx.xxx.xxx:179
13:10:29 | 28862  | outgoing-1    | connection to xxx.xxx.xxx.xxx closed
13:10:29 | 28862  | outgoing-1    | outgoing-1 xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx closing connection
13:10:29 | 28862  | reactor       | initialising connection to peer-1
13:10:29 | 28862  | outgoing-2    | attempting connection to xxx.xxx.xxx.xxx:179
13:10:29 | 28862  | outgoing-2    | connection to xxx.xxx.xxx.xxx closed
13:10:29 | 28862  | outgoing-2    | outgoing-2 xxx.xxx.xxx.xxx-xxx.xxx.xxx.xxx closing connection

```
This goes on forever.

**Comment by thomas-mangin** [comment]
if you run with `-d` I will have more clue on what you are doing wrong, for example if the router is not configured correctly, or what is not right.

With your installation the environment file (which is not really required unless you really know you need to change something) should be `/usr/local/etc/exabgp/exabgp.env` as indicated with `generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env` - you could symlink the location to your current file if you need - or indeed use `--env`.

**Comment by Jitoxxx** [comment]
I got it to work, I was still running old instances which blocked the new exabgp config from running.
I'm testing now and I'm guessing it works, but only temporary, I guess the data it's collecting is to much to handle over a timespan? After 7min of collecting 703.000 hits of changes, it stops sending them forward.

Thanks for your help, I'll be searching through exabgp to solve this issue and have a 100% uptime!

**Comment by Jitoxxx** [comment]
For those who are wondering here what happend:

I had an issue when running a script : 

```

EXA_BASEDIR=/exabgp-4.0.5/
CONF_DIR=/routecollector/etc/
$EXA_BASEDIR/sbin/exabgp --env $CONF_DIR/exabgp.env $CONF_DIR/grt-collector.cfg
$EXA_BASEDIR/sbin/exabgp --env $CONF_DIR/exabgp.env $CONF_DIR/vprn-collector.cfg
$EXA_BASEDIR/sbin/exabgp --env $CONF_DIR/exabgp.env $CONF_DIR/evpn-collector.cfg

```

If I run this script it bugs and always closes connections instead of keeping it up.

When I run the ```
exabgp --env exabgp.env grt-collector.cfg
```
it works

Don't really know what the problem is.
