### ISSUE TITLE
Loopback IP address detection fails on OS X

### ISSUE THREAD

**Issue by oogali** [Exa-Networks/exabgp#822]
##### Summary

ExaBGP cannot parse loopback IP addresses on OS X High Sierra.

It largely appears to be an issue on [line 312](https://github.com/Exa-Networks/exabgp/blob/master/lib/exabgp/application/healthcheck.py#L312) where the first part of the assignment attempts to cast a `None` into an `int`.

The `None` occurs because the output of `ifconfig lo0` on OS X does not include a `prefixlen` bit for IPv4 addresses, just the network mask in hexadecimal notation.

```
$ ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
```

##### OS

```
Apple OS X High Sierra 10.13.4 Build 17E199
```

```
$ uname -a
Darwin monty.lab.idlepattern.com 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
```

##### Version

```
$ exabgp --version
ExaBGP : 4.0.6-daa3d6ba
Python : 2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
Uname  : Darwin monty.lab.idlepattern.com 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Root   : /Users/oogali/Library/Python/2.7
```

##### Installation
```
pip install --user exabgp
```

##### Environment 

```
$ exabgp --di
$
```

##### Configuration

```
process healthcheck {
  run python -m exabgp healthcheck --cmd "test -f /Users/oogali/exabgp-test/announce" --ip 192.168.81.123 --next-hop 192.168.7.121 --withdraw-on-down;
  encoder json;
}

template {
  neighbor anycast-peer {
    local-as 65531;
    peer-as 65530;

    router-id 192.168.7.121;
    local-address 192.168.7.121;

    hold-time 30;
    group-updates false;

    api {
      processes [ healthcheck ];
    }
  }
}

neighbor 192.168.7.1 {
  inherit anycast-peer;
}
```

##### Program output

```
$ exabgp -d -e exabgp.env test.conf
19:06:15 | 10388  | welcome       | Thank you for using ExaBGP
19:06:15 | 10388  | version       | 4.0.6-daa3d6ba
19:06:15 | 10388  | interpreter   | 2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
19:06:15 | 10388  | os            | Darwin monty.lab.idlepattern.com 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
19:06:15 | 10388  | installation  | /Users/oogali/Library/Python/2.7
19:06:15 | 10388  | advice        | environment file missing
19:06:15 | 10388  | advice        | generate it using "exabgp --fi > /Users/oogali/Library/Python/2.7/etc/exabgp/exabgp.env"
19:06:15 | 10388  | cli           | could not find the named pipes (exabgp.in and exabgp.out) required for the cli
19:06:15 | 10388  | cli           | we scanned the following folders (the number is your PID):
19:06:15 | 10388  | cli control   |  - /run/exabgp/
19:06:15 | 10388  | cli control   |  - /run/501/
19:06:15 | 10388  | cli control   |  - /run/
19:06:15 | 10388  | cli control   |  - /var/run/exabgp/
19:06:15 | 10388  | cli control   |  - /var/run/501/
19:06:15 | 10388  | cli control   |  - /var/run/
19:06:15 | 10388  | cli control   |  - /Users/oogali/Library/Python/2.7/run/exabgp/
19:06:15 | 10388  | cli control   |  - /Users/oogali/Library/Python/2.7/run/501/
19:06:15 | 10388  | cli control   |  - /Users/oogali/Library/Python/2.7/run/
19:06:15 | 10388  | cli control   |  - /Users/oogali/Library/Python/2.7/var/run/exabgp/
19:06:15 | 10388  | cli control   |  - /Users/oogali/Library/Python/2.7/var/run/501/
19:06:15 | 10388  | cli control   |  - /Users/oogali/Library/Python/2.7/var/run/
19:06:15 | 10388  | cli control   | please make them in one of the folder with the following commands:
19:06:15 | 10388  | cli control   | > mkfifo /Users/oogali/exabgp-test/run/exabgp.{in,out}
19:06:15 | 10388  | cli control   | > chmod 600 /Users/oogali/exabgp-test/run/exabgp.{in,out}
19:06:15 | 10388  | cli control   | > chown 501:20 /Users/oogali/exabgp-test/run/exabgp.{in,out}
19:06:15 | 10388  | configuration | performing reload of exabgp 4.0.6-daa3d6ba
19:06:15 | 10388  | configuration | > process          | 'healthcheck'
19:06:15 | 10388  | configuration | . run              | 'python' '-m' 'exabgp' 'healthcheck' '--cmd' 'test -f /Users/oogali/exabgp-test/announce' '--ip' '192.168.81.123' '--next-hop' '192.168.7.121' '--withdraw-on-down'
19:06:15 | 10388  | configuration | . encoder          | 'json'
19:06:15 | 10388  | configuration | < process          |
19:06:15 | 10388  | configuration | > template         |
19:06:15 | 10388  | configuration | > neighbor         | 'anycast-peer'
19:06:15 | 10388  | configuration | . local-as         | '65531'
19:06:15 | 10388  | configuration | . peer-as          | '65530'
19:06:15 | 10388  | configuration | . router-id        | '192.168.7.121'
19:06:15 | 10388  | configuration | . local-address    | '192.168.7.121'
19:06:15 | 10388  | configuration | . hold-time        | '30'
19:06:15 | 10388  | configuration | . group-updates    | 'false'
19:06:15 | 10388  | configuration | > api              |
19:06:15 | 10388  | configuration | . processes        | '[' 'healthcheck' ']'
19:06:15 | 10388  | configuration | < api              |
19:06:15 | 10388  | configuration | < neighbor         |
19:06:15 | 10388  | configuration | < template         |
19:06:15 | 10388  | configuration | > neighbor         | '192.168.7.1'
19:06:15 | 10388  | configuration | . inherit          | 'anycast-peer'
19:06:15 | 10388  | configuration | < neighbor         |
19:06:15 | 10388  | reactor       | new peer: neighbor 192.168.7.1 local-ip 192.168.7.121 local-as 65531 peer-as 65530 router-id 192.168.7.121 family-allowed in-open
19:06:15 | 10388  | reactor       | loaded new configuration successfully
19:06:15 | 10388  | process       | forked process healthcheck
19:06:15 | 10388  | reactor       | initialising connection to peer-1
19:06:15 | 10388  | outgoing-1    | attempting connection to 192.168.7.1:179
19:06:15 | 10388  | outgoing-1    | sending TCP payload ( 177) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 00B1 0104 FFFB 001E C0A8 0779 9402 0601 0400 0100 0102 0601 0400 0100 0202 0601 0400 0100 0402 0601 0400 0100 8002 0601 0400 0100 8402 0601 0400 0100 8502 0601 0400 0100 8602 0601 0400 0200 0102 0601 0400 0200 0202 0601 0400 0200 0402 0601 0400 0200 8002 0601 0400 0200 8502 0601 0400 0200 8602 0601 0400 1900 4102 0601 0400 1900 4602 0601 0440 0400 4702 0601 0440 0400 4802 0206 0002 0641 0400 00FF FB
19:06:15 | 10388  | outgoing-1    | >> OPEN version=4 asn=65531 hold_time=30 router_id=192.168.7.121 capabilities=[Multiprotocol(ipv4 unicast,ipv4 multicast,ipv4 nlri-mpls,ipv4 mpls-vpn,ipv4 rtc,ipv4 flow,ipv4 flow-vpn,ipv6 unicast,ipv6 multicast,ipv6 nlri-mpls,ipv6 mpls-vpn,ipv6 flow,ipv6 flow-vpn,l2vpn vpls,l2vpn evpn,bgp-ls bgp-ls,bgp-ls bgp-ls-vpn), Extended Message(65535), ASN4(65531)]
19:06:15 | 10388  | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002D 01
19:06:15 | 10388  | outgoing-1    | received TCP payload (  26) 04FF FA00 B4C0 A807 0110 020E 0200 4104 0000 FFFA 0104 0001 0001
19:06:15 | 10388  | outgoing-1    | << message of type OPEN
19:06:15 | 10388  | outgoing-1    | << OPEN version=4 asn=65530 hold_time=180 router_id=192.168.7.1 capabilities=[Multiprotocol(ipv4 unicast), Route Refresh, ASN4(65530)]
19:06:15 | 10388  | ka-outgoing-1 | receive-timer 60 second(s) left
19:06:15 | 10388  | outgoing-1    | --------------------------------------------------------------------
19:06:15 | 10388  | outgoing-1    | the connection can not carry the following family/families
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv4/multicast
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for bgp-ls/bgp-ls
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv6/flow-vpn
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv4/mpls-vpn
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv4/flow
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for bgp-ls/bgp-ls-vpn
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for l2vpn/evpn
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv4/nlri-mpls
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv6/nlri-mpls
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv4/rtc
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv6/mpls-vpn
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv4/flow-vpn
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv6/unicast
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv6/multicast
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for ipv6/flow
19:06:15 | 10388  | outgoing-1    |  - peer is not configured for l2vpn/vpls
19:06:15 | 10388  | outgoing-1    | therefore no routes of this kind can be announced on the connection
19:06:15 | 10388  | outgoing-1    | --------------------------------------------------------------------
19:06:15 | 10388  | outgoing-1    | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
19:06:15 | 10388  | outgoing-1    | >> KEEPALIVE (OPENCONFIRM)
19:06:15 | 10388  | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
19:06:15 | 10388  | outgoing-1    | << message of type KEEPALIVE
19:06:15 | 10388  | ka-outgoing-1 | receive-timer 30 second(s) left
19:06:15 | 10388  | reactor       | connected to peer-1 with outgoing-1 192.168.7.121-192.168.7.1
19:06:15 | 10388  | outgoing-1    | sending TCP payload (  23) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
19:06:15 | 10388  | outgoing-1    | >> EOR ipv4 unicast
19:06:15 | 10388  | peer-1        | >> EOR(s)
19:06:15 | 10388  | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002F 02
19:06:15 | 10388  | outgoing-1    | received TCP payload (  28) 0000 0014 4001 0100 4002 0602 0100 00FF FA40 0304 C0A8 0701 18C0 A807
19:06:15 | 10388  | outgoing-1    | << message of type UPDATE
19:06:15 | 10388  | parser        | parsing UPDATE (  28) 0000 0014 4001 0100 4002 0602 0100 00FF FA40 0304 C0A8 0701 18C0 A807
19:06:15 | 10388  | parser        | withdrawn NLRI none
19:06:15 | 10388  | parser        | attribute origin             flag 0x40 type 0x01 len 0x01 payload 00
19:06:15 | 10388  | parser        | attribute as-path            flag 0x40 type 0x02 len 0x06 payload 0201 0000 FFFA
19:06:15 | 10388  | parser        | attribute next-hop           flag 0x40 type 0x03 len 0x04 payload C0A8 0701
19:06:15 | 10388  | parser        | NLRI      ipv4 unicast       without path-information     payload 18C0 A807
19:06:15 | 10388  | parser        | announced NLRI 192.168.7.0/24 next-hop 192.168.7.1
19:06:15 | 10388  | peer-1        | << UPDATE #1
19:06:15 | 10388  | peer-1        |    UPDATE #1 nlri  (   4) 192.168.7.0/24 next-hop 192.168.7.1
ERROR[healthcheck] Uncaught exception: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 610, in main
    setup_ips(options.ips, options.label, options.sudo)
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 330, in setup_ips
    existing = set(loopback_ips(label))
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 312, in loopback_ips
    mask = int(mo.group("mask")) or bin(int(mo.group("netmask"), 16)).count("1")
TypeError: int() argument must be a string or a number, not 'NoneType'
19:06:16 | 10388  | ka-outgoing-1 | receive-timer 29 second(s) left
19:06:16 | 10388  | ka-outgoing-1 | send-timer 9 second(s) left
19:06:16 | 10388  | process       | issue with the process, restarting it
19:06:16 | 10388  | process       | terminating process healthcheck
19:06:16 | 10388  | process       | forked process healthcheck
19:06:16 | 10388  | outgoing-1    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002F 02
19:06:16 | 10388  | outgoing-1    | received TCP payload (  28) 0000 0014 4001 0100 4002 0602 0100 00FF FA40 0304 C0A8 0701 18C0 A807
19:06:16 | 10388  | outgoing-1    | << message of type UPDATE
19:06:16 | 10388  | parser        | parsing UPDATE (  28) 0000 0014 4001 0100 4002 0602 0100 00FF FA40 0304 C0A8 0701 18C0 A807
19:06:16 | 10388  | parser        | withdrawn NLRI none
19:06:16 | 10388  | parser        | NLRI      ipv4 unicast       without path-information     payload 18C0 A807
19:06:16 | 10388  | parser        | announced NLRI 192.168.7.0/24 next-hop 192.168.7.1
19:06:16 | 10388  | peer-1        | << UPDATE #2
19:06:16 | 10388  | peer-1        |    UPDATE #2 nlri  (   4) 192.168.7.0/24 next-hop 192.168.7.1
ERROR[healthcheck] Uncaught exception: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 610, in main
    setup_ips(options.ips, options.label, options.sudo)
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 330, in setup_ips
    existing = set(loopback_ips(label))
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 312, in loopback_ips
    mask = int(mo.group("mask")) or bin(int(mo.group("netmask"), 16)).count("1")
TypeError: int() argument must be a string or a number, not 'NoneType'
19:06:16 | 10388  | process       | issue with the process, restarting it
19:06:16 | 10388  | process       | terminating process healthcheck
19:06:16 | 10388  | process       | forked process healthcheck
ERROR[healthcheck] Uncaught exception: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 610, in main
    setup_ips(options.ips, options.label, options.sudo)
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 330, in setup_ips
    existing = set(loopback_ips(label))
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 312, in loopback_ips
    mask = int(mo.group("mask")) or bin(int(mo.group("netmask"), 16)).count("1")
TypeError: int() argument must be a string or a number, not 'NoneType'
19:06:16 | 10388  | process       | issue with the process, restarting it
19:06:16 | 10388  | process       | terminating process healthcheck
19:06:16 | 10388  | process       | forked process healthcheck
ERROR[healthcheck] Uncaught exception: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 610, in main
    setup_ips(options.ips, options.label, options.sudo)
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 330, in setup_ips
    existing = set(loopback_ips(label))
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 312, in loopback_ips
    mask = int(mo.group("mask")) or bin(int(mo.group("netmask"), 16)).count("1")
TypeError: int() argument must be a string or a number, not 'NoneType'
19:06:16 | 10388  | process       | issue with the process, restarting it
19:06:16 | 10388  | process       | terminating process healthcheck
19:06:16 | 10388  | process       | forked process healthcheck
ERROR[healthcheck] Uncaught exception: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 610, in main
    setup_ips(options.ips, options.label, options.sudo)
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 330, in setup_ips
    existing = set(loopback_ips(label))
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 312, in loopback_ips
    mask = int(mo.group("mask")) or bin(int(mo.group("netmask"), 16)).count("1")
TypeError: int() argument must be a string or a number, not 'NoneType'
19:06:16 | 10388  | process       | issue with the process, restarting it
19:06:16 | 10388  | process       | terminating process healthcheck
19:06:16 | 10388  | process       | forked process healthcheck
19:06:16 | 10388  | process       | Too many death for healthcheck (5) terminating program
19:06:16 | 10388  | reactor       | Problem when sending message(s) to helper program, stopping
19:06:16 | 10388  | reactor       | performing shutdown
ERROR[healthcheck] Uncaught exception: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 610, in main
    setup_ips(options.ips, options.label, options.sudo)
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 330, in setup_ips
    existing = set(loopback_ips(label))
  File "/Users/oogali/Library/Python/2.7/lib/python/site-packages/exabgp/application/healthcheck.py", line 312, in loopback_ips
    mask = int(mo.group("mask")) or bin(int(mo.group("netmask"), 16)).count("1")
TypeError: int() argument must be a string or a number, not 'NoneType'
19:06:16 | 10388  | process       | terminating process healthcheck
```

##### Steps to reproduce

```
Attempt to fire up ExaBGP on an OS X system.
```

##### Importance

```
This isn't too important for me as OS X is just a convenient testing environment.
```

**Comment by vincentbernat** [comment]
I have pushed your suggested fix. Thanks!
