### ISSUE TITLE
EXABGP Crashed when pushing a redirect rule.  

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#854]
##### OS

```
Linux

```

```
Linux Demo-Controller 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

##### Version

```
demo@Demo-Controller:/home/demo/SR_Controller$ exabgp --version
ExaBGP : 4.0.2-1c737d99
Python : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
Uname  : Linux Demo-Controller 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64
Root   : /usr/local
```

##### Installation

```
pip

```

##### Environment 

```
17:12:13 | 4687   | process       | command from process http-api : neighbor 23.1.1.11  announce flow route source 1.0.4.1/32 destination 12.1.1.2/32 protocol [ udp ] source-port [ =53 ] destination-port [ =80 ]  redirect 65001:100 
10.95.69.105 - - [19/Oct/2018 17:12:13] "POST / HTTP/1.1" 200 -
17:12:13 | 4687   | reactor       | async | http-api | neighbor 23.1.1.11 announce flow route source 1.0.4.1/32 destination 12.1.1.2/32 protocol [ udp ] source-port [ =53 ] destination-port [ =80 ] redirect 65001:100
17:12:13 | 4687   | configuration | . route            | 'source' '1.0.4.1/32' 'destination' '12.1.1.2/32' 'protocol' '[' 'udp' ']' 'source-port' '[' '=53' ']' 'destination-port' '[' '=80' ']' 'redirect' '65001:100'
17:12:13 | 4687   | api           | flow added to neighbor 23.1.1.11 local-ip 192.168.2.10 local-as 64512 peer-as 64512 router-id 192.168.2.10 family-allowed in-open : flow destination-ipv4 12.1.1.2/32 source-ipv4 1.0.4.1/32 protocol =udp destination-port =80 source-port =53 next-hop None extended-community redirect:65001:100
17:12:13 | 4687   | process       | responding to http-api : done
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       | EXABGP MISBEHAVED / HELP US FIX IT
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | Sorry, you encountered a problem with ExaBGP, as the problem only affects one
17:12:13 | 4687   | reactor       | peer, we are trying to keep the program running.
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | There are a few things you can do to help us (and yourself):
17:12:13 | 4687   | reactor       | - make sure you are running the latest version of the code available at
17:12:13 | 4687   | reactor       |   https://github.com/Exa-Networks/exabgp/releases/latest
17:12:13 | 4687   | reactor       | - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
17:12:13 | 4687   | reactor       |   so it can be fixed (github can be searched for similar reports)
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | PLEASE, when reporting, do include as much information as you can:
17:12:13 | 4687   | reactor       | - do not obfuscate any data (feel free to send us a private  email with the
17:12:13 | 4687   | reactor       |   extra information if your business policy is strict on information sharing)
17:12:13 | 4687   | reactor       |   https://github.com/Exa-Networks/exabgp/wiki/FAQ
17:12:13 | 4687   | reactor       | - if you can reproduce the issue, run ExaBGP with the command line option -d
17:12:13 | 4687   | reactor       |   it provides us with much needed information to fix problems quickly
17:12:13 | 4687   | reactor       | - include the information presented below
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | Should you not receive an acknowledgment of your issue on github (assignement,
17:12:13 | 4687   | reactor       | comment, or similar) within a few hours, feel free to email us to make sure
17:12:13 | 4687   | reactor       | it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       | -- Please provide ALL the information below on :
17:12:13 | 4687   | reactor       | -- https://github.com/Exa-Networks/exabgp/issues
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ExaBGP version : 4.0.2-1c737d99
17:12:13 | 4687   | reactor       | Python version : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
17:12:13 | 4687   | reactor       | System Uname   : #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016
17:12:13 | 4687   | reactor       | System MaxInt  : 9223372036854775807
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | <type 'exceptions.AttributeError'>
17:12:13 | 4687   | reactor       | 'NoneType' object has no attribute 'ton'
17:12:13 | 4687   | reactor       | Traceback (most recent call last):
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/reactor/peer.py", line 522, in _run
17:12:13 | 4687   | reactor       |     for action in self._main():
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/reactor/peer.py", line 472, in _main
17:12:13 | 4687   | reactor       |     six.next(new_routes)
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/reactor/protocol.py", line 347, in new_update
17:12:13 | 4687   | reactor       |     for message in update.messages(self.negotiated,include_withdraw):
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/bgp/message/update/__init__.py", line 164, in messages
17:12:13 | 4687   | reactor       |     for mprnlri in mp_announce.packed_attributes(negotiated, msg_size - len(withdraws + announced)):
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/bgp/message/update/attribute/mprnlri.py", line 73, in packed_attributes
17:12:13 | 4687   | reactor       |     nexthop = nh_rd + nlri.nexthop.ton(negotiated,nlri.afi)
17:12:13 | 4687   | reactor       | AttributeError: 'NoneType' object has no attribute 'ton'
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       | -- Please provide _ALL_ the information above on :
17:12:13 | 4687   | reactor       | -- https://github.com/Exa-Networks/exabgp/issues
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | outgoing-5    | peer reset, message [] error[]
17:12:13 | 4687   | outgoing-5    | outgoing-5 192.168.2.10-23.1.1.11, closing connection
17:12:13 | 4687   | ka-outgoing-2 | receive-timer 149 second(s) left
17:12:13 | 4687   | ka-outgoing-1 | receive-timer 147 second(s) left
17:12:13 | 4687   | ka-outgoing-4 | receive-timer 156 second(s) left
17:12:14 | 4687   | ka-outgoing-4 | send-timer 6 second(s) left
17:12:14 | 4687   | ka-outgoing-1 | send-timer 6 second(s) left
17:12:14 | 4687   | ka-outgoing-2 | send-timer 6 second(s) left
17:12:14 | 4687   | reactor       | initialising connection to peer-1
17:12:14 | 4687   | outgoing-6    | attempting connection to 23.1.1.11:179
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  73) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0049 0104 FC00 00B4 C0A8 020A 2C02 0601 0400 0100 0102 0601 0400 0100 0402 0601 0400 0100 8502 0A45 0800 0101 0200 0104 0202 0641 0400 00FC 00
17:12:14 | 4687   | outgoing-6    | >> OPEN version=4 asn=64512 hold_time=180 router_id=192.168.2.10 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), ASN4(64512), AddPath(send ipv4 unicast,send ipv4 nlri-mpls)]
17:12:14 | 4687   | ka-outgoing-6 | receive-timer 59 second(s) left
17:12:14 | 4687   | outgoing-6    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0055 01
17:12:14 | 4687   | outgoing-6    | received TCP payload (  66) 04FC 0000 B417 0101 0B38 0236 4002 012C 0804 0001 0407 0200 0104 0001 0001 0104 0001 0004 0104 0001 0085 4104 0000 FC00 4504 0001 0103 4504 0001 0401 4504 0001 8501
17:12:14 | 4687   | outgoing-6    | << message of type OPEN
17:12:14 | 4687   | outgoing-6    | << OPEN version=4 asn=64512 hold_time=180 router_id=23.1.1.11 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), Route Refresh, Unknown 8, Graceful Restart Flags 0x0 Time 300 , ASN4(64512), AddPath(receive ipv4 flow,send/receive ipv4 unicast,receive ipv4 nlri-mpls)]
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
17:12:14 | 4687   | outgoing-6    | >> KEEPALIVE (OPENCONFIRM)
17:12:14 | 4687   | ka-outgoing-6 | receive-timer 179 second(s) left
17:12:14 | 4687   | outgoing-6    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
17:12:14 | 4687   | outgoing-6    | << message of type KEEPALIVE
17:12:14 | 4687   | reactor       | connected to peer-1 with outgoing-6 192.168.2.10-23.1.1.11
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  23) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
17:12:14 | 4687   | outgoing-6    | >> EOR ipv4 unicast
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0104
17:12:14 | 4687   | outgoing-6    | >> EOR ipv4 nlri-mpls
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0185
17:12:14 | 4687   | outgoing-6    | >> EOR ipv4 flow
17:12:14 | 4687   | peer-1        | >> EOR(s)
17:12:14 | 4687   | ka-outgoing-2 | receive-timer 148 second(s) left
17:12:14 | 4687   | ka-outgoing-1 | receive-timer 146 second(s) left
17:12:14 | 4687   | ka-outgoing-4 | receive-timer 155 second(s) left
17:12:15 | 4687   | ka-outgoing-1 | send-timer 5 second(s) left
17:12:15 | 4687   | ka-outgoing-2 | send-timer 5 second(s) left
17:12:15 | 4687   | ka-outgoing-6 | send-timer 59 second(s) left
17:12:15 | 4687   | ka-outgoing-4 | send-timer 5 second(s) left
17:12:15 | 4687   | ka-outgoing-6 | receive-timer 178 second(s) left
17:12:15 | 4687   | ka-outgoing-2 | receive-timer 147 second(s) left
17:12:15 | 4687   | ka-outgoing-1 | receive-timer 145 second(s) left
17:12:15 | 4687   | ka-outgoing-4 | receive-timer 154 second(s) left
17:12:16 | 4687   | ka-outgoing-1 | send-timer 4 second(s) left
17:12:16 | 4687   | ka-outgoing-2 | send-timer 4 second(s) left
17:12:16 | 4687   | ka-outgoing-6 | send-timer 58 second(s) left
17:12:16 | 4687   | ka-outgoing-4 | send-timer 4 second(s) left
^C17:12:16 | 4687   | reactor       | ^C received
17:12:16 | 4687   | reactor       | performing shutdown
17:12:16 | 4687   | process       | terminating process http-api
```

##### Configuration

```

```

##### Program output

```
17:12:13 | 4687   | process       | command from process http-api : neighbor 23.1.1.11  announce flow route source 1.0.4.1/32 destination 12.1.1.2/32 protocol [ udp ] source-port [ =53 ] destination-port [ =80 ]  redirect 65001:100 
10.95.69.105 - - [19/Oct/2018 17:12:13] "POST / HTTP/1.1" 200 -
17:12:13 | 4687   | reactor       | async | http-api | neighbor 23.1.1.11 announce flow route source 1.0.4.1/32 destination 12.1.1.2/32 protocol [ udp ] source-port [ =53 ] destination-port [ =80 ] redirect 65001:100
17:12:13 | 4687   | configuration | . route            | 'source' '1.0.4.1/32' 'destination' '12.1.1.2/32' 'protocol' '[' 'udp' ']' 'source-port' '[' '=53' ']' 'destination-port' '[' '=80' ']' 'redirect' '65001:100'
17:12:13 | 4687   | api           | flow added to neighbor 23.1.1.11 local-ip 192.168.2.10 local-as 64512 peer-as 64512 router-id 192.168.2.10 family-allowed in-open : flow destination-ipv4 12.1.1.2/32 source-ipv4 1.0.4.1/32 protocol =udp destination-port =80 source-port =53 next-hop None extended-community redirect:65001:100
17:12:13 | 4687   | process       | responding to http-api : done
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       | EXABGP MISBEHAVED / HELP US FIX IT
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | Sorry, you encountered a problem with ExaBGP, as the problem only affects one
17:12:13 | 4687   | reactor       | peer, we are trying to keep the program running.
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | There are a few things you can do to help us (and yourself):
17:12:13 | 4687   | reactor       | - make sure you are running the latest version of the code available at
17:12:13 | 4687   | reactor       |   https://github.com/Exa-Networks/exabgp/releases/latest
17:12:13 | 4687   | reactor       | - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
17:12:13 | 4687   | reactor       |   so it can be fixed (github can be searched for similar reports)
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | PLEASE, when reporting, do include as much information as you can:
17:12:13 | 4687   | reactor       | - do not obfuscate any data (feel free to send us a private  email with the
17:12:13 | 4687   | reactor       |   extra information if your business policy is strict on information sharing)
17:12:13 | 4687   | reactor       |   https://github.com/Exa-Networks/exabgp/wiki/FAQ
17:12:13 | 4687   | reactor       | - if you can reproduce the issue, run ExaBGP with the command line option -d
17:12:13 | 4687   | reactor       |   it provides us with much needed information to fix problems quickly
17:12:13 | 4687   | reactor       | - include the information presented below
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | Should you not receive an acknowledgment of your issue on github (assignement,
17:12:13 | 4687   | reactor       | comment, or similar) within a few hours, feel free to email us to make sure
17:12:13 | 4687   | reactor       | it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       | -- Please provide ALL the information below on :
17:12:13 | 4687   | reactor       | -- https://github.com/Exa-Networks/exabgp/issues
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ExaBGP version : 4.0.2-1c737d99
17:12:13 | 4687   | reactor       | Python version : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
17:12:13 | 4687   | reactor       | System Uname   : #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016
17:12:13 | 4687   | reactor       | System MaxInt  : 9223372036854775807
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | <type 'exceptions.AttributeError'>
17:12:13 | 4687   | reactor       | 'NoneType' object has no attribute 'ton'
17:12:13 | 4687   | reactor       | Traceback (most recent call last):
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/reactor/peer.py", line 522, in _run
17:12:13 | 4687   | reactor       |     for action in self._main():
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/reactor/peer.py", line 472, in _main
17:12:13 | 4687   | reactor       |     six.next(new_routes)
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/reactor/protocol.py", line 347, in new_update
17:12:13 | 4687   | reactor       |     for message in update.messages(self.negotiated,include_withdraw):
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/bgp/message/update/__init__.py", line 164, in messages
17:12:13 | 4687   | reactor       |     for mprnlri in mp_announce.packed_attributes(negotiated, msg_size - len(withdraws + announced)):
17:12:13 | 4687   | reactor       |   File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.2-py2.7.egg/exabgp/bgp/message/update/attribute/mprnlri.py", line 73, in packed_attributes
17:12:13 | 4687   | reactor       |     nexthop = nh_rd + nlri.nexthop.ton(negotiated,nlri.afi)
17:12:13 | 4687   | reactor       | AttributeError: 'NoneType' object has no attribute 'ton'
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       | -- Please provide _ALL_ the information above on :
17:12:13 | 4687   | reactor       | -- https://github.com/Exa-Networks/exabgp/issues
17:12:13 | 4687   | reactor       | ********************************************************************************
17:12:13 | 4687   | reactor       |         
17:12:13 | 4687   | outgoing-5    | peer reset, message [] error[]
17:12:13 | 4687   | outgoing-5    | outgoing-5 192.168.2.10-23.1.1.11, closing connection
17:12:13 | 4687   | ka-outgoing-2 | receive-timer 149 second(s) left
17:12:13 | 4687   | ka-outgoing-1 | receive-timer 147 second(s) left
17:12:13 | 4687   | ka-outgoing-4 | receive-timer 156 second(s) left
17:12:14 | 4687   | ka-outgoing-4 | send-timer 6 second(s) left
17:12:14 | 4687   | ka-outgoing-1 | send-timer 6 second(s) left
17:12:14 | 4687   | ka-outgoing-2 | send-timer 6 second(s) left
17:12:14 | 4687   | reactor       | initialising connection to peer-1
17:12:14 | 4687   | outgoing-6    | attempting connection to 23.1.1.11:179
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  73) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0049 0104 FC00 00B4 C0A8 020A 2C02 0601 0400 0100 0102 0601 0400 0100 0402 0601 0400 0100 8502 0A45 0800 0101 0200 0104 0202 0641 0400 00FC 00
17:12:14 | 4687   | outgoing-6    | >> OPEN version=4 asn=64512 hold_time=180 router_id=192.168.2.10 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), ASN4(64512), AddPath(send ipv4 unicast,send ipv4 nlri-mpls)]
17:12:14 | 4687   | ka-outgoing-6 | receive-timer 59 second(s) left
17:12:14 | 4687   | outgoing-6    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0055 01
17:12:14 | 4687   | outgoing-6    | received TCP payload (  66) 04FC 0000 B417 0101 0B38 0236 4002 012C 0804 0001 0407 0200 0104 0001 0001 0104 0001 0004 0104 0001 0085 4104 0000 FC00 4504 0001 0103 4504 0001 0401 4504 0001 8501
17:12:14 | 4687   | outgoing-6    | << message of type OPEN
17:12:14 | 4687   | outgoing-6    | << OPEN version=4 asn=64512 hold_time=180 router_id=23.1.1.11 capabilities=[Multiprotocol(ipv4 unicast,ipv4 nlri-mpls,ipv4 flow), Route Refresh, Unknown 8, Graceful Restart Flags 0x0 Time 300 , ASN4(64512), AddPath(receive ipv4 flow,send/receive ipv4 unicast,receive ipv4 nlri-mpls)]
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
17:12:14 | 4687   | outgoing-6    | >> KEEPALIVE (OPENCONFIRM)
17:12:14 | 4687   | ka-outgoing-6 | receive-timer 179 second(s) left
17:12:14 | 4687   | outgoing-6    | received TCP payload (  19) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0013 04
17:12:14 | 4687   | outgoing-6    | << message of type KEEPALIVE
17:12:14 | 4687   | reactor       | connected to peer-1 with outgoing-6 192.168.2.10-23.1.1.11
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  23) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 0017 0200 0000 00
17:12:14 | 4687   | outgoing-6    | >> EOR ipv4 unicast
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0104
17:12:14 | 4687   | outgoing-6    | >> EOR ipv4 nlri-mpls
17:12:14 | 4687   | outgoing-6    | sending TCP payload (  30) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 001E 0200 0000 0790 0F00 0300 0185
17:12:14 | 4687   | outgoing-6    | >> EOR ipv4 flow
17:12:14 | 4687   | peer-1        | >> EOR(s)
17:12:14 | 4687   | ka-outgoing-2 | receive-timer 148 second(s) left
17:12:14 | 4687   | ka-outgoing-1 | receive-timer 146 second(s) left
17:12:14 | 4687   | ka-outgoing-4 | receive-timer 155 second(s) left
17:12:15 | 4687   | ka-outgoing-1 | send-timer 5 second(s) left
17:12:15 | 4687   | ka-outgoing-2 | send-timer 5 second(s) left
17:12:15 | 4687   | ka-outgoing-6 | send-timer 59 second(s) left
17:12:15 | 4687   | ka-outgoing-4 | send-timer 5 second(s) left
17:12:15 | 4687   | ka-outgoing-6 | receive-timer 178 second(s) left
17:12:15 | 4687   | ka-outgoing-2 | receive-timer 147 second(s) left
17:12:15 | 4687   | ka-outgoing-1 | receive-timer 145 second(s) left
17:12:15 | 4687   | ka-outgoing-4 | receive-timer 154 second(s) left
17:12:16 | 4687   | ka-outgoing-1 | send-timer 4 second(s) left
17:12:16 | 4687   | ka-outgoing-2 | send-timer 4 second(s) left
17:12:16 | 4687   | ka-outgoing-6 | send-timer 58 second(s) left
17:12:16 | 4687   | ka-outgoing-4 | send-timer 4 second(s) left
^C17:12:16 | 4687   | reactor       | ^C received
17:12:16 | 4687   | reactor       | performing shutdown
17:12:16 | 4687   | process       | terminating process http-api
```

##### Steps to reproduce

```

```

##### Importance

```

```

**Comment by russellkelly** [comment]
Fixed in lastest 4.0 master
