### ISSUE TITLE
ExaBgp Crash Using Neighbor Teardown Command

### ISSUE THREAD

**Issue by russellkelly** [Exa-Networks/exabgp#855]
##### OS

```
Linux

```

```
Linux Demo-Controller 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
ExaBGP version : 4.0.8-793a2931
Python version : 2.7.6 (default, Oct 26 2016, 20:30:19)  [GCC 4.8.4]
System Uname   : #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016
System MaxInt  : 9223372036854775807


```

##### Installation

```
pip


```

##### Environment 

```
08:07:19 | 1818   | ka-outgoing-4 | receive-timer 166 second(s) left
08:07:19 | 1818   | ka-outgoing-4 | send-timer 45 second(s) left
08:07:20 | 1818   | ka-outgoing-1 | receive-timer 168 second(s) left
08:07:20 | 1818   | ka-outgoing-1 | send-timer 44 second(s) left
08:07:20 | 1818   | ka-outgoing-2 | receive-timer 165 second(s) left
08:07:20 | 1818   | ka-outgoing-2 | send-timer 44 second(s) left
08:07:20 | 1818   | ka-outgoing-3 | receive-timer 164 second(s) left
08:07:20 | 1818   | ka-outgoing-3 | send-timer 44 second(s) left
08:07:20 | 1818   | ka-outgoing-4 | receive-timer 165 second(s) left
08:07:20 | 1818   | ka-outgoing-4 | send-timer 44 second(s) left
08:07:20 | 1818   | process       | command from process http-api : neighbor 6.6.6.6 teardown 2 
08:07:20 | 1818   | api           | teardown scheduled for neighbor 6.6.6.6
08:07:20 | 1818   | process       | responding to http-api : done
08:07:20 | 1818   | outgoing-2    | sending TCP payload (  45) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002D 0306 0217 4164 6D69 6E69 7374 7261 7469 7665 2053 6875 7464 6F77 6E
08:07:20 | 1818   | outgoing-2    | >> NOTIFICATION (6,2,"Administrative Shutdown")
08:07:20 | 1818   | outgoing-2    | peer reset, message [notification sent (6,2)] error[Cease / Administrative Shutdown / Administrative Shutdown]
08:07:20 | 1818   | outgoing-2    | outgoing-2 192.168.2.10-6.6.6.6, closing connection
08:07:20 | 1818   | reactor       | socket error received
08:07:20 | 1818   | reactor       | performing shutdown


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgp", line 11, in <module>
    load_entry_point('exabgp==4.0.8', 'console_scripts', 'exabgp')()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/application/bgp.py", line 302, in main
    run(env,comment,configurations,root,options["--validate"])
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/application/bgp.py", line 370, in run
    exit_code = Reactor(configurations).run(validate,root)
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/loop.py", line 222, in run
    self.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/loop.py", line 318, in shutdown
    self.peers[key].shutdown()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/peer.py", line 181, in shutdown
    self._stop("shutting down")
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/peer.py", line 153, in _stop
    self.proto.close('stop, message [%s]' % message)
AttributeError: 'NoneType' object has no attribute 'close'


```

##### Configuration

```
neighbor 6.6.6.6 {
      local-address 192.168.2.10;
      adj-rib-out false;
      router-id 192.168.2.10;
      local-as 64512;
      peer-as 64512;
      group-updates;
      family {
        ipv4 unicast;
        ipv4 nlri-mpls;
      }
      api {
        processes [ http-api ];
      }
      capability {
        add-path send;
      }

```

##### Program output

```
08:07:19 | 1818   | ka-outgoing-4 | receive-timer 166 second(s) left
08:07:19 | 1818   | ka-outgoing-4 | send-timer 45 second(s) left
08:07:20 | 1818   | ka-outgoing-1 | receive-timer 168 second(s) left
08:07:20 | 1818   | ka-outgoing-1 | send-timer 44 second(s) left
08:07:20 | 1818   | ka-outgoing-2 | receive-timer 165 second(s) left
08:07:20 | 1818   | ka-outgoing-2 | send-timer 44 second(s) left
08:07:20 | 1818   | ka-outgoing-3 | receive-timer 164 second(s) left
08:07:20 | 1818   | ka-outgoing-3 | send-timer 44 second(s) left
08:07:20 | 1818   | ka-outgoing-4 | receive-timer 165 second(s) left
08:07:20 | 1818   | ka-outgoing-4 | send-timer 44 second(s) left
08:07:20 | 1818   | process       | command from process http-api : neighbor 6.6.6.6 teardown 2 
08:07:20 | 1818   | api           | teardown scheduled for neighbor 6.6.6.6
08:07:20 | 1818   | process       | responding to http-api : done
08:07:20 | 1818   | outgoing-2    | sending TCP payload (  45) FFFF FFFF FFFF FFFF FFFF FFFF FFFF FFFF 002D 0306 0217 4164 6D69 6E69 7374 7261 7469 7665 2053 6875 7464 6F77 6E
08:07:20 | 1818   | outgoing-2    | >> NOTIFICATION (6,2,"Administrative Shutdown")
08:07:20 | 1818   | outgoing-2    | peer reset, message [notification sent (6,2)] error[Cease / Administrative Shutdown / Administrative Shutdown]
08:07:20 | 1818   | outgoing-2    | outgoing-2 192.168.2.10-6.6.6.6, closing connection
08:07:20 | 1818   | reactor       | socket error received
08:07:20 | 1818   | reactor       | performing shutdown


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgp", line 11, in <module>
    load_entry_point('exabgp==4.0.8', 'console_scripts', 'exabgp')()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/application/bgp.py", line 302, in main
    run(env,comment,configurations,root,options["--validate"])
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/application/bgp.py", line 370, in run
    exit_code = Reactor(configurations).run(validate,root)
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/loop.py", line 222, in run
    self.shutdown()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/loop.py", line 318, in shutdown
    self.peers[key].shutdown()
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/peer.py", line 181, in shutdown
    self._stop("shutting down")
  File "/usr/local/lib/python2.7/dist-packages/exabgp-4.0.8-py2.7.egg/exabgp/reactor/peer.py", line 153, in _stop
    self.proto.close('stop, message [%s]' % message)
AttributeError: 'NoneType' object has no attribute 'close'


```

##### Steps to reproduce

```

```

##### Importance

```

```

**Comment by mwichtlh** [comment]
I can reproduce the issue. It does not happen on every occasion, but frequently enough to be a problem for me.

```
4.0.7-40f00b5e
2.7.15rc1 (default, Apr 15 2018, 21:51:34)  [GCC 7.3.0]
Linux notebook 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64
```

Steps to reproduce: Let two exabgp instances peer with each other, where one of the instances is going up an down a couple of times. The following was tested on Ubuntu.

Virtual local network:
```
ip link add veth0 type veth peer name veth1
ip link set dev veth0 up
ip tuntap add tap_dummy mode tap
ip link set dev tap_dummy up
ip link add brm type bridge
ip link set tap_dummy master brm
ip link set veth0 master brm
ip addr add 80.81.192.157/16 dev brm
ip addr add 80.81.193.157/16 dev veth1
ip link set brm up
ip link set veth1 up
```

You can check connectivity between the IPs 80.81.192.157 and 80.81.193.157 by executing:
```
ping -I 80.81.192.157 80.81.193.157
PING 80.81.193.157 (80.81.193.157) from 80.81.192.157 : 56(84) bytes of data.
64 bytes from 80.81.193.157: icmp_seq=1 ttl=64 time=0.035 ms
64 bytes from 80.81.193.157: icmp_seq=2 ttl=64 time=0.054 ms
...

In case you have problems, you may have to add the following routes. My Ubuntu did that automatically. However, I'm not sure about other distributions.
```
80.81.0.0/16 dev brm proto kernel scope link src 80.81.192.157 
80.81.0.0/16 dev veth1 proto kernel scope link src 80.81.193.157
```

For testing, ExaBGP instance A and B run in two terminals. B is the one frequently going up and down.

Configuration A:
```
neighbor 80.81.192.157 {
  router-id 80.81.193.157;
  local-address 80.81.193.157;
  local-as 1234;
  peer-as 1235;
}
```

Run exabgp in terminal A:
```
env exabgp.tcp.bind="80.81.193.157" exabgp.tcp.port=179 exabgp A.conf
```

Configuration B:
```
neighbor 80.81.193.157 {
  router-id 80.81.192.157;
  local-address 80.81.192.157;
  local-as 1235;
  peer-as 1234;
}
```

Run exabgp in terminal B using the following script:
```
#! /bin/bash
  
while true
do
        env exabgp.tcp.bind="80.81.192.157" exabgp.tcp.port=179 exabgp B.conf &
        PID=$!
        sleep 3
        kill 15 $PID
done
```

A sample result of Peer A I obtained after 10 reconnects. Sometimes it lasts longer, so you may have to be patient.
```
15:27:53 | 16202  | configuration | performing reload of exabgp 4.0.7-40f00b5e
15:27:53 | 16202  | reactor       | loaded new configuration successfully
15:27:56 | 16202  | reactor       | connected to peer-1 with incoming-1 80.81.192.157-80.81.193.157
15:27:59 | 16202  | reactor       | connected to peer-1 with incoming-2 80.81.192.157-80.81.193.157
15:28:02 | 16202  | reactor       | connected to peer-1 with incoming-3 80.81.192.157-80.81.193.157
15:28:05 | 16202  | reactor       | connected to peer-1 with incoming-4 80.81.192.157-80.81.193.157
15:28:08 | 16202  | reactor       | connected to peer-1 with incoming-5 80.81.192.157-80.81.193.157
15:28:11 | 16202  | reactor       | connected to peer-1 with incoming-6 80.81.192.157-80.81.193.157
15:28:14 | 16202  | reactor       | connected to peer-1 with incoming-7 80.81.192.157-80.81.193.157
15:28:17 | 16202  | reactor       | connected to peer-1 with incoming-8 80.81.192.157-80.81.193.157
15:28:20 | 16202  | reactor       | connected to peer-1 with incoming-9 80.81.192.157-80.81.193.157
15:28:23 | 16202  | reactor       | connected to peer-1 with incoming-10 80.81.192.157-80.81.193.157
15:28:26 | 16202  | reactor       | connected to peer-1 with incoming-11 80.81.192.157-80.81.193.157
15:28:29 | 16202  | reactor       | connected to peer-1 with incoming-12 80.81.192.157-80.81.193.157
15:28:32 | 16202  | reactor       | connected to peer-1 with incoming-13 80.81.192.157-80.81.193.157
15:28:35 | 16202  | reactor       | socket error received
15:28:35 | 16202  | reactor       | performing shutdown
15:28:35 | 16202  | network       | stopped listening on 80.81.193.157:179

```

This currently affects my 3 person 1 year project so I would appreciate a fix. I am willing to help out with any further information, but I am travelling so further input might happen before next week's Wednesday.

**Comment by mwichtlh** [comment]
I just realized that this may be a different issue. I am opening a separate issue based on my comment above.

**Comment by mwichtlh** [comment]
I digged a bit into the code and came up with a crude patch that allows me to continue with my project. A proper fix is still appreciated, as my knowledge of the ExaBGP code base is very limited.

The first problem is in peer.py, which may dereference self.proto even if it may have been set to None beforehand.

```
+++ b/lib/exabgp/reactor/peer.py
@@ -150,7 +150,8 @@ class Peer (object):
 
        def _stop (self, message):
                self.generator = False
-               self.proto.close('stop, message [%s]' % message)
+               if self.proto is not None:
+                       self.proto.close('stop, message [%s]' % message)
                self.proto = None
 
        # logging
```

The second problem is in loop.py. Calling fileno() on a socket can trigger a socket error if the socket was closed beforehand. Testing for -1 is not enough to handle this case. 

+++ b/lib/exabgp/reactor/loop.py
@@ -250,8 +250,11 @@ class Reactor (object):
 
                                # do not attempt to listen on closed sockets even if the peer is still here
                                for io in list(workers.keys()):
-                                       if io.fileno() == -1:
-                                               del workers[io]
+                                       try:
+                                               if io.fileno() == -1:
+                                                       del workers[io]
+                                       except socket.error:
+                                               pass
 
                                # give a turn to all the peers
                                for key in list(peers):

**Comment by thomas-mangin** [comment]
Thank you for the patches - I will review them.

**Comment by mwichtlh** [comment]
Great, let me know when you need any further input.

**Comment by bcavns01** [comment]
Would love to see this merged in.  Seems like it might resolve a problem affecting us as well. :)

**Comment by thomas-mangin** [comment]
changed the patch to have:
```
				for io in list(workers.keys()):
					try:
						if io.fileno() == -1:
							del workers[io]
					except socket.error:
						del workers[io]
```
Let me know if you disagree.

**Comment by mwichtlh** [comment]
No, its fine. Cleans up the io which I didn't. Thank you for merging in.

**Comment by bcavns01** [comment]
What is the expected release date for 4.0.9? (to pypi, etc.)  I'll attempt to wait for an official release if it's on its way. :)

**Comment by thomas-mangin** [comment]
I will surely realise one tomorrow as I now have enough bug fixes to justify it.
