### ISSUE TITLE
ImportError Exception upon running exabgp command

### ISSUE THREAD

**Issue by rewajkale** [Exa-Networks/exabgp#868]
##### OS

```
I am using Centos 7 and Python 2.7.5
```

```
[root@~]# uname -a
Linux nfvis 3.10.0-862.11.6.el7.1.x86_64 #1 SMP Thu Nov 15 23:57:25 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
[root@~]# exabgp --version
Traceback (most recent call last):
  File "/sbin/exabgp", line 9, in <module>
    load_entry_point('exabgp==4.0.1', 'console_scripts', 'exabgp')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named exabgp.application
```

##### Installation

```
I installed it using the exabgp 4.0 using the command yum install and rpm -i 
```

##### Environment 

```
[root@~]# exabgp di
Traceback (most recent call last):
  File "/sbin/exabgp", line 9, in <module>
    load_entry_point('exabgp==4.0.1', 'console_scripts', 'exabgp')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named exabgp.application
```

##### Configuration

```
neighbor 182.24.261.176 {

        router-id 152.27.241.198;

        local-address 152.27.241.198;

        local-as 65090;

        peer-as 65070;

        process announce-routes {

            run /usr/bin/python2 /home/admin/exabgp/etc/exabgp/sample.py;

        }

}
```

##### Program output

```
[root@~]# exabgp -d
Traceback (most recent call last):
  File "/sbin/exabgp", line 9, in <module>
    load_entry_point('exabgp==4.0.1', 'console_scripts', 'exabgp')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named exabgp.application
```

##### Steps to reproduce

```
I am able to reproduce it every time I run exabgp command
```

##### Importance

```
I am unable to proceed to implementation of the feature and testing
```

**Comment by thomas-mangin** [comment]
It could be a conflict between a pip install and yum ...
```
pip uninstall exabgp
pip3 uninstall exabgp
``` 
Then uninstall and reinstall exabpg with yum .??

**Comment by thomas-mangin** [comment]
Or the RPM package has a fault ?

**Comment by rewajkale** [comment]
Will you please point to the current location where I can find rpm for this repository? When I git clone the repository it works all good. I would like to have both 4.0 and 3.4 stable rpm for testing. Please help me!
