### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AdamJacobMuller** [Exa-Networks/exabgp#878]
##### Summary
Exabgp crashes with UnicodeDecodeError

##### OS
Debian Stretch 9.6

```
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
```

##### Version
```
ExaBGP : 4.0.8-793a2931
Python : 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
Uname  : Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
Root   : 
```

##### Installation
```
latest OS package
```

##### Environment 

```
[exabgp.daemon]
user = 'exabgp'
```

##### Configuration

```

```

##### Program output

```
exabgp[25722]: 19:43:08 | 31188  | reactor         | connected to peer-2 with outgoing-27 2610:...:fc9a-2610:...:fc99
exabgp[25722]: decoding b'@\x03\x10&\x10\x01\xc8\x00"\x00F\x00\x00\x00\x00\\=\xfc\x9a' failed
exabgp[25722]: Traceback (most recent call last):
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 535, in _run
exabgp[25722]:     for action in self._main():
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 406, in _main
exabgp[25722]:     for message in self.proto.read_message():
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/protocol.py", line 249, in read_message
exabgp[25722]:     raise message
exabgp[25722]: exabgp.bgp.message.notification.Notification: <unprintable Notification object>
exabgp[25722]: During handling of the above exception, another exception occurred:
exabgp[25722]: Traceback (most recent call last):
exabgp[25722]:   File "/usr/sbin/exabgp", line 11, in <module>
exabgp[25722]:     load_entry_point('exabgp==4.0.8', 'console_scripts', 'exabgp')()
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/application/__init__.py", line 13, in run_exabgp
exabgp[25722]:     main()
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/application/bgp.py", line 302, in main
exabgp[25722]:     run(env,comment,configurations,root,options["--validate"])
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/application/bgp.py", line 368, in run
exabgp[25722]:     exit_code = Reactor(configurations).run(validate,root)
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/loop.py", line 259, in run
exabgp[25722]:     action = peer.run()
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 626, in run
exabgp[25722]:     return six.next(self.generator)
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 577, in _run
exabgp[25722]:     notification
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 133, in _reset
exabgp[25722]:     self.proto.close(u"peer reset, message [{0}] error[{1}]".format(message, error))
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/bgp/message/notification.py", line 155, in __str__
exabgp[25722]:     '%s' % (' / %s' % str_ascii(self.data) if self.data else '')
exabgp[25722]:   File "/usr/lib/python3/dist-packages/exabgp/util/__init__.py", line 84, in str_ascii
exabgp[25722]:     return str(bytestring, 'ascii')
exabgp[25722]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 6: ordinal not in range(128)
exabgp[25722]: ********************************************************************************
exabgp[25722]: EXABGP HAD AN INTERNAL ISSUE / HELP US FIX IT
exabgp[25722]: ********************************************************************************
exabgp[25722]: Sorry, you encountered a problem with ExaBGP and we could not keep the program
exabgp[25722]: running.
exabgp[25722]: There are a few things you can do to help us (and yourself):
exabgp[25722]: - make sure you are running the latest version of the code available at
exabgp[25722]:   https://github.com/Exa-Networks/exabgp/releases/latest
exabgp[25722]: - if so report the issue on https://github.com/Exa-Networks/exabgp/issues
exabgp[25722]:   so it can be fixed (github can be searched for similar reports)
exabgp[25722]: PLEASE, when reporting, do include as much information as you can:
exabgp[25722]: - do not obfuscate any data (feel free to send us a private  email with the
exabgp[25722]:   extra information if your business policy is strict on information sharing)
exabgp[25722]:   https://github.com/Exa-Networks/exabgp/wiki/FAQ
exabgp[25722]: - if you can reproduce the issue, run ExaBGP with the command line option -d
exabgp[25722]:   it provides us with much needed information to fix problems quickly
exabgp[25722]: - include the information presented below
exabgp[25722]: Should you not receive an acknowledgment of your issue on github (assignement,
exabgp[25722]: comment, or similar) within a few hours, feel free to email us to make sure
exabgp[25722]: it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
exabgp[25722]: ********************************************************************************
exabgp[25722]: -- Please provide ALL the information below on :
exabgp[25722]: -- https://github.com/Exa-Networks/exabgp/issues
exabgp[25722]: ********************************************************************************
exabgp[25722]: ExaBGP version : 4.0.8-793a2931
exabgp[25722]: Python version : 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
exabgp[25722]: System Uname   : #1 SMP Debian 4.9.144-3.1 (2019-02-19)
exabgp[25722]: System MaxInt  : 9223372036854775807
```

Please take note of this line:
```exabgp[25722]: decoding b'@\x03\x10&\x10\x01\xc8\x00"\x00F\x00\x00\x00\x00\\=\xfc\x9a' failed
```

I added a hook into __init__ str_ascii to print the data which failed to decode.

##### Steps to reproduce

```
Unknown. Seems to happen at random.
```

##### Importance

Yes, this is occurring in a live production environment.

**Comment by thomas-mangin** [comment]
should be now fixed

**Comment by AdamJacobMuller** [comment]
seems like this still happens elsewhere in the code:

```
********************************************************************************
EXABGP HAD AN INTERNAL ISSUE / HELP US FIX IT
********************************************************************************
Sorry, you encountered a problem with ExaBGP and we could not keep the program
running.
There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)
PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below
Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)
********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
ExaBGP version : 4.0.8-793a2931
Python version : 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
System Uname   : #1 SMP Debian 4.9.144-3.1 (2019-02-19)
System MaxInt  : 9223372036854775807
-- Traceback
-- Configuration
-- Logging History
17:22:37 | 19279  | reactor         | connected to peer-2 with outgoing-29 2610::0-2610:1
********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 539, in _run
    for action in self._main():
  File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 410, in _main
    for message in self.proto.read_message():
  File "/usr/lib/python3/dist-packages/exabgp/reactor/protocol.py", line 249, in read_message
    raise message
exabgp.bgp.message.notification.Notification: <unprintable Notification object>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 134, in _reset
    message = u"peer reset, message [{0}] error[{1}]".format(message, error)
  File "/usr/lib/python3/dist-packages/exabgp/bgp/message/notification.py", line 155, in __str__
    '%s' % (' / %s' % str_ascii(self.data) if self.data else '')
  File "/usr/lib/python3/dist-packages/exabgp/util/__init__.py", line 84, in str_ascii
    return str(bytestring, 'ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 6: ordinal not in range(128)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/sbin/exabgp", line 11, in <module>
    load_entry_point('exabgp==4.0.8', 'console_scripts', 'exabgp')()
  File "/usr/lib/python3/dist-packages/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/usr/lib/python3/dist-packages/exabgp/application/bgp.py", line 302, in main
    run(env,comment,configurations,root,options["--validate"])
  File "/usr/lib/python3/dist-packages/exabgp/application/bgp.py", line 368, in run
    exit_code = Reactor(configurations).run(validate,root)
  File "/usr/lib/python3/dist-packages/exabgp/reactor/loop.py", line 259, in run
    action = peer.run()
  File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 630, in run
    return six.next(self.generator)
  File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 581, in _run
    notification
  File "/usr/lib/python3/dist-packages/exabgp/reactor/peer.py", line 136, in _reset
    message = u"peer reset, message [{0}] error[{1}]".format(msg_err, error)
  File "/usr/lib/python3/dist-packages/exabgp/bgp/message/notification.py", line 155, in __str__
    '%s' % (' / %s' % str_ascii(self.data) if self.data else '')
  File "/usr/lib/python3/dist-packages/exabgp/util/__init__.py", line 84, in str_ascii
    return str(bytestring, 'ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 6: ordinal not in range(128)
```

**Comment by thomas-mangin** [comment]
@AdamJacobMuller no news == good news ?

**Comment by AdamJacobMuller** [comment]
@thomas-mangin I haven't tested as I fixed the actual issue that was causing the session disconnects, but, that patch does look better.

Having the session not restart every minute was a better solution :)

**Comment by thomas-mangin** [comment]
LOL - ok, I will close the issue, please re-open if you find something is still wrong.
