### ISSUE TITLE
exabgp withdraw all announced routes 

### ISSUE THREAD

**Issue by brna62petsto** [Exa-Networks/exabgp#891]
##### Summary

```
I'm trying to withdraw all of the routes announced from exabgp to a router without tearing down BGP session, but unable to do so with "exabgpcli clear adj-rib out" and "exabgpcli flush adj-rib out". Please advise if this is the correct way to achieve withdrawal, or if there's another way to do it.
```
##### OS

```
Linux Ubuntu 18.04.2 LTS
```

```
Linux app1234 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

##### Version

```
ExaBGP : 4.0.10-a8462350
Python : 2.7.15rc1 (default, Nov 12 2018, 14:31:15)  [GCC 7.3.0]
Uname  : Linux app1234 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
Root   : /usr/local

```

##### Installation

```
pip
```

##### Environment 

```
[exabgp.log]
message = true
routes = true
```

##### Configuration

```
neighbor 172.16.0.10 {
        local-address 172.16.0.50;
        local-as 65111;
        peer-as 65112;
        listen 179;
        passive;
}

neighbor 172.16.0.239{
        local-address 172.16.0.50;
        local-as 65111;
        peer-as 65112;
        listen 179;
        passive;
}

neighbor 172.16.0.1 {
        local-address 172.16.0.50;
        local-as 65111;
        peer-as 65112;
        listen 179;
        passive;
}

neighbor 172.16.0.2 {
        local-address 172.16.0.50;
        local-as 65111;
        peer-as 65112;
        listen 179;
        passive;
}


process add-delete {
        encoder text;
        run socat '-u' 'pipe:/tmp/app_ip_pipe,nonblock,ignoreeof,perm-late=0666' '-';
}
```

##### Program output

```
log shows commands (clear and flush) being accepted on exabgp (172.16.0.50), but BGP neighbors (172.16.0.239, 172.16.0.1, 172.16.0.2, 172.16.0.10) still see the routes announced from exabgp. 

May 29 09:23:34 app1234 exabgp[1469]: 09:23:34 | 1469   | api             | clearing adjb-rib-out for neighbor 172.16.0.239 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open, neighbor 172.16.0.1 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open, neighbor 172.16.0.10 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open, neighbor 172.16.0.2 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open


May 29 12:05:19 app1234 exabgp[1469]: 12:05:19 | 1469   | api             | Flushing adjb-rib out for neighbor 172.16.0.239 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open, neighbor 172.16.0.1 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open, neighbor 172.16.0.10 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open, neighbor 172.16.0.2 local-ip 172.16.0.50 local-as 65111 peer-as 65112 router-id 172.16.0.50 family-allowed in-open 
```

##### Steps to reproduce

```

```

##### Importance

```
not yet in production
```

**Comment by thomas-mangin** [comment]
The callback does clear the RIB but does not withdraw the routes from the neighbor
```
	def callback (self, peers, direction):
		self.log_message("clearing adjb-rib-%s for %s" % (direction,', '.join(peers if peers else []) if peers is not None else 'all peers'))
		for peer_name in peers:
			peer = reactor.peers.get(peer_name, None)
			if not peer:
				continue
			if direction == 'out':
				peer.neighbor.rib.outgoing.clear()
			else:
				peer.neighbor.rib.incoming.clear()
```

**Comment by thomas-mangin** [comment]
The model of command used by ExaBGP, add all command to a list as iterators and then run one command of each to be fair, means that it is possible that following a `clear` command some other command do add routes to the RIB causing a race-condition.

The engine could be changed so that the callback are aware of their position in the queue, only run if they are first and do not pass the hand to the next acting like barriers. It must be seen if it could cause issues with current users of 4.x as, while it is not stable, it is quite deployed.

**Comment by thomas-mangin** [comment]
flush has the same issue of not being implemented
```
	def callback (self, peers):
		self.log_message("Flushing adjb-rib out for %s" % ', '.join(peers if peers else []) if peers is not None else 'all peers')
		for peer_name in peers:
			peer = reactor.peers.get(peer_name, None)
			if not peer:
				continue
			yield False
```

**Comment by thomas-mangin** [comment]
works for me with my limited testing.

**Comment by thomas-mangin** [comment]
the code for clearly the RIB need to allocate a list of all the changes (already in cache) but for large numbers it may use a little bit more than a little bit of memory.

**Comment by nrocco** [comment]
@thomas-mangin thanks for your quick response on this issue. @brna62petsto and I will try out commit 3e578992e76d482b337933c012f6a77be4ab186f on one of our test exabgp instances tomorrow

**Comment by nrocco** [comment]
@thomas-mangin I tried out the latest master branch (3e578992e76d482b337933c012f6a77be4ab186f) but have troubles running `exabgp` daemon:

```
-- Traceback

Traceback (most recent call last):
  File "/root/test/exabgp/env/bin/exabgp", line 11, in <module>
    load_entry_point('exabgp', 'console_scripts', 'exabgp')()
  File "/root/test/exabgp/lib/exabgp/application/__init__.py", line 13, in run_exabgp
    main()
  File "/root/test/exabgp/lib/exabgp/application/bgp.py", line 302, in main
    run(env,comment,configurations,root,options["--validate"])
  File "/root/test/exabgp/lib/exabgp/application/bgp.py", line 370, in run
    exit_code = Reactor(configurations).run(validate,root)
  File "/root/test/exabgp/lib/exabgp/reactor/loop.py", line 177, in run
    if not self.listener.listen_on(neighbor.md5_ip, neighbor.peer_address, neighbor.listen, neighbor.md5_password, neighbor.md5_base64, neighbor.ttl_in):
  File "/root/test/exabgp/lib/exabgp/reactor/listener.py", line 102, in listen_on
    self._listen(local_addr, remote_addr, port, md5_password, md5_base64, ttl_in)
  File "/root/test/exabgp/lib/exabgp/reactor/listener.py", line 74, in _listen
    MD5(sock,peer_ip.top(),0,md5,md5_base64)
  File "/root/test/exabgp/lib/exabgp/reactor/network/tcp.py", line 168, in MD5
    if md5_bytes:
UnboundLocalError: local variable 'md5_bytes' referenced before assignment
```

Most likely not related to this issue but it is preventing my from testing this :). Any help appreciated.

**Comment by thomas-mangin** [comment]
oops, that should fix this issue https://github.com/Exa-Networks/exabgp/commit/919fc0753ee582515c28510097a2a082ad3ca0a2

**Comment by nrocco** [comment]
@thomas-mangin that was exactly the work around I did too :D.

I got passed the the second issue `LookupError: unknown encoding: string-escape` simply by switching from python2 to python3.

I managed to execute the `clear adj-rib out` command:

```
root@test:/opt/exabgp# env/bin/exabgpcli --env exabgp.env neighbour x.x.x.x clear adj-rib out
```

I see in the logs that the command was accepted, tomorrow I will check on the `x.x.x.x` side to see if things were really cleared.

I did notice in the logs, that even though I specify `neighbour x.x.x.x`, it seems that the routes were cleared on *all* neighbours, not sure if that is intended behaviour:

```
...
Jun 05 20:15:14 test exabgp[13786]: 20:15:14 | 13786  | process         | command from process api-internal-cli-17a6bcf4 : neighbour x.x.x.x clear adj-rib out
Jun 05 20:15:14 test exabgp[13786]: 20:15:14 | 13786  | reactor         | async | api-internal-cli-17a6bcf4 | neighbour x.x.x.x clear adj-rib out
Jun 05 20:15:14 test exabgp[13786]: 20:15:14 | 13786  | api             | clearing adjb-rib-out for neighbor x.x.x.x local-ip y.y.y.y local-as 7890 peer-as 1234 router-id y.y.y.y family-allowed in-open, neighbor c.c.c.c local-ip y.y.y.y local-as 7890 peer-as 1234 router-id 95.211.51.50 family-allowed in-open, neighbor a.a.a.a local-ip y.y.y.y local-as 7890 peer-as 1234 router-id y.y.y.y family-allowed in-open, neighbor b.b.b.b local-ip y.y.y.y local-as 7890 peer-as 1234 router-id y.y.y.y family-allowed in-open
...
```

**Comment by thomas-mangin** [comment]
what version of python2 are you running please ?

**Comment by thomas-mangin** [comment]
will look into the per peer filtering code.

**Comment by thomas-mangin** [comment]
The peer filtering code should work so if you want to provide me with your current configuration it would help :-)

**Comment by nrocco** [comment]
Python2 is
```
$ python2 --version
Python 2.7.15rc1
```

Under python3 it works:
```
$ python3 --version
Python 3.6.7
```

We are running this on:
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Thanks for looking into the `peer filtering code`. And thanks for helping with this.

**Comment by nrocco** [comment]
@thomas-mangin tomorrow I will try clearing a few more times and when I have eyes on the neighbour routing tables I can determine if there is an actual issue or not.

In case of an issue I will provide you with our current configuration.

I will get back to you on this asap

**Comment by thomas-mangin** [comment]
```
  File "/usr/lib/python2.7/subprocess.py", line 1046, in _execute_child
    child_exception = pickle.loads(data)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 977, in load_string
    self.append(rep.decode("string-escape"))
LookupError: unknown encoding: string-escape
```

Congratulation it looks like you found a bug in Python 2.7 !

**Comment by nrocco** [comment]
@thomas-mangin We managed to test the master branch of exabgp (which includes your fix for the clear command) and had successful results.

When we send:

```
exabgpcli neighbor 1.2.3.4 clear adj-rib out
``

We can see the following log message:

```
Jun 12 08:57:17 test exabgp[6117]: 08:57:17 | 6117   | api             | clearing adjb-rib-out for neighbor 1.2.3.4 local-ip 5.6.7.8 local-as 65999 peer-as 65998 router-id 5.6.7.8 family-allowed in-open
```

And on the neighbour side `1.2.3.4` we see all routes cleared.

Are you planning to create a new release that includes this feature any time soon?

If not, we will have to find another way of deploying the exabgp code in our infrastructure :).

Thank you so much for all your efforts so far. This is an awesome project! Keep up the great work.

**Comment by thomas-mangin** [comment]
I am currently fixing an issue with BGP-LS and just performed a change on the AddPath change. Once the code is confirmed good I will release 4.1.0 to PYPI - so yes, soonish.
