### ISSUE TITLE
Running exabgpcli "show adj-rib out extensive" without any routes being announced crashes.

### ISSUE THREAD

**Issue by adudek16** [Exa-Networks/exabgp#955]
Stared exabgp with a bgp session only, no routes exchanged in or our. I can provide the conf file if needed. 

```
root@exabgp-nso-test:/etc/exabgp# exabgpcli  s a o e

********************************************************************************
EXABGP HAD AN INTERNAL ISSUE / HELP US FIX IT
********************************************************************************

Sorry, you encountered a problem with ExaBGP and we could not keep the program
running.

There are a few things you can do to help us (and yourself):
- make sure you are running the latest version of the code available at
  https://github.com/Exa-Networks/exabgp/releases/latest
- if so report the issue on https://github.com/Exa-Networks/exabgp/issues
  so it can be fixed (github can be searched for similar reports)

PLEASE, when reporting, do include as much information as you can:
- do not obfuscate any data (feel free to send us a private  email with the
  extra information if your business policy is strict on information sharing)
  https://github.com/Exa-Networks/exabgp/wiki/FAQ
- if you can reproduce the issue, run ExaBGP with the command line option -d
  it provides us with much needed information to fix problems quickly
- include the information presented below

Should you not receive an acknowledgment of your issue on github (assignement,
comment, or similar) within a few hours, feel free to email us to make sure
it was not overlooked. (please keep in mind the authors are based in GMT/Europe)

********************************************************************************
-- Please provide ALL the information below on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

ExaBGP version : 4.2.6
Python version : 3.7.5 (default, Nov  7 2019, 10:50:52)  [GCC 8.3.0]
System Uname   : #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019
System MaxInt  : 9223372036854775807


-- Traceback


Traceback (most recent call last):
  File "/usr/local/bin/exabgpcli", line 11, in <module>
    sys.exit(run_cli())
  File "/usr/local/lib/python3.7/dist-packages/exabgp/application/__init__.py", line 28, in run_cli
    main()
  File "/usr/local/lib/python3.7/dist-packages/exabgp/application/cli.py", line 194, in main
    if AnswerStream.done.endswith(rbuffer[-len(AnswerStream.done):]):
TypeError: endswith first arg must be str or a tuple of str, not bytes


-- Configuration





-- Logging History







********************************************************************************
-- Please provide _ALL_ the information above on :
-- https://github.com/Exa-Networks/exabgp/issues
********************************************************************************

root@exabgp-nso-test:/etc/exabgp#
```

**Comment by thomas-mangin** [comment]
```
> cat config
neighbor 127.0.0.1 {
	router-id 127.0.0.2;
	local-address 127.0.0.1;
	local-as 12345;
	peer-as 12345;

	family {
	}

	static {
	}
}
1> sudo ./qa/sbin/bgp --port 179 --echo
2> ./sbin/exabgp -d -p config
```
> ./bin/exabgpcli s a o e
command: show adj-rib out extensive
```
```
05:05:51 | 80653  | ka-outgoing-1 | send-timer 55 second(s) left
05:05:52 | 80653  | ka-outgoing-1 | receive-timer 174 second(s) left
05:05:52 | 80653  | ka-outgoing-1 | send-timer 54 second(s) left
05:05:52 | 80653  | process       | command from process api-internal-cli-2823b8bc : show adj-rib out extensive
05:05:52 | 80653  | reactor       | async | api-internal-cli-2823b8bc | show adj-rib out extensive
05:05:52 | 80653  | process       | responding to api-internal-cli-2823b8bc : done
05:05:53 | 80653  | ka-outgoing-1 | receive-timer 173 second(s) left
05:05:53 | 80653  | ka-outgoing-1 | send-timer 53 second(s) left
05:05:54 | 80653  | ka-outgoing-1 | receive-timer 172 second(s) left
05:05:54 | 80653  | ka-outgoing-1 | send-timer 52 second(s) left
^C05:05:54 | 80653  | reactor       | ^C received
```
```
> ./bin/exabgpcli announce route 10.0.0.1 next-hop 127.0.0.1
> /bin/exabgpcli s a o e
command: show adj-rib out extensive
neighbor 127.0.0.1 local-ip 127.0.0.1 local-as 12345 peer-as 12345 router-id 127.0.0.2 family-allowed in-open ipv4 unicast 10.0.0.1/32 next-hop 127.0.0.1
```

**Comment by thomas-mangin** [comment]
```
05:05:46 | 80653  | welcome       | Thank you for using ExaBGP
05:05:46 | 80653  | version       | master-640b05aabdb14707f945415d4f1405993401446f
05:05:46 | 80653  | interpreter   | 3.8.1 (default, Dec 27 2019, 18:06:00)  [Clang 11.0.0 (clang-1100.0.33.16)]
05:05:46 | 80653  | os            | Darwin ThomasMBP.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```
this is master which at the moment is the same as 4.2.6

**Comment by adudek16** [comment]
I’ll try to recreate.

**Comment by adudek16** [comment]
I am not able to recreate at the moment.
