### ISSUE TITLE
Issue parsing process->run if have commas on command

### ISSUE THREAD

**Issue by leleobhz** [Exa-Networks/exabgp#971]
##### Summary
This run command:

```
/usr/bin/socat STDOUT PIPE:/process_sockets/sparkle.cmd,mode=666
```

Leads to this error:

```
socat[15] E exactly 2 addresses required (there are 4); use option "-h" for help
```

Analysing with strace, exabgp tries to subprocess the following execve:

```
38715 execve("/bin/socat", ["/bin/socat", "STDOUT", "PIPE:/process_sockets/sparkle", ",", "cmd"], 0x1f4cfe0 /* 17 vars */ <unfinished ...>
``` 

##### OS
Docker container based on python:3-slim-buster. Kver from host is:

```
Linux <hidden> 5.4.0-0.bpo.2-amd64 #1 SMP Debian 5.4.8-1~bpo10+1 (2020-01-07) x86_64 GNU/Linux
```
##### Version

ExaBGP was built in the following form:
```
pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6
```

##### Steps to reproduce

Just configure any run command that contains commas. and start ExaBGP. In socat case, will not be possible to set any connector options.

##### Importance
This issue is blocking my exabgp adoption because I need to export the socket via volume and need specific permission and user/group configurations set on socat.

**Comment by thomas-mangin** [comment]
Hello @leleobhz 

Can you please provide us your configuration. Thanks.

**Comment by leleobhz** [comment]
Hello Thomas!

I'll just hide the IP address, ok?

```
process sparkle {
        run /usr/bin/socat STDOUT PIPE:/process_sockets/sparkle.cmd;
        encoder json;
}

template {
        neighbor Sparkle {
                local-as <AS-LOCAL>;
                peer-as <AS-UPSTREAM>;
                router-id <HIDDEN-LOCAL>;
                hold-time 90;
                group-updates false;
                adj-rib-in false;
                capability {
                        route-refresh;
                        graceful-restart 120;
                }
                api {
                        processes [ sparkle ];
                }
        }
}

neighbor <HIDDEN-UPSTREAM> {
        inherit Sparkle;
        description "Flowspec - Sparkle";
        local-address <HIDDEN-LOCAL>;
        family {
                ipv4 unicast;
                ipv4 flow;
        }
}
```

Environment is:

```
      exabgp_log_all=false
      exabgp_log_configuration=false
      exabgp_daemon_daemonize=false
```

Do you need something else?

Thanks!

**Comment by thomas-mangin** [comment]
try using quotes ("") after run and before ;

**Comment by leleobhz** [comment]
@thomas-mangin Samething :(

**Comment by thomas-mangin** [comment]
I have successfully run your configuration file on my machine with the socat installed on my mac and an ubuntu VM (Ubuntu 18.04 LTS using multipass).

```
1264 ?        Ss     0:00  \_ sshd: ubuntu [priv]
 1342 ?        S      0:00  |   \_ sshd: ubuntu@pts/0
 1343 pts/0    Ss     0:00  |       \_ -bash
 1525 pts/0    S+     0:00  |           \_ /usr/bin/python3 /home/ubuntu/exabgp/lib/exabgp/application/main.py ../ti
 1547 pts/0    S      0:00  |               \_ /usr/bin/socat STDOUT PIPE:/tmp/sparkle.cmd
```

As installing with
```
pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6
```
does not work, which is a real bug :-(, the reason must be that you must not be using the exabgp version you think you are.

```
root@ubuntu-1:~# pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/Exa-Networks/exabgp.git@4.2.6
  Cloning https://github.com/Exa-Networks/exabgp.git (to 4.2.6) to /tmp/pip-fJW9qf-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-fJW9qf-build/setup.py", line 49, in <module>
        data_files=data_files,
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named exabgp.version

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-fJW9qf-build/
```

**Comment by thomas-mangin** [comment]
https://github.com/Exa-Networks/exabgp/issues/975

**Comment by thomas-mangin** [comment]
could you provide the version of exabpg reported by the executable ?

**Comment by leleobhz** [comment]
> could you provide the version of exabpg reported by the executable ?

Exabgp was built using

pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6

Its a need to get the version? I'll need to change the production environment to replicate the issue at this date (I did a "workarround" using docker binding volumes and manual permission changes).

**Comment by thomas-mangin** [comment]
```
run /usr/bin/socat STDOUT PIPE:/process_sockets/sparkle.cmd;
```
sparkle DOT cmd
```
38715 execve("/bin/socat", ["/bin/socat", "STDOUT", "PIPE:/process_sockets/sparkle", ",", "cmd"], 0x1f4cfe0 /* 17 vars */ <unfinished ...>
```
sparkled COMA cmd

**Comment by thomas-mangin** [comment]
Correct the parser does indeed see this , as a separator.

**Comment by thomas-mangin** [comment]
```
process sparkle {
        run /usr/local/bin/socat STDOUT "PIPE:/process_sockets/sparkle.cmd,mode=666";
        encoder json;
}
```
