### ISSUE TITLE
pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6 fails

### ISSUE THREAD

**Issue by thomas-mangin** [Exa-Networks/exabgp#975]
As installing with
```
pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6
```
does not work, which is a real bug :-(, the reason must be that you must not be using the exabgp version you think you are.

```
root@ubuntu-1:~# pip install git+https://github.com/Exa-Networks/exabgp.git@4.2.6
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/Exa-Networks/exabgp.git@4.2.6
  Cloning https://github.com/Exa-Networks/exabgp.git (to 4.2.6) to /tmp/pip-fJW9qf-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-fJW9qf-build/setup.py", line 49, in <module>
        data_files=data_files,
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
        dist.parse_config_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/usr/lib/python2.7/dist-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named exabgp.version

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-fJW9qf-build/
```

**Comment by thomas-mangin** [comment]
Support for python2 was removed from master so this on is going to remain unresolved :-(
Looking to fix master.

**Comment by thomas-mangin** [comment]
fixed with
https://github.com/Exa-Networks/exabgp/commit/b8c6cd5a1126e573915c7fba34f9732a4af7225c
