### ISSUE TITLE
Installation failure on Ubuntu 18.04 with pip3 install exabgp=4.2.11

### ISSUE THREAD

**Issue by calvincheng8** [Exa-Networks/exabgp#997]
** Bug Report **

**Describe the bug**

I have been installing and running exabgp 4.1.2 without problems on Ubuntu 18.04.5. But when trying to install exabgp release 4.2.11 on a new system, the installation fails.

**To Reproduce**

Running on Ubuntu 18.04.5, with python3.6.

Install fails,

```
$ pip3 install exabgp
Collecting exabgp
  Downloading https://files.pythonhosted.org/packages/9e/ff/481ee16e10c9f90d978e3f11d63f3798671a4bc3203cdbf4091244c79aca/exabgp-4.2.11.tar.gz (401kB)
    100% |████████████████████████████████| 409kB 2.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ggj1bc63/exabgp/setup.py", line 49, in <module>
        data_files=data_files,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 494, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 106, in parse_configuration
        meta.parse()
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 382, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 355, in parse_section
        self[name] = value
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 173, in __setitem__
        value = parser(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 430, in _parse_version
        version = self._parse_attr(value)
      File "/usr/lib/python3/dist-packages/setuptools/config.py", line 305, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'exabgp'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ggj1bc63/exabgp/
```

I checked the version of setuptools, it turns out that it's on version 39.0.1. After upgrading setuptools to the latest 50.3.2, I can install exabgp 4.2.11.

```
~$ pip3 install -U setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl
Installing collected packages: setuptools
Successfully installed setuptools-50.3.2

$ pip3 install exabgp
Collecting exabgp
Collecting setuptools (from exabgp)
  Using cached https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl
Installing collected packages: setuptools, exabgp
Successfully installed exabgp-4.2.11 setuptools-50.3.2
```

**Expected behavior**

Installation should be successful without the need to install latest version of setuptools, or at least specify the dependency on the version of setuptools.

**Environment:**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

$ python3 --version
Python 3.6.9
```
**Additional context**

**Comment by thomas-mangin** [comment]
Thank you for reporting the issue, this way people find this problem will be able to know what they need to make sure to install ExaBGP.

That said, I do not agree it is a bug with ExaBGP as upgrading setuptool fixes the issue. I have neither agreed to fix it (but it was still assigned to me).

While I am sure my answer will disappoint you, I will un-mark this as a bug and will close the issue. I hope you will understand my position.
